#!/bin/bash
#
# On-demand setup for running Toolbox against this hoist-react checkout in a Claude Code on the
# web session. Not run automatically at session start (it is heavyweight) - invoke it from a
# session when live verification in Toolbox is needed:
#
#   .claude/hooks/setup-toolbox.sh
#
# Clones xh/toolbox as a sibling of this hoist-react checkout - the layout `pnpm startWithHoist`
# expects - and writes a toolbox/.env configured for a fully self-contained run: transient
# in-memory H2 database and form-based login (no MySQL, no OAuth). See toolbox/.env.template
# and the Toolbox README for background on these settings.
#
# Also clones xh/hoist-core as a sibling, so Toolbox's Docs tab resolves hoist-core content from
# disk rather than the GitHub API, and (in web sessions only) installs a Gradle init script that
# mirrors Maven Central. Both work around sandbox restrictions documented in README.md.
#
# Requires the same environment configuration as session-start.sh, plus the Gradle/Maven domains
# in the network policy - see README.md in this directory. After running, start the app with:
#
#   1. Server: (cd ../toolbox && ./gradlew bootRun)                     # API on :8080
#   2. Client: (cd ../toolbox/client-app && pnpm startWithHoist)        # dev server on :3000
#   3. Open http://localhost:3000/app - log in with the bootstrap admin credentials below.
set -euo pipefail

HOIST_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
TOOLBOX_DIR="$(dirname "$HOIST_DIR")/toolbox"
HOIST_CORE_DIR="$(dirname "$HOIST_DIR")/hoist-core"
GRADLE_INIT_SCRIPT="$HOME/.gradle/init.d/central-mirror.gradle"

if [ ! -d "$TOOLBOX_DIR/.git" ]; then
    echo "setup-toolbox: cloning xh/toolbox to $TOOLBOX_DIR..."
    git clone --depth 1 https://github.com/xh/toolbox "$TOOLBOX_DIR"
else
    echo "setup-toolbox: found existing toolbox checkout at $TOOLBOX_DIR."
fi

# Toolbox's DocsService serves hoist-react and hoist-core docs, preferring a local sibling
# checkout (`../<repo>/docs/README.md`) and falling back to the GitHub API. That fallback is
# blocked in a web session for any repo outside the session's scope, so clone hoist-core to keep
# the Docs tab working. Plain git clone over github.com needs no API access. Harmless to the
# build: Toolbox only composite-builds a sibling hoist-core when runHoistInline=true, which it
# is not by default.
if [ ! -d "$HOIST_CORE_DIR/.git" ]; then
    echo "setup-toolbox: cloning xh/hoist-core to $HOIST_CORE_DIR (for the Docs tab)..."
    git clone --depth 1 https://github.com/xh/hoist-core "$HOIST_CORE_DIR"
else
    echo "setup-toolbox: found existing hoist-core checkout at $HOIST_CORE_DIR."
fi

if [ ! -f "$TOOLBOX_DIR/.env" ]; then
    echo 'setup-toolbox: writing .env for a self-contained run (H2 + form-based login)...'
    cat > "$TOOLBOX_DIR/.env" << 'EOF'
# Generated by hoist-react/.claude/hooks/setup-toolbox.sh for local verification runs only.
APP_TOOLBOX_ENVIRONMENT=Development
APP_TOOLBOX_USE_H2=true

# DB connection vars are required by the build but unused when running with H2.
APP_TOOLBOX_DB_HOST=localhost
APP_TOOLBOX_DB_SCHEMA=toolbox
APP_TOOLBOX_DB_USER=toolbox
APP_TOOLBOX_DB_PASSWORD=toolbox

# Form-based login with a local-only bootstrap admin - no OAuth provider required.
APP_TOOLBOX_OAUTH_PROVIDER=NONE
APP_TOOLBOX_BOOTSTRAP_ADMIN_USER=toolbox-admin@xh.io
APP_TOOLBOX_BOOTSTRAP_ADMIN_PASSWORD=localDevOnly
EOF
fi

# Maven Central (repo.maven.apache.org and repo1.maven.org alike) rate-limits the sandbox hard
# enough to block `bootRun`: a single HTTP 429 disables MavenRepo for the whole build and cascades
# into unrelated resolution failures. Prefer the already-allowlisted repo.grails.org virtual repo,
# which proxies Central and serves the full dependency set. Web sessions only, and never clobber an
# existing file - this is global Gradle config, not project config.
if [ "${CLAUDE_CODE_REMOTE:-}" = "true" ] && [ ! -f "$GRADLE_INIT_SCRIPT" ]; then
    echo "setup-toolbox: writing Maven Central mirror to $GRADLE_INIT_SCRIPT..."
    mkdir -p "$(dirname "$GRADLE_INIT_SCRIPT")"
    cat > "$GRADLE_INIT_SCRIPT" << 'EOF'
// Generated by hoist-react/.claude/hooks/setup-toolbox.sh for Claude Code on the web sessions.
// Maven Central returns HTTP 429 (Cloudflare rate limit) in the sandbox; repo.grails.org/grails/core
// is an allowlisted Artifactory virtual repo that proxies it. Delete this file to opt back out.
def MIRROR = 'https://repo.grails.org/grails/core'

def prepend = { rh ->
    if (rh.findByName('centralMirror') == null) {
        def repo = rh.maven { name = 'centralMirror'; url = MIRROR }
        rh.remove(repo)
        rh.addFirst(repo)
    }
}

beforeSettings { settings ->
    prepend(settings.pluginManagement.repositories)
    settings.pluginManagement.repositories.gradlePluginPortal()
    settings.pluginManagement.repositories.mavenCentral()
}

allprojects { p ->
    prepend(p.buildscript.repositories)
    prepend(p.repositories)
}
EOF
elif [ -f "$GRADLE_INIT_SCRIPT" ]; then
    echo "setup-toolbox: leaving existing Gradle init script at $GRADLE_INIT_SCRIPT untouched."
fi

echo 'setup-toolbox: installing toolbox client dependencies...'
(cd "$TOOLBOX_DIR/client-app" && pnpm install)

cat << EOF

setup-toolbox: done. To run Toolbox:
  1. Server: (cd $TOOLBOX_DIR && ./gradlew bootRun)
  2. Client: (cd $TOOLBOX_DIR/client-app && pnpm startWithHoist)
  3. Open http://localhost:3000/app - log in as toolbox-admin@xh.io / localDevOnly
EOF
