#!/bin/bash
#
# On-demand setup for running Toolbox against this hoist-react checkout in a Claude Code on the
# web session. Not run automatically at session start (it is heavyweight) - invoke it from a
# session when live verification in Toolbox is needed:
#
#   .claude/hooks/setup-toolbox.sh
#
# Clones xh/toolbox as a sibling of this hoist-react checkout - the layout `pnpm startWithHoist`
# expects - and writes a toolbox/.env configured for a fully self-contained run: transient
# in-memory H2 database and form-based login (no MySQL, no OAuth). See toolbox/.env.template
# and the Toolbox README for background on these settings.
#
# Requires the same environment configuration as session-start.sh, plus the Gradle/Maven domains
# in the network policy - see README.md in this directory. After running, start the app with:
#
#   1. Server: (cd ../toolbox && ./gradlew bootRun)                     # API on :8080
#   2. Client: (cd ../toolbox/client-app && pnpm startWithHoist)        # dev server on :3000
#   3. Open http://localhost:3000/app - log in with the bootstrap admin credentials below.
set -euo pipefail

HOIST_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
TOOLBOX_DIR="$(dirname "$HOIST_DIR")/toolbox"

if [ ! -d "$TOOLBOX_DIR/.git" ]; then
    echo "setup-toolbox: cloning xh/toolbox to $TOOLBOX_DIR..."
    git clone --depth 1 https://github.com/xh/toolbox "$TOOLBOX_DIR"
else
    echo "setup-toolbox: found existing toolbox checkout at $TOOLBOX_DIR."
fi

if [ ! -f "$TOOLBOX_DIR/.env" ]; then
    echo 'setup-toolbox: writing .env for a self-contained run (H2 + form-based login)...'
    cat > "$TOOLBOX_DIR/.env" << 'EOF'
# Generated by hoist-react/.claude/hooks/setup-toolbox.sh for local verification runs only.
APP_TOOLBOX_ENVIRONMENT=Development
APP_TOOLBOX_USE_H2=true

# DB connection vars are required by the build but unused when running with H2.
APP_TOOLBOX_DB_HOST=localhost
APP_TOOLBOX_DB_SCHEMA=toolbox
APP_TOOLBOX_DB_USER=toolbox
APP_TOOLBOX_DB_PASSWORD=toolbox

# Form-based login with a local-only bootstrap admin - no OAuth provider required.
APP_TOOLBOX_OAUTH_PROVIDER=NONE
APP_TOOLBOX_BOOTSTRAP_ADMIN_USER=toolbox-admin@xh.io
APP_TOOLBOX_BOOTSTRAP_ADMIN_PASSWORD=localDevOnly
EOF
fi

echo 'setup-toolbox: installing toolbox client dependencies...'
(cd "$TOOLBOX_DIR/client-app" && pnpm install)

cat << EOF

setup-toolbox: done. To run Toolbox:
  1. Server: (cd $TOOLBOX_DIR && ./gradlew bootRun)
  2. Client: (cd $TOOLBOX_DIR/client-app && pnpm startWithHoist)
  3. Open http://localhost:3000/app - log in as toolbox-admin@xh.io / localDevOnly
EOF
