import {GridModel} from '@xh/hoist/cmp/grid';
import {ColumnGroup} from '@xh/hoist/cmp/grid/columns/ColumnGroup';
import type {ColumnOrGroup} from '@xh/hoist/cmp/grid/Types';
import {HoistModel} from '@xh/hoist/core';
import type {HSide} from '@xh/hoist/core';
import {action, bindable, computed, makeObservable} from '@xh/hoist/mobx';
import {withDefault} from '@xh/hoist/utils/js';
import {PinSectionModel} from './PinSectionModel';
import {managed} from '@xh/hoist/core';

/** Shape of record data in the ColumnChooser's internal grids. */
export interface ColumnChooserData {
    id: string;
    name: string;
    description: string;
    visible: boolean;
    pinned: HSide;
    isGroup: boolean;
    hideable: boolean;
    parentId: string;
    sortOrder: number;
    leafColIds: string[];
}

/**
 * Model for the new ColumnChooser component. Manages an internal representation of the target
 * grid's columns and provides controls for visibility toggling, reordering, and pin management.
 */
export class ColumnChooserModel extends HoistModel {
    override xhImpl = true;

    /** True to display columns grouped under their column group headers. */
    @bindable showGroups: boolean = true;
    setShowGroups: (v: boolean) => void; // auto-generated by @bindable

    /** Current quick-filter text. */
    @bindable filterText: string = '';

    @managed leftPinModel = new PinSectionModel({pinned: 'left'});
    @managed centerPinModel = new PinSectionModel({pinned: null});
    @managed rightPinModel = new PinSectionModel({pinned: 'right'});

    /** Description of the currently selected column, or empty string if none selected. */
    @computed
    get selectedDescription(): string {
        for (const pinModel of [this.leftPinModel, this.centerPinModel, this.rightPinModel]) {
            const rec = pinModel.gridModel.selectedRecord;
            if (rec) return rec.data.description ?? '';
        }
        return '';
    }

    /** True when the target grid has at least one column group. */
    @computed
    get hasColumnGroups(): boolean {
        if (!this.gridModel) return false;
        return this.gridModel.columns.some(c => c instanceof ColumnGroup);
    }

    /** The GridModel whose columns this chooser manages. */
    @computed
    get gridModel(): GridModel {
        const ret = withDefault(this.componentProps?.gridModel, this.lookupModel(GridModel));
        if (!ret) {
            this.logError("No GridModel available. Provide via a 'gridModel' prop, or context.");
        }
        return ret;
    }

    constructor() {
        super();
        makeObservable(this);
    }

    override onLinked() {
        // Wire visibility toggle callbacks
        this.leftPinModel.onToggleVisibility = id => this.toggleVisibility(id);
        this.centerPinModel.onToggleVisibility = id => this.toggleVisibility(id);
        this.rightPinModel.onToggleVisibility = id => this.toggleVisibility(id);

        // Wire reorder callbacks
        this.leftPinModel.onReorder = (ids, pinned) => this.handleReorder(ids, pinned);
        this.centerPinModel.onReorder = (ids, pinned) => this.handleReorder(ids, pinned);
        this.rightPinModel.onReorder = (ids, pinned) => this.handleReorder(ids, pinned);

        // React to changes in the target grid's column state
        this.addReaction({
            track: () => [this.gridModel?.columnState, this.gridModel?.columns],
            run: () => this.syncFromGridModel(),
            fireImmediately: true
        });

        // Re-sync when tree/flat mode toggled
        this.addReaction({
            track: () => this.showGroups,
            run: () => this.syncFromGridModel()
        });

        // Apply quick-filter when filterText changes
        this.addReaction({
            track: () => this.filterText,
            run: filterText => this.applyFilter(filterText),
            debounce: 200
        });

        // Register cross-zone drop zones when AG APIs become available
        this.addReaction({
            track: () => [
                this.leftPinModel.gridModel.agApi,
                this.centerPinModel.gridModel.agApi,
                this.rightPinModel.gridModel.agApi
            ],
            run: ([leftApi, centerApi, rightApi]) => {
                if (leftApi && centerApi && rightApi) {
                    this.registerDropZones();
                }
            },
            fireImmediately: true
        });

        // Ensure only one pin section has a selection at a time
        const pinModels = [this.leftPinModel, this.centerPinModel, this.rightPinModel];
        for (const pinModel of pinModels) {
            const others = pinModels.filter(m => m !== pinModel);
            this.addReaction({
                track: () => pinModel.gridModel.selectedRecord,
                run: rec => {
                    if (rec) {
                        others.forEach(m => m.gridModel.clearSelection());
                    }
                }
            });
        }
    }

    toggleVisibility(recordId: string) {
        const {gridModel} = this;
        if (!gridModel) return;

        const record = this.findRecord(recordId);
        if (!record || !record.data.hideable) return;

        const newHidden = record.data.visible;
        const colIds: string[] = record.data.leafColIds;

        gridModel.updateColumnState(colIds.map(colId => ({colId, hidden: newHidden})));
    }

    //------------------
    // Implementation
    //------------------
    private dropZonesRegistered = false;

    private registerDropZones() {
        if (this.dropZonesRegistered) return;

        const models = [this.leftPinModel, this.centerPinModel, this.rightPinModel];

        // Each grid registers the other two as drop targets
        for (const source of models) {
            for (const target of models) {
                if (source === target) continue;
                source.registerDropZone(target);
            }
        }

        // Wire callbacks
        for (const model of models) {
            model.onCrossZoneDrop = (records, targetPinned) =>
                this.handleCrossZoneDrop(records, targetPinned);
        }

        this.dropZonesRegistered = true;
    }

    private handleCrossZoneDrop(records: ColumnChooserData[], targetPinned: HSide) {
        const {gridModel} = this;
        if (!gridModel) return;

        const colIds = records.flatMap(r => r.leafColIds);
        gridModel.updateColumnState(colIds.map(colId => ({colId, pinned: targetPinned})));
    }

    @action
    private syncFromGridModel() {
        if (!this.gridModel) return;
        const records = this.buildRecords();
        const {showGroups} = this;
        this.leftPinModel.loadRecords(records, showGroups);
        this.centerPinModel.loadRecords(records, showGroups);
        this.rightPinModel.loadRecords(records, showGroups);
    }

    /**
     * Build chooser records bottom-up from columnState order.
     *
     * Iterates the columnState array (source of truth for display order), and for each leaf
     * column looks up its parent group chain from the column definitions. Adjacent columns
     * sharing the same group are merged under a single group node. Non-adjacent columns from
     * the same group produce separate group instances (split groups).
     */
    private buildRecords(): ColumnChooserData[] {
        const {gridModel} = this,
            {columnState} = gridModel;

        // Build a map of colId -> parent group chain (innermost first)
        const parentChainMap = new Map<string, ColumnGroup[]>();
        const buildParentChains = (cols: ColumnOrGroup[], ancestors: ColumnGroup[]) => {
            for (const col of cols) {
                if (col instanceof ColumnGroup) {
                    buildParentChains(col.children, [...ancestors, col]);
                } else {
                    parentChainMap.set(col.colId, ancestors);
                }
            }
        };
        buildParentChains(gridModel.columns, []);

        // Walk columnState in order, building leaf records and group records as needed.
        // Track open group instances at each depth so we can merge adjacent siblings
        // and split groups that are non-adjacent.
        const records: ColumnChooserData[] = [];
        const groupInstanceCounts = new Map<string, number>();

        // activeGroups[depth] = the groupId of the currently open group at that depth
        const activeGroups: (string | null)[] = [];

        for (let i = 0; i < columnState.length; i++) {
            const cs = columnState[i];
            const col = gridModel.findColumn(gridModel.columns, cs.colId);
            if (!col || col.excludeFromChooser) continue;

            const chain = parentChainMap.get(cs.colId) ?? [];

            // Determine which groups in the chain are still active (same group, same depth)
            // and which need new instances
            let sharedDepth = 0;
            for (let d = 0; d < chain.length; d++) {
                if (activeGroups[d] === chain[d].groupId) {
                    sharedDepth = d + 1;
                } else {
                    break;
                }
            }

            // Close groups deeper than the shared depth
            activeGroups.length = sharedDepth;

            // Open new group instances for the rest of the chain
            for (let d = sharedDepth; d < chain.length; d++) {
                const group = chain[d];
                const count = (groupInstanceCounts.get(group.groupId) ?? 0) + 1;
                groupInstanceCounts.set(group.groupId, count);

                const instanceId = count > 1 ? `${group.groupId}_${count}` : group.groupId;
                const parentInstanceId =
                    d > 0
                        ? this.getActiveGroupId(activeGroups, chain, d - 1, groupInstanceCounts)
                        : null;

                const leafCols = group.getLeafColumns();
                const leafColIds = leafCols.map(lc => lc.colId);

                records.push({
                    id: instanceId,
                    name: typeof group.headerName === 'string' ? group.headerName : group.groupId,
                    description: '',
                    visible: leafColIds.every(id => !gridModel.getStateForColumn(id)?.hidden),
                    pinned: null,
                    isGroup: true,
                    hideable: leafCols.some(lc => lc.hideable),
                    parentId: parentInstanceId,
                    sortOrder: i,
                    leafColIds
                });

                activeGroups[d] = group.groupId;
            }

            // Add the leaf column record
            const parentInstanceId =
                chain.length > 0
                    ? this.getActiveGroupId(
                          activeGroups,
                          chain,
                          chain.length - 1,
                          groupInstanceCounts
                      )
                    : null;

            records.push({
                id: cs.colId,
                name: col.chooserName,
                description: col.chooserDescription ?? '',
                visible: !cs.hidden,
                pinned: cs.pinned ?? null,
                isGroup: false,
                hideable: col.hideable,
                parentId: parentInstanceId,
                sortOrder: i,
                leafColIds: [cs.colId]
            });
        }

        return records;
    }

    /** Get the instance ID for the active group at a given depth. */
    private getActiveGroupId(
        activeGroups: (string | null)[],
        chain: ColumnGroup[],
        depth: number,
        groupInstanceCounts: Map<string, number>
    ): string {
        const groupId = chain[depth].groupId;
        const count = groupInstanceCounts.get(groupId) ?? 1;
        return count > 1 ? `${groupId}_${count}` : groupId;
    }

    private applyFilter(filterText: string) {
        const filter = filterText
            ? rec => {
                  const lower = filterText.toLowerCase();
                  if (!rec.data.isGroup) {
                      return rec.data.name?.toLowerCase().includes(lower);
                  }
                  return rec.data.leafColIds?.some(colId => {
                      const leaf = rec.store.getById(colId);
                      return leaf?.data.name?.toLowerCase().includes(lower);
                  });
              }
            : null;

        this.leftPinModel.gridModel.store.setFilter(filter);
        this.centerPinModel.gridModel.store.setFilter(filter);
        this.rightPinModel.gridModel.store.setFilter(filter);
    }

    private handleReorder(reorderedColIds: string[], pinned: HSide) {
        const {gridModel} = this;
        if (!gridModel) return;

        // Build the full new column order: left-pinned + center + right-pinned
        const leftIds = this.getOrderedColIds(
            this.leftPinModel,
            pinned === 'left' ? reorderedColIds : null
        );
        const centerIds = this.getOrderedColIds(
            this.centerPinModel,
            pinned === null ? reorderedColIds : null
        );
        const rightIds = this.getOrderedColIds(
            this.rightPinModel,
            pinned === 'right' ? reorderedColIds : null
        );

        const fullOrder = [...leftIds, ...centerIds, ...rightIds];

        // Build full columnState in new order — must include ALL leaf columns for
        // GridModel.updateColumnState() to recognize it as a reorder operation
        const newState = fullOrder.map(colId => {
            const existing = gridModel.getStateForColumn(colId);
            return {...existing};
        });

        gridModel.updateColumnState(newState);
    }

    private getOrderedColIds(pinModel: PinSectionModel, overrideOrder: string[]): string[] {
        if (overrideOrder) return overrideOrder;
        // Read current leaf column order from this pin section's AG Grid
        const ids: string[] = [];
        pinModel.gridModel.agApi?.forEachNodeAfterFilterAndSort(node => {
            if (node.data && !node.data.isGroup) {
                ids.push(node.data.id);
            }
        });
        return ids;
    }

    async restoreDefaultsAsync() {
        await this.gridModel?.restoreDefaultsAsync();
    }

    private findRecord(id: string) {
        return (
            this.leftPinModel.gridModel.store.getById(id) ??
            this.centerPinModel.gridModel.store.getById(id) ??
            this.rightPinModel.gridModel.store.getById(id)
        );
    }
}
