import {GridModel} from '@xh/hoist/cmp/grid';
import {ColumnGroup} from '@xh/hoist/cmp/grid/columns/ColumnGroup';
import type {ColumnOrGroup} from '@xh/hoist/cmp/grid/Types';
import {HoistModel} from '@xh/hoist/core';
import type {HSide} from '@xh/hoist/core';
import {action, bindable, computed, makeObservable} from '@xh/hoist/mobx';
import {withDefault} from '@xh/hoist/utils/js';
import {PinSectionModel} from './PinSectionModel';
import {managed} from '@xh/hoist/core';

/** Shape of records in the ColumnChooser's internal grids. */
export interface ColumnChooserRecord {
    id: string;
    name: string;
    description: string;
    visible: boolean;
    pinned: HSide;
    isGroup: boolean;
    hideable: boolean;
    parentId: string;
    sortOrder: number;
    leafColIds: string[];
}

/**
 * Model for the new ColumnChooser component. Manages an internal representation of the target
 * grid's columns and provides controls for visibility toggling, reordering, and pin management.
 */
export class ColumnChooserModel extends HoistModel {
    override xhImpl = true;

    /** Show column groups as tree hierarchy (true) or flat leaf list (false). */
    @bindable showGroups: boolean = true;
    setShowGroups: (v: boolean) => void; // auto-generated by @bindable

    /** Current quick-filter text. */
    @bindable filterText: string = '';

    @managed leftPinModel = new PinSectionModel({pinned: 'left'});
    @managed centerPinModel = new PinSectionModel({pinned: null});
    @managed rightPinModel = new PinSectionModel({pinned: 'right'});

    /** Description of the currently selected column, or empty string if none selected. */
    @computed
    get selectedDescription(): string {
        for (const pinModel of [this.leftPinModel, this.centerPinModel, this.rightPinModel]) {
            const rec = pinModel.gridModel.selectedRecord;
            if (rec) return rec.data.description ?? '';
        }
        return '';
    }

    /** True when the target grid has at least one column group. */
    @computed
    get hasColumnGroups(): boolean {
        if (!this.gridModel) return false;
        return this.gridModel.columns.some(c => c instanceof ColumnGroup);
    }

    /** The GridModel whose columns this chooser manages. */
    @computed
    get gridModel(): GridModel {
        const ret = withDefault(this.componentProps?.gridModel, this.lookupModel(GridModel));
        if (!ret) {
            this.logError("No GridModel available. Provide via a 'gridModel' prop, or context.");
        }
        return ret;
    }

    constructor() {
        super();
        makeObservable(this);
    }

    override onLinked() {
        // Wire visibility toggle callbacks
        this.leftPinModel.onToggleVisibility = id => this.toggleVisibility(id);
        this.centerPinModel.onToggleVisibility = id => this.toggleVisibility(id);
        this.rightPinModel.onToggleVisibility = id => this.toggleVisibility(id);

        // React to changes in the target grid's column state
        this.addReaction({
            track: () => [this.gridModel?.columnState, this.gridModel?.columns],
            run: () => this.syncFromGridModel(),
            fireImmediately: true
        });

        // Re-sync when tree/flat mode toggled
        this.addReaction({
            track: () => this.showGroups,
            run: () => this.syncFromGridModel()
        });

        // Apply quick-filter when filterText changes
        this.addReaction({
            track: () => this.filterText,
            run: filterText => this.applyFilter(filterText),
            debounce: 200
        });

        // Ensure only one pin section has a selection at a time
        const pinModels = [this.leftPinModel, this.centerPinModel, this.rightPinModel];
        for (const pinModel of pinModels) {
            const others = pinModels.filter(m => m !== pinModel);
            this.addReaction({
                track: () => pinModel.gridModel.selectedRecord,
                run: rec => {
                    if (rec) {
                        others.forEach(m => m.gridModel.clearSelection());
                    }
                }
            });
        }
    }

    toggleVisibility(recordId: string) {
        const {gridModel} = this;
        if (!gridModel) return;

        const record = this.findRecord(recordId);
        if (!record || !record.data.hideable) return;

        const newHidden = record.data.visible;
        const colIds: string[] = record.data.leafColIds;

        gridModel.updateColumnState(colIds.map(colId => ({colId, hidden: newHidden})));
    }

    //------------------
    // Implementation
    //------------------
    @action
    private syncFromGridModel() {
        if (!this.gridModel) return;
        const records = this.buildRecords();
        const {showGroups} = this;
        this.leftPinModel.loadRecords(records, showGroups);
        this.centerPinModel.loadRecords(records, showGroups);
        this.rightPinModel.loadRecords(records, showGroups);
    }

    private buildRecords(): ColumnChooserRecord[] {
        const {gridModel} = this,
            {columns, columnState} = gridModel,
            records: ColumnChooserRecord[] = [];

        const orderMap = new Map(columnState.map((cs, idx) => [cs.colId, idx]));

        const walk = (cols: ColumnOrGroup[], parentId: string = null) => {
            for (const col of cols) {
                if (col instanceof ColumnGroup) {
                    const leafCols = col.getLeafColumns();
                    const leafColIds = leafCols.map(lc => lc.colId);
                    const leafStates = leafColIds.map(id => gridModel.getStateForColumn(id));
                    const allVisible = leafStates.every(s => !s.hidden);

                    records.push({
                        id: col.groupId,
                        name: typeof col.headerName === 'string' ? col.headerName : col.groupId,
                        description: '',
                        visible: allVisible,
                        pinned: null,
                        isGroup: true,
                        hideable: leafCols.some(lc => lc.hideable),
                        parentId,
                        sortOrder: Math.min(...leafColIds.map(id => orderMap.get(id) ?? Infinity)),
                        leafColIds
                    });

                    walk(col.children, col.groupId);
                } else {
                    if (col.excludeFromChooser) continue;
                    const state = gridModel.getStateForColumn(col.colId);
                    records.push({
                        id: col.colId,
                        name: col.chooserName,
                        description: col.chooserDescription ?? '',
                        visible: !state.hidden,
                        pinned: state.pinned ?? null,
                        isGroup: false,
                        hideable: col.hideable,
                        parentId,
                        sortOrder: orderMap.get(col.colId) ?? Infinity,
                        leafColIds: [col.colId]
                    });
                }
            }
        };

        walk(columns);
        return records;
    }

    private applyFilter(filterText: string) {
        const filter = filterText
            ? rec => {
                  const lower = filterText.toLowerCase();
                  if (!rec.data.isGroup) {
                      return rec.data.name?.toLowerCase().includes(lower);
                  }
                  return rec.data.leafColIds?.some(colId => {
                      const leaf = rec.store.getById(colId);
                      return leaf?.data.name?.toLowerCase().includes(lower);
                  });
              }
            : null;

        this.leftPinModel.gridModel.store.setFilter(filter);
        this.centerPinModel.gridModel.store.setFilter(filter);
        this.rightPinModel.gridModel.store.setFilter(filter);
    }

    private findRecord(id: string) {
        return (
            this.leftPinModel.gridModel.store.getById(id) ??
            this.centerPinModel.gridModel.store.getById(id) ??
            this.rightPinModel.gridModel.store.getById(id)
        );
    }
}
