/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2021 Extremely Heavy Industries Inc.
 */
export * from './Icon';
export * from './XHLogo';

import {library} from '@fortawesome/fontawesome-svg-core';
import {
    faAddressCard as faAddressCardLight,
    faAlignJustify as faAlignJustifyLight,
    faAnalytics as faAnalyticsLight,
    faAngleDoubleDown as faAngleDoubleDownLight,
    faAngleDoubleLeft as faAngleDoubleLeftLight,
    faAngleDoubleRight as faAngleDoubleRightLight,
    faAngleDoubleUp as faAngleDoubleUpLight,
    faAngleDown as faAngleDownLight,
    faAngleLeft as faAngleLeftLight,
    faAngleRight as faAngleRightLight,
    faAngleUp as faAngleUpLight,
    faArrowDown as faArrowDownLight,
    faArrowLeft as faArrowLeftLight,
    faArrowRight as faArrowRightLight,
    faArrowToBottom as faArrowToBottomLight,
    faArrowToLeft as faArrowToLeftLight,
    faArrowToRight as faArrowToRightLight,
    faArrowToTop as faArrowToTopLight,
    faArrowUp as faArrowUpLight,
    faArrowsH as faArrowsHLight,
    faArrowsV as faArrowsVLight,
    faBalanceScale as faBalanceScaleLight,
    faBalanceScaleLeft as faBalanceScaleLeftLight,
    faBalanceScaleRight as faBalanceScaleRightLight,
    faBan as faBanLight,
    faBars as faBarsLight,
    faBolt as faBoltLight,
    faBook as faBookLight,
    faBookmark as faBookmarkLight,
    faBooks as faBooksLight,
    faBox as faBoxLight,
    faBoxFull as faBoxFullLight,
    faBracketsCurly as faBracketsCurlyLight,
    faBreadSlice as faBreadSliceLight,
    faBriefcase as faBriefcaseLight,
    faBrowser as faBrowserLight,
    faBuilding as faBuildingLight,
    faBullhorn as faBullhornLight,
    faBullseyeArrow as faBullseyeArrowLight,
    faCalculator as faCalculatorLight,
    faCalendarDay as faCalendarDayLight,
    faCamera as faCameraLight,
    faCaretLeft as faCaretLeftLight,
    faCaretRight as faCaretRightLight,
    faChartArea as faChartAreaLight,
    faChartColumn as faChartColumnLight,
    faChartLine as faChartLineLight,
    faChartPie as faChartPieLight,
    faCheck as faCheckLight,
    faCheckCircle as faCheckCircleLight,
    faChess as faChessLight,
    faChessKnightAlt as faChessKnightAltLight,
    faChevronDown as faChevronDownLight,
    faChevronLeft as faChevronLeftLight,
    faChevronRight as faChevronRightLight,
    faChevronUp as faChevronUpLight,
    faCircle as faCircleLight,
    faClipboard as faClipboardLight,
    faClock as faClockLight,
    faCloudDownload as faCloudDownloadLight,
    faCloudUpload as faCloudUploadLight,
    faCode as faCodeLight,
    faCog as faCogLight,
    faCogs as faCogsLight,
    faCommentDots as faCommentDotsLight,
    faCompressAlt as faCompressAltLight,
    faCopy as faCopyLight,
    faCrosshairs as faCrosshairsLight,
    faCube as faCubeLight,
    faDatabase as faDatabaseLight,
    faDesktop as faDesktopLight,
    faDollarSign as faDollarSignLight,
    faDownload as faDownloadLight,
    faEdit as faEditLight,
    faEllipsisH as faEllipsisHLight,
    faEllipsisV as faEllipsisVLight,
    faEnvelope as faEnvelopeLight,
    faEquals as faEqualsLight,
    faEuroSign as faEuroSignLight,
    faExchange as faExchangeLight,
    faExclamationCircle as faExclamationCircleLight,
    faExclamationSquare as faExclamationSquareLight,
    faExclamationTriangle as faExclamationTriangleLight,
    faExpandAlt as faExpandAltLight,
    faExternalLink as faExternalLinkLight,
    faEye as faEyeLight,
    faEyeSlash as faEyeSlashLight,
    faFile as faFileLight,
    faFileAlt as faFileAltLight,
    faFileArchive as faFileArchiveLight,
    faFileCertificate as faFileCertificateLight,
    faFileCsv as faFileCsvLight,
    faFileExcel as faFileExcelLight,
    faFileImage as faFileImageLight,
    faFilePdf as faFilePdfLight,
    faFilePowerpoint as faFilePowerpointLight,
    faFileWord as faFileWordLight,
    faFilter as faFilterLight,
    faFlag as faFlagLight,
    faFlask as faFlaskLight,
    faFolder as faFolderLight,
    faFolderOpen as faFolderOpenLight,
    faFunction as faFunctionLight,
    faGift as faGiftLight,
    faGlobe as faGlobeLight,
    faGlobeAmericas as faGlobeAmericasLight,
    faGraduationCap as faGraduationCapLight,
    faGreaterThan as faGreaterThanLight,
    faGreaterThanEqual as faGreaterThanEqualLight,
    faGripHorizontal as faGripHorizontalLight,
    faHandPaper as faHandPaperLight,
    faHandPointUp as faHandPointUpLight,
    faHandshake as faHandshakeLight,
    faHeartRate as faHeartRateLight,
    faHistory as faHistoryLight,
    faHome as faHomeLight,
    faInbox as faInboxLight,
    faIndustryAlt as faIndustryAltLight,
    faInfoCircle as faInfoCircleLight,
    faLessThan as faLessThanLight,
    faLessThanEqual as faLessThanEqualLight,
    faLink as faLinkLight,
    faLock as faLockLight,
    faLockOpen as faLockOpenLight,
    faWandMagicSparkles as faWandMagicSparklesLight,
    faMapMarkerAlt as faMapMarkerAltLight,
    faMapSigns as faMapSignsLight,
    faMask as faMaskLight,
    faMinusCircle as faMinusCircleLight,
    faMobileScreen as faMobileScreenLight,
    faMoon as faMoonLight,
    faNewspaper as faNewspaperLight,
    faNotEqual as faNotEqualLight,
    faPaperclip as faPaperclipLight,
    faPaste as faPasteLight,
    faPause as faPauseLight,
    faPauseCircle as faPauseCircleLight,
    faPhoneAlt as faPhoneAltLight,
    faPlay as faPlayLight,
    faPlayCircle as faPlayCircleLight,
    faPlus as faPlusLight,
    faPlusCircle as faPlusCircleLight,
    faPoundSign as faPoundSignLight,
    faPrint as faPrintLight,
    faQuestion as faQuestionLight,
    faQuestionCircle as faQuestionCircleLight,
    faRandom as faRandomLight,
    faReceipt as faReceiptLight,
    faRedo as faRedoLight,
    faRocket as faRocketLight,
    faSave as faSaveLight,
    faSearch as faSearchLight,
    faServer as faServerLight,
    faShieldAlt as faShieldAltLight,
    faShieldCheck as faShieldCheckLight,
    faSigma as faSigmaLight,
    faSignIn as faSignInLight,
    faSignOut as faSignOutLight,
    faSkull as faSkullLight,
    faSlidersHSquare as faSlidersHSquareLight,
    faSpinner as faSpinnerLight,
    faStar as faStarLight,
    faStethoscope as faStethoscopeLight,
    faStop as faStopLight,
    faStopCircle as faStopCircleLight,
    faStopwatch as faStopwatchLight,
    faStream as faStreamLight,
    faSun as faSunLight,
    faSync as faSyncLight,
    faTable as faTableLight,
    faTableLayout as faTableLayoutLight,
    faGaugeHigh as faGaugeHighLight,
    faTag as faTagLight,
    faTags as faTagsLight,
    faTh as faThLight,
    faThLarge as faThLargeLight,
    faThumbsDown as faThumbsDownLight,
    faThumbsUp as faThumbsUpLight,
    faThumbtack as faThumbtackLight,
    faTimes as faTimesLight,
    faTimesCircle as faTimesCircleLight,
    faTimesHexagon as faTimesHexagonLight,
    faToolbox as faToolboxLight,
    faTools as faToolsLight,
    faTrashAlt as faTrashAltLight,
    faUndo as faUndoLight,
    faUniversity as faUniversityLight,
    faUnlink as faUnlinkLight,
    faUpload as faUploadLight,
    faUsdCircle as faUsdCircleLight,
    faUser as faUserLight,
    faUserCheck as faUserCheckLight,
    faUserCircle as faUserCircleLight,
    faUserClock as faUserClockLight,
    faUserFriends as faUserFriendsLight,
    faUsers as faUsersLight,
    faWindow as faWindowLight,
    faWrench as faWrenchLight
} from '@fortawesome/pro-light-svg-icons';
import {
    faAddressCard,
    faAlignJustify,
    faAnalytics,
    faAngleDoubleDown,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faAngleDoubleUp,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowToBottom,
    faArrowToLeft,
    faArrowToRight,
    faArrowToTop,
    faArrowUp,
    faArrowsH,
    faArrowsV,
    faBalanceScale,
    faBalanceScaleLeft,
    faBalanceScaleRight,
    faBan,
    faBars,
    faBolt,
    faBook,
    faBookmark,
    faBooks,
    faBox,
    faBoxFull,
    faBracketsCurly,
    faBreadSlice,
    faBriefcase,
    faBrowser,
    faBuilding,
    faBullhorn,
    faBullseyeArrow,
    faCalculator,
    faCalendarDay,
    faCamera,
    faCaretLeft,
    faCaretRight,
    faChartArea,
    faChartColumn,
    faChartLine,
    faChartPie,
    faCheck,
    faCheckCircle,
    faChess,
    faChessKnightAlt,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faCircle,
    faClipboard,
    faClock,
    faCloudDownload,
    faCloudUpload,
    faCode,
    faCog,
    faCogs,
    faCommentDots,
    faCompressAlt,
    faCopy,
    faCrosshairs,
    faCube,
    faDatabase,
    faDesktop,
    faDollarSign,
    faDownload,
    faEdit,
    faEllipsisH,
    faEllipsisV,
    faEnvelope,
    faEquals,
    faEuroSign,
    faExchange,
    faExclamationCircle,
    faExclamationSquare,
    faExclamationTriangle,
    faExpandAlt,
    faExternalLink,
    faEye,
    faEyeSlash,
    faFile,
    faFileAlt,
    faFileArchive,
    faFileCertificate,
    faFileCsv,
    faFileExcel,
    faFileImage,
    faFilePdf,
    faFilePowerpoint,
    faFileWord,
    faFilter,
    faFlag,
    faFlask,
    faFolder,
    faFolderOpen,
    faFunction,
    faGift,
    faGlobe,
    faGlobeAmericas,
    faGraduationCap,
    faGreaterThan,
    faGreaterThanEqual,
    faGripHorizontal,
    faHandPaper,
    faHandPointUp,
    faHandshake,
    faHeartRate,
    faHistory,
    faHome,
    faInbox,
    faIndustryAlt,
    faInfoCircle,
    faLessThan,
    faLessThanEqual,
    faLink,
    faLock,
    faLockOpen,
    faWandMagicSparkles,
    faMapMarkerAlt,
    faMapSigns,
    faMask,
    faMinusCircle,
    faMobileScreen,
    faMoon,
    faNewspaper,
    faNotEqual,
    faPaperclip,
    faPaste,
    faPause,
    faPauseCircle,
    faPhoneAlt,
    faPlay,
    faPlayCircle,
    faPlus,
    faPlusCircle,
    faPoundSign,
    faPrint,
    faQuestion,
    faQuestionCircle,
    faRandom,
    faReceipt,
    faRedo,
    faRocket,
    faSave,
    faSearch,
    faServer,
    faShieldAlt,
    faShieldCheck,
    faSigma,
    faSignIn,
    faSignOut,
    faSkull,
    faSlidersHSquare,
    faSpinner,
    faStar,
    faStethoscope,
    faStop,
    faStopCircle,
    faStopwatch,
    faStream,
    faSun,
    faSync,
    faTable,
    faTableLayout,
    faGaugeHigh,
    faTag,
    faTags,
    faTh,
    faThLarge,
    faThumbsDown,
    faThumbsUp,
    faThumbtack,
    faTimes,
    faTimesCircle,
    faTimesHexagon,
    faToolbox,
    faTools,
    faTrashAlt,
    faUndo,
    faUniversity,
    faUnlink,
    faUpload,
    faUsdCircle,
    faUser,
    faUserCheck,
    faUserCircle,
    faUserClock,
    faUserFriends,
    faUsers,
    faWindow,
    faWrench
} from '@fortawesome/pro-regular-svg-icons';
import {
    faAddressCard as faAddressCardSolid,
    faAlignJustify as faAlignJustifySolid,
    faAnalytics as faAnalyticsSolid,
    faAngleDoubleDown as faAngleDoubleDownSolid,
    faAngleDoubleLeft as faAngleDoubleLeftSolid,
    faAngleDoubleRight as faAngleDoubleRightSolid,
    faAngleDoubleUp as faAngleDoubleUpSolid,
    faAngleDown as faAngleDownSolid,
    faAngleLeft as faAngleLeftSolid,
    faAngleRight as faAngleRightSolid,
    faAngleUp as faAngleUpSolid,
    faArrowDown as faArrowDownSolid,
    faArrowLeft as faArrowLeftSolid,
    faArrowRight as faArrowRightSolid,
    faArrowToBottom as faArrowToBottomSolid,
    faArrowToLeft as faArrowToLeftSolid,
    faArrowToRight as faArrowToRightSolid,
    faArrowToTop as faArrowToTopSolid,
    faArrowUp as faArrowUpSolid,
    faArrowsH as faArrowsHSolid,
    faArrowsV as faArrowsVSolid,
    faBalanceScale as faBalanceScaleSolid,
    faBalanceScaleLeft as faBalanceScaleLeftSolid,
    faBalanceScaleRight as faBalanceScaleRightSolid,
    faBan as faBanSolid,
    faBars as faBarsSolid,
    faBolt as faBoltSolid,
    faBook as faBookSolid,
    faBookmark as faBookmarkSolid,
    faBooks as faBooksSolid,
    faBox as faBoxSolid,
    faBoxFull as faBoxFullSolid,
    faBracketsCurly as faBracketsCurlySolid,
    faBreadSlice as faBreadSliceSolid,
    faBriefcase as faBriefcaseSolid,
    faBrowser as faBrowserSolid,
    faBuilding as faBuildingSolid,
    faBullhorn as faBullhornSolid,
    faBullseyeArrow as faBullseyeArrowSolid,
    faCalculator as faCalculatorSolid,
    faCalendarDay as faCalendarDaySolid,
    faCamera as faCameraSolid,
    faCaretLeft as faCaretLeftSolid,
    faCaretRight as faCaretRightSolid,
    faChartArea as faChartAreaSolid,
    faChartColumn as faChartColumnSolid,
    faChartLine as faChartLineSolid,
    faChartPie as faChartPieSolid,
    faCheck as faCheckSolid,
    faCheckCircle as faCheckCircleSolid,
    faChess as faChessSolid,
    faChessKnightAlt as faChessKnightAltSolid,
    faChevronDown as faChevronDownSolid,
    faChevronLeft as faChevronLeftSolid,
    faChevronRight as faChevronRightSolid,
    faChevronUp as faChevronUpSolid,
    faCircle as faCircleSolid,
    faClipboard as faClipboardSolid,
    faClock as faClockSolid,
    faCloudDownload as faCloudDownloadSolid,
    faCloudUpload as faCloudUploadSolid,
    faCode as faCodeSolid,
    faCog as faCogSolid,
    faCogs as faCogsSolid,
    faCommentDots as faCommentDotsSolid,
    faCompressAlt as faCompressAltSolid,
    faCopy as faCopySolid,
    faCrosshairs as faCrosshairsSolid,
    faCube as faCubeSolid,
    faDatabase as faDatabaseSolid,
    faDesktop as faDesktopSolid,
    faDollarSign as faDollarSignSolid,
    faDownload as faDownloadSolid,
    faEdit as faEditSolid,
    faEllipsisH as faEllipsisHSolid,
    faEllipsisV as faEllipsisVSolid,
    faEnvelope as faEnvelopeSolid,
    faEquals as faEqualsSolid,
    faEuroSign as faEuroSignSolid,
    faExchange as faExchangeSolid,
    faExclamationCircle as faExclamationCircleSolid,
    faExclamationSquare as faExclamationSquareSolid,
    faExclamationTriangle as faExclamationTriangleSolid,
    faExpandAlt as faExpandAltSolid,
    faExternalLink as faExternalLinkSolid,
    faEye as faEyeSolid,
    faEyeSlash as faEyeSlashSolid,
    faFile as faFileSolid,
    faFileAlt as faFileAltSolid,
    faFileArchive as faFileArchiveSolid,
    faFileCertificate as faFileCertificateSolid,
    faFileCsv as faFileCsvSolid,
    faFileExcel as faFileExcelSolid,
    faFileImage as faFileImageSolid,
    faFilePdf as faFilePdfSolid,
    faFilePowerpoint as faFilePowerpointSolid,
    faFileWord as faFileWordSolid,
    faFilter as faFilterSolid,
    faFlag as faFlagSolid,
    faFlask as faFlaskSolid,
    faFolder as faFolderSolid,
    faFolderOpen as faFolderOpenSolid,
    faFunction as faFunctionSolid,
    faGift as faGiftSolid,
    faGlobe as faGlobeSolid,
    faGlobeAmericas as faGlobeAmericasSolid,
    faGraduationCap as faGraduationCapSolid,
    faGreaterThan as faGreaterThanSolid,
    faGreaterThanEqual as faGreaterThanEqualSolid,
    faGripHorizontal as faGripHorizontalSolid,
    faHandPaper as faHandPaperSolid,
    faHandPointUp as faHandPointUpSolid,
    faHandshake as faHandshakeSolid,
    faHeartRate as faHeartRateSolid,
    faHistory as faHistorySolid,
    faHome as faHomeSolid,
    faInbox as faInboxSolid,
    faIndustryAlt as faIndustryAltSolid,
    faInfoCircle as faInfoCircleSolid,
    faLessThan as faLessThanSolid,
    faLessThanEqual as faLessThanEqualSolid,
    faLink as faLinkSolid,
    faLock as faLockSolid,
    faLockOpen as faLockOpenSolid,
    faWandMagicSparkles as faWandMagicSparklesSolid,
    faMapMarkerAlt as faMapMarkerAltSolid,
    faMapSigns as faMapSignsSolid,
    faMask as faMaskSolid,
    faMinusCircle as faMinusCircleSolid,
    faMobileScreen as faMobileScreenSolid,
    faMoon as faMoonSolid,
    faNewspaper as faNewspaperSolid,
    faNotEqual as faNotEqualSolid,
    faPaperclip as faPaperclipSolid,
    faPaste as faPasteSolid,
    faPause as faPauseSolid,
    faPauseCircle as faPauseCircleSolid,
    faPhoneAlt as faPhoneAltSolid,
    faPlay as faPlaySolid,
    faPlayCircle as faPlayCircleSolid,
    faPlus as faPlusSolid,
    faPlusCircle as faPlusCircleSolid,
    faPoundSign as faPoundSignSolid,
    faPrint as faPrintSolid,
    faQuestion as faQuestionSolid,
    faQuestionCircle as faQuestionCircleSolid,
    faRandom as faRandomSolid,
    faReceipt as faReceiptSolid,
    faRedo as faRedoSolid,
    faRocket as faRocketSolid,
    faSave as faSaveSolid,
    faSearch as faSearchSolid,
    faServer as faServerSolid,
    faShieldAlt as faShieldAltSolid,
    faShieldCheck as faShieldCheckSolid,
    faSigma as faSigmaSolid,
    faSignIn as faSignInSolid,
    faSignOut as faSignOutSolid,
    faSkull as faSkullSolid,
    faSlidersHSquare as faSlidersHSquareSolid,
    faSpinner as faSpinnerSolid,
    faStar as faStarSolid,
    faStethoscope as faStethoscopeSolid,
    faStop as faStopSolid,
    faStopCircle as faStopCircleSolid,
    faStopwatch as faStopwatchSolid,
    faStream as faStreamSolid,
    faSun as faSunSolid,
    faSync as faSyncSolid,
    faTable as faTableSolid,
    faTableLayout as faTableLayoutSolid,
    faGaugeHigh as faGaugeHighSolid,
    faTag as faTagSolid,
    faTags as faTagsSolid,
    faTh as faThSolid,
    faThLarge as faThLargeSolid,
    faThumbsDown as faThumbsDownSolid,
    faThumbsUp as faThumbsUpSolid,
    faThumbtack as faThumbtackSolid,
    faTimes as faTimesSolid,
    faTimesCircle as faTimesCircleSolid,
    faTimesHexagon as faTimesHexagonSolid,
    faToolbox as faToolboxSolid,
    faTools as faToolsSolid,
    faTrashAlt as faTrashAltSolid,
    faUndo as faUndoSolid,
    faUniversity as faUniversitySolid,
    faUnlink as faUnlinkSolid,
    faUpload as faUploadSolid,
    faUsdCircle as faUsdCircleSolid,
    faUser as faUserSolid,
    faUserCheck as faUserCheckSolid,
    faUserCircle as faUserCircleSolid,
    faUserClock as faUserClockSolid,
    faUserFriends as faUserFriendsSolid,
    faUsers as faUsersSolid,
    faWindow as faWindowSolid,
    faWrench as faWrenchSolid
} from '@fortawesome/pro-solid-svg-icons';

import {
    faAddressCard as faAddressCardThin,
    faAlignJustify as faAlignJustifyThin,
    faAnalytics as faAnalyticsThin,
    faAngleDoubleDown as faAngleDoubleDownThin,
    faAngleDoubleLeft as faAngleDoubleLeftThin,
    faAngleDoubleRight as faAngleDoubleRightThin,
    faAngleDoubleUp as faAngleDoubleUpThin,
    faAngleDown as faAngleDownThin,
    faAngleLeft as faAngleLeftThin,
    faAngleRight as faAngleRightThin,
    faAngleUp as faAngleUpThin,
    faArrowDown as faArrowDownThin,
    faArrowLeft as faArrowLeftThin,
    faArrowRight as faArrowRightThin,
    faArrowToBottom as faArrowToBottomThin,
    faArrowToLeft as faArrowToLeftThin,
    faArrowToRight as faArrowToRightThin,
    faArrowToTop as faArrowToTopThin,
    faArrowUp as faArrowUpThin,
    faArrowsH as faArrowsHThin,
    faArrowsV as faArrowsVThin,
    faBalanceScale as faBalanceScaleThin,
    faBalanceScaleLeft as faBalanceScaleLeftThin,
    faBalanceScaleRight as faBalanceScaleRightThin,
    faBan as faBanThin,
    faBars as faBarsThin,
    faBolt as faBoltThin,
    faBook as faBookThin,
    faBookmark as faBookmarkThin,
    faBooks as faBooksThin,
    faBox as faBoxThin,
    faBoxFull as faBoxFullThin,
    faBracketsCurly as faBracketsCurlyThin,
    faBreadSlice as faBreadSliceThin,
    faBriefcase as faBriefcaseThin,
    faBrowser as faBrowserThin,
    faBuilding as faBuildingThin,
    faBullhorn as faBullhornThin,
    faBullseyeArrow as faBullseyeArrowThin,
    faCalculator as faCalculatorThin,
    faCalendarDay as faCalendarDayThin,
    faCamera as faCameraThin,
    faCaretLeft as faCaretLeftThin,
    faCaretRight as faCaretRightThin,
    faChartArea as faChartAreaThin,
    faChartColumn as faChartColumnThin,
    faChartLine as faChartLineThin,
    faChartPie as faChartPieThin,
    faCheck as faCheckThin,
    faCheckCircle as faCheckCircleThin,
    faChess as faChessThin,
    faChessKnightAlt as faChessKnightAltThin,
    faChevronDown as faChevronDownThin,
    faChevronLeft as faChevronLeftThin,
    faChevronRight as faChevronRightThin,
    faChevronUp as faChevronUpThin,
    faCircle as faCircleThin,
    faClipboard as faClipboardThin,
    faClock as faClockThin,
    faCloudDownload as faCloudDownloadThin,
    faCloudUpload as faCloudUploadThin,
    faCode as faCodeThin,
    faCog as faCogThin,
    faCogs as faCogsThin,
    faCommentDots as faCommentDotsThin,
    faCompressAlt as faCompressAltThin,
    faCopy as faCopyThin,
    faCrosshairs as faCrosshairsThin,
    faCube as faCubeThin,
    faDatabase as faDatabaseThin,
    faDesktop as faDesktopThin,
    faDollarSign as faDollarSignThin,
    faDownload as faDownloadThin,
    faEdit as faEditThin,
    faEllipsisH as faEllipsisHThin,
    faEllipsisV as faEllipsisVThin,
    faEnvelope as faEnvelopeThin,
    faEquals as faEqualsThin,
    faEuroSign as faEuroSignThin,
    faExchange as faExchangeThin,
    faExclamationCircle as faExclamationCircleThin,
    faExclamationSquare as faExclamationSquareThin,
    faExclamationTriangle as faExclamationTriangleThin,
    faExpandAlt as faExpandAltThin,
    faExternalLink as faExternalLinkThin,
    faEye as faEyeThin,
    faEyeSlash as faEyeSlashThin,
    faFile as faFileThin,
    faFileAlt as faFileAltThin,
    faFileArchive as faFileArchiveThin,
    faFileCertificate as faFileCertificateThin,
    faFileCsv as faFileCsvThin,
    faFileExcel as faFileExcelThin,
    faFileImage as faFileImageThin,
    faFilePdf as faFilePdfThin,
    faFilePowerpoint as faFilePowerpointThin,
    faFileWord as faFileWordThin,
    faFilter as faFilterThin,
    faFlag as faFlagThin,
    faFlask as faFlaskThin,
    faFolder as faFolderThin,
    faFolderOpen as faFolderOpenThin,
    faFunction as faFunctionThin,
    faGift as faGiftThin,
    faGlobe as faGlobeThin,
    faGlobeAmericas as faGlobeAmericasThin,
    faGraduationCap as faGraduationCapThin,
    faGreaterThan as faGreaterThanThin,
    faGreaterThanEqual as faGreaterThanEqualThin,
    faGripHorizontal as faGripHorizontalThin,
    faHandPaper as faHandPaperThin,
    faHandPointUp as faHandPointUpThin,
    faHandshake as faHandshakeThin,
    faHeartRate as faHeartRateThin,
    faHistory as faHistoryThin,
    faHome as faHomeThin,
    faInbox as faInboxThin,
    faIndustryAlt as faIndustryAltThin,
    faInfoCircle as faInfoCircleThin,
    faLessThan as faLessThanThin,
    faLessThanEqual as faLessThanEqualThin,
    faLink as faLinkThin,
    faLock as faLockThin,
    faLockOpen as faLockOpenThin,
    faWandMagicSparkles as faWandMagicSparklesThin,
    faMapMarkerAlt as faMapMarkerAltThin,
    faMapSigns as faMapSignsThin,
    faMask as faMaskThin,
    faMinusCircle as faMinusCircleThin,
    faMobileScreen as faMobileScreenThin,
    faMoon as faMoonThin,
    faNewspaper as faNewspaperThin,
    faNotEqual as faNotEqualThin,
    faPaperclip as faPaperclipThin,
    faPaste as faPasteThin,
    faPause as faPauseThin,
    faPauseCircle as faPauseCircleThin,
    faPhoneAlt as faPhoneAltThin,
    faPlay as faPlayThin,
    faPlayCircle as faPlayCircleThin,
    faPlus as faPlusThin,
    faPlusCircle as faPlusCircleThin,
    faPoundSign as faPoundSignThin,
    faPrint as faPrintThin,
    faQuestion as faQuestionThin,
    faQuestionCircle as faQuestionCircleThin,
    faRandom as faRandomThin,
    faReceipt as faReceiptThin,
    faRedo as faRedoThin,
    faRocket as faRocketThin,
    faSave as faSaveThin,
    faSearch as faSearchThin,
    faServer as faServerThin,
    faShieldAlt as faShieldAltThin,
    faShieldCheck as faShieldCheckThin,
    faSigma as faSigmaThin,
    faSignIn as faSignInThin,
    faSignOut as faSignOutThin,
    faSkull as faSkullThin,
    faSlidersHSquare as faSlidersHSquareThin,
    faSpinner as faSpinnerThin,
    faStar as faStarThin,
    faStethoscope as faStethoscopeThin,
    faStop as faStopThin,
    faStopCircle as faStopCircleThin,
    faStopwatch as faStopwatchThin,
    faStream as faStreamThin,
    faSun as faSunThin,
    faSync as faSyncThin,
    faTable as faTableThin,
    faTableLayout as faTableLayoutThin,
    faGaugeHigh as faGaugeHighThin,
    faTag as faTagThin,
    faTags as faTagsThin,
    faTh as faThThin,
    faThLarge as faThLargeThin,
    faThumbsDown as faThumbsDownThin,
    faThumbsUp as faThumbsUpThin,
    faThumbtack as faThumbtackThin,
    faTimes as faTimesThin,
    faTimesCircle as faTimesCircleThin,
    faTimesHexagon as faTimesHexagonThin,
    faToolbox as faToolboxThin,
    faTools as faToolsThin,
    faTrashAlt as faTrashAltThin,
    faUndo as faUndoThin,
    faUniversity as faUniversityThin,
    faUnlink as faUnlinkThin,
    faUpload as faUploadThin,
    faUsdCircle as faUsdCircleThin,
    faUser as faUserThin,
    faUserCheck as faUserCheckThin,
    faUserCircle as faUserCircleThin,
    faUserClock as faUserClockThin,
    faUserFriends as faUserFriendsThin,
    faUsers as faUsersThin,
    faWindow as faWindowThin,
    faWrench as faWrenchThin
} from '@fortawesome/pro-thin-svg-icons';

import {
    faAddressCard as faAddressCardDuoTone,
    faAlignJustify as faAlignJustifyDuoTone,
    faAnalytics as faAnalyticsDuoTone,
    faAngleDoubleDown as faAngleDoubleDownDuoTone,
    faAngleDoubleLeft as faAngleDoubleLeftDuoTone,
    faAngleDoubleRight as faAngleDoubleRightDuoTone,
    faAngleDoubleUp as faAngleDoubleUpDuoTone,
    faAngleDown as faAngleDownDuoTone,
    faAngleLeft as faAngleLeftDuoTone,
    faAngleRight as faAngleRightDuoTone,
    faAngleUp as faAngleUpDuoTone,
    faArrowDown as faArrowDownDuoTone,
    faArrowLeft as faArrowLeftDuoTone,
    faArrowRight as faArrowRightDuoTone,
    faArrowToBottom as faArrowToBottomDuoTone,
    faArrowToLeft as faArrowToLeftDuoTone,
    faArrowToRight as faArrowToRightDuoTone,
    faArrowToTop as faArrowToTopDuoTone,
    faArrowUp as faArrowUpDuoTone,
    faArrowsH as faArrowsHDuoTone,
    faArrowsV as faArrowsVDuoTone,
    faBalanceScale as faBalanceScaleDuoTone,
    faBalanceScaleLeft as faBalanceScaleLeftDuoTone,
    faBalanceScaleRight as faBalanceScaleRightDuoTone,
    faBan as faBanDuoTone,
    faBars as faBarsDuoTone,
    faBolt as faBoltDuoTone,
    faBook as faBookDuoTone,
    faBookmark as faBookmarkDuoTone,
    faBooks as faBooksDuoTone,
    faBox as faBoxDuoTone,
    faBoxFull as faBoxFullDuoTone,
    faBracketsCurly as faBracketsCurlyDuoTone,
    faBreadSlice as faBreadSliceDuoTone,
    faBriefcase as faBriefcaseDuoTone,
    faBrowser as faBrowserDuoTone,
    faBuilding as faBuildingDuoTone,
    faBullhorn as faBullhornDuoTone,
    faBullseyeArrow as faBullseyeArrowDuoTone,
    faCalculator as faCalculatorDuoTone,
    faCalendarDay as faCalendarDayDuoTone,
    faCamera as faCameraDuoTone,
    faCaretLeft as faCaretLeftDuoTone,
    faCaretRight as faCaretRightDuoTone,
    faChartArea as faChartAreaDuoTone,
    faChartColumn as faChartColumnDuoTone,
    faChartLine as faChartLineDuoTone,
    faChartPie as faChartPieDuoTone,
    faCheck as faCheckDuoTone,
    faCheckCircle as faCheckCircleDuoTone,
    faChess as faChessDuoTone,
    faChessKnightAlt as faChessKnightAltDuoTone,
    faChevronDown as faChevronDownDuoTone,
    faChevronLeft as faChevronLeftDuoTone,
    faChevronRight as faChevronRightDuoTone,
    faChevronUp as faChevronUpDuoTone,
    faCircle as faCircleDuoTone,
    faClipboard as faClipboardDuoTone,
    faClock as faClockDuoTone,
    faCloudDownload as faCloudDownloadDuoTone,
    faCloudUpload as faCloudUploadDuoTone,
    faCode as faCodeDuoTone,
    faCog as faCogDuoTone,
    faCogs as faCogsDuoTone,
    faCommentDots as faCommentDotsDuoTone,
    faCompressAlt as faCompressAltDuoTone,
    faCopy as faCopyDuoTone,
    faCrosshairs as faCrosshairsDuoTone,
    faCube as faCubeDuoTone,
    faDatabase as faDatabaseDuoTone,
    faDesktop as faDesktopDuoTone,
    faDollarSign as faDollarSignDuoTone,
    faDownload as faDownloadDuoTone,
    faEdit as faEditDuoTone,
    faEllipsisH as faEllipsisHDuoTone,
    faEllipsisV as faEllipsisVDuoTone,
    faEnvelope as faEnvelopeDuoTone,
    faEquals as faEqualsDuoTone,
    faEuroSign as faEuroSignDuoTone,
    faExchange as faExchangeDuoTone,
    faExclamationCircle as faExclamationCircleDuoTone,
    faExclamationSquare as faExclamationSquareDuoTone,
    faExclamationTriangle as faExclamationTriangleDuoTone,
    faExpandAlt as faExpandAltDuoTone,
    faExternalLink as faExternalLinkDuoTone,
    faEye as faEyeDuoTone,
    faEyeSlash as faEyeSlashDuoTone,
    faFile as faFileDuoTone,
    faFileAlt as faFileAltDuoTone,
    faFileArchive as faFileArchiveDuoTone,
    faFileCertificate as faFileCertificateDuoTone,
    faFileCsv as faFileCsvDuoTone,
    faFileExcel as faFileExcelDuoTone,
    faFileImage as faFileImageDuoTone,
    faFilePdf as faFilePdfDuoTone,
    faFilePowerpoint as faFilePowerpointDuoTone,
    faFileWord as faFileWordDuoTone,
    faFilter as faFilterDuoTone,
    faFlag as faFlagDuoTone,
    faFlask as faFlaskDuoTone,
    faFolder as faFolderDuoTone,
    faFolderOpen as faFolderOpenDuoTone,
    faFunction as faFunctionDuoTone,
    faGift as faGiftDuoTone,
    faGlobe as faGlobeDuoTone,
    faGlobeAmericas as faGlobeAmericasDuoTone,
    faGraduationCap as faGraduationCapDuoTone,
    faGreaterThan as faGreaterThanDuoTone,
    faGreaterThanEqual as faGreaterThanEqualDuoTone,
    faGripHorizontal as faGripHorizontalDuoTone,
    faHandPaper as faHandPaperDuoTone,
    faHandPointUp as faHandPointUpDuoTone,
    faHandshake as faHandshakeDuoTone,
    faHeartRate as faHeartRateDuoTone,
    faHistory as faHistoryDuoTone,
    faHome as faHomeDuoTone,
    faInbox as faInboxDuoTone,
    faIndustryAlt as faIndustryAltDuoTone,
    faInfoCircle as faInfoCircleDuoTone,
    faLessThan as faLessThanDuoTone,
    faLessThanEqual as faLessThanEqualDuoTone,
    faLink as faLinkDuoTone,
    faLock as faLockDuoTone,
    faLockOpen as faLockOpenDuoTone,
    faWandMagicSparkles as faWandMagicSparklesDuoTone,
    faMapMarkerAlt as faMapMarkerAltDuoTone,
    faMapSigns as faMapSignsDuoTone,
    faMask as faMaskDuoTone,
    faMinusCircle as faMinusCircleDuoTone,
    faMobileScreen as faMobileScreenDuoTone,
    faMoon as faMoonDuoTone,
    faNewspaper as faNewspaperDuoTone,
    faNotEqual as faNotEqualDuoTone,
    faPaperclip as faPaperclipDuoTone,
    faPaste as faPasteDuoTone,
    faPause as faPauseDuoTone,
    faPauseCircle as faPauseCircleDuoTone,
    faPhoneAlt as faPhoneAltDuoTone,
    faPlay as faPlayDuoTone,
    faPlayCircle as faPlayCircleDuoTone,
    faPlus as faPlusDuoTone,
    faPlusCircle as faPlusCircleDuoTone,
    faPoundSign as faPoundSignDuoTone,
    faPrint as faPrintDuoTone,
    faQuestion as faQuestionDuoTone,
    faQuestionCircle as faQuestionCircleDuoTone,
    faRandom as faRandomDuoTone,
    faReceipt as faReceiptDuoTone,
    faRedo as faRedoDuoTone,
    faRocket as faRocketDuoTone,
    faSave as faSaveDuoTone,
    faSearch as faSearchDuoTone,
    faServer as faServerDuoTone,
    faShieldAlt as faShieldAltDuoTone,
    faShieldCheck as faShieldCheckDuoTone,
    faSigma as faSigmaDuoTone,
    faSignIn as faSignInDuoTone,
    faSignOut as faSignOutDuoTone,
    faSkull as faSkullDuoTone,
    faSlidersHSquare as faSlidersHSquareDuoTone,
    faSpinner as faSpinnerDuoTone,
    faStar as faStarDuoTone,
    faStethoscope as faStethoscopeDuoTone,
    faStop as faStopDuoTone,
    faStopCircle as faStopCircleDuoTone,
    faStopwatch as faStopwatchDuoTone,
    faStream as faStreamDuoTone,
    faSun as faSunDuoTone,
    faSync as faSyncDuoTone,
    faTable as faTableDuoTone,
    faTableLayout as faTableLayoutDuoTone,
    faGaugeHigh as faGaugeHighDuoTone,
    faTag as faTagDuoTone,
    faTags as faTagsDuoTone,
    faTh as faThDuoTone,
    faThLarge as faThLargeDuoTone,
    faThumbsDown as faThumbsDownDuoTone,
    faThumbsUp as faThumbsUpDuoTone,
    faThumbtack as faThumbtackDuoTone,
    faTimes as faTimesDuoTone,
    faTimesCircle as faTimesCircleDuoTone,
    faTimesHexagon as faTimesHexagonDuoTone,
    faToolbox as faToolboxDuoTone,
    faTools as faToolsDuoTone,
    faTrashAlt as faTrashAltDuoTone,
    faUndo as faUndoDuoTone,
    faUniversity as faUniversityDuoTone,
    faUnlink as faUnlinkDuoTone,
    faUpload as faUploadDuoTone,
    faUsdCircle as faUsdCircleDuoTone,
    faUser as faUserDuoTone,
    faUserCheck as faUserCheckDuoTone,
    faUserCircle as faUserCircleDuoTone,
    faUserClock as faUserClockDuoTone,
    faUserFriends as faUserFriendsDuoTone,
    faUsers as faUsersDuoTone,
    faWindow as faWindowDuoTone,
    faWrench as faWrenchDuoTone
} from '@fortawesome/pro-duotone-svg-icons';

// Register imported icons with the FA library to ensure they are available by name.
library.add(
    faAddressCard, faAddressCardLight, faAddressCardSolid, faAddressCardThin, faAddressCardDuoTone,
    faAddressCard, faAddressCardLight, faAddressCardSolid, faAddressCardThin, faAddressCardDuoTone,
    faAlignJustify, faAlignJustifyLight, faAlignJustifySolid, faAlignJustifyThin, faAlignJustifyDuoTone,
    faAnalytics, faAnalyticsLight, faAnalyticsSolid, faAnalyticsThin, faAnalyticsDuoTone,
    faAngleDoubleDown, faAngleDoubleDownLight, faAngleDoubleDownSolid, faAngleDoubleDownThin, faAngleDoubleDownDuoTone,
    faAngleDoubleLeft, faAngleDoubleLeftLight, faAngleDoubleLeftSolid, faAngleDoubleLeftThin, faAngleDoubleLeftDuoTone,
    faAngleDoubleRight, faAngleDoubleRightLight, faAngleDoubleRightSolid, faAngleDoubleRightThin, faAngleDoubleRightDuoTone,
    faAngleDoubleUp, faAngleDoubleUpLight, faAngleDoubleUpSolid, faAngleDoubleUpThin, faAngleDoubleUpDuoTone,
    faAngleDown, faAngleDownLight, faAngleDownSolid, faAngleDownThin, faAngleDownDuoTone,
    faAngleLeft, faAngleLeftLight, faAngleLeftSolid, faAngleLeftThin, faAngleLeftDuoTone,
    faAngleRight, faAngleRightLight, faAngleRightSolid, faAngleRightThin, faAngleRightDuoTone,
    faAngleUp, faAngleUpLight, faAngleUpSolid, faAngleUpThin, faAngleUpDuoTone,
    faArrowDown, faArrowDownLight, faArrowDownSolid, faArrowDownThin, faArrowDownDuoTone,
    faArrowLeft, faArrowLeftLight, faArrowLeftSolid, faArrowLeftThin, faArrowLeftDuoTone,
    faArrowRight, faArrowRightLight, faArrowRightSolid, faArrowRightThin, faArrowRightDuoTone,
    faArrowsH, faArrowsHLight, faArrowsHSolid, faArrowsHThin, faArrowsHDuoTone,
    faArrowsV, faArrowsVLight, faArrowsVSolid, faArrowsVThin, faArrowsVDuoTone,
    faArrowToBottom, faArrowToBottomLight, faArrowToBottomSolid, faArrowToBottomThin, faArrowToBottomDuoTone,
    faArrowToLeft, faArrowToLeftLight, faArrowToLeftSolid, faArrowToLeftThin, faArrowToLeftDuoTone,
    faArrowToRight, faArrowToRightLight, faArrowToRightSolid, faArrowToRightThin, faArrowToRightDuoTone,
    faArrowToTop, faArrowToTopLight, faArrowToTopSolid, faArrowToTopThin, faArrowToTopDuoTone,
    faArrowUp, faArrowUpLight, faArrowUpSolid, faArrowUpThin, faArrowUpDuoTone,
    faBalanceScale, faBalanceScaleLight, faBalanceScaleSolid, faBalanceScaleThin, faBalanceScaleDuoTone,
    faBalanceScaleLeft, faBalanceScaleLeftLight, faBalanceScaleLeftSolid, faBalanceScaleLeftThin, faBalanceScaleLeftDuoTone,
    faBalanceScaleRight, faBalanceScaleRightLight, faBalanceScaleRightSolid, faBalanceScaleRightThin, faBalanceScaleRightDuoTone,
    faBan, faBanLight, faBanSolid, faBanThin, faBanDuoTone,
    faBars, faBarsLight, faBarsSolid, faBarsThin, faBarsDuoTone,
    faBolt, faBoltLight, faBoltSolid, faBoltThin, faBoltDuoTone,
    faBook, faBookLight, faBookSolid, faBookThin, faBookDuoTone,
    faBookmark, faBookmarkLight, faBookmarkSolid, faBookmarkThin, faBookmarkDuoTone,
    faBooks, faBooksLight, faBooksSolid, faBooksThin, faBooksDuoTone,
    faBox, faBoxLight, faBoxSolid, faBoxThin, faBoxDuoTone,
    faBoxFull, faBoxFullLight, faBoxFullSolid, faBoxFullThin, faBoxFullDuoTone,
    faBracketsCurly, faBracketsCurlyLight, faBracketsCurlySolid, faBracketsCurlyThin, faBracketsCurlyDuoTone,
    faBreadSlice, faBreadSliceLight, faBreadSliceSolid, faBreadSliceThin, faBreadSliceDuoTone,
    faBriefcase, faBriefcaseLight, faBriefcaseSolid, faBriefcaseThin, faBriefcaseDuoTone,
    faBrowser, faBrowserLight, faBrowserSolid, faBrowserThin, faBrowserDuoTone,
    faBuilding, faBuildingLight, faBuildingSolid, faBuildingThin, faBuildingDuoTone,
    faBullhorn, faBullhornLight, faBullhornSolid, faBullhornThin, faBullhornDuoTone,
    faBullseyeArrow, faBullseyeArrowLight, faBullseyeArrowSolid, faBullseyeArrowThin, faBullseyeArrowDuoTone,
    faCalculator, faCalculatorLight, faCalculatorSolid, faCalculatorThin, faCalculatorDuoTone,
    faCalendarDay, faCalendarDayLight, faCalendarDaySolid, faCalendarDayThin, faCalendarDayDuoTone,
    faCamera, faCameraLight, faCameraSolid, faCameraThin, faCameraDuoTone,
    faCaretLeft, faCaretLeftLight, faCaretLeftSolid, faCaretLeftThin, faCaretLeftDuoTone,
    faCaretRight, faCaretRightLight, faCaretRightSolid, faCaretRightThin, faCaretRightDuoTone,
    faChartArea, faChartAreaLight, faChartAreaSolid, faChartAreaThin, faChartAreaDuoTone,
    faChartColumn, faChartColumnLight, faChartColumnSolid, faChartColumnThin, faChartColumnDuoTone,
    faChartLine, faChartLineLight, faChartLineSolid, faChartLineThin, faChartLineDuoTone,
    faChartPie, faChartPieLight, faChartPieSolid, faChartPieThin, faChartPieDuoTone,
    faCheck, faCheckLight, faCheckSolid, faCheckThin, faCheckDuoTone,
    faCheckCircle, faCheckCircleLight, faCheckCircleSolid, faCheckCircleThin, faCheckCircleDuoTone,
    faChess, faChessLight, faChessSolid, faChessThin, faChessDuoTone,
    faChessKnightAlt, faChessKnightAltLight, faChessKnightAltSolid, faChessKnightAltThin, faChessKnightAltDuoTone,
    faChevronDown, faChevronDownLight, faChevronDownSolid, faChevronDownThin, faChevronDownDuoTone,
    faChevronLeft, faChevronLeftLight, faChevronLeftSolid, faChevronLeftThin, faChevronLeftDuoTone,
    faChevronRight, faChevronRightLight, faChevronRightSolid, faChevronRightThin, faChevronRightDuoTone,
    faChevronUp, faChevronUpLight, faChevronUpSolid, faChevronUpThin, faChevronUpDuoTone,
    faCircle, faCircleLight, faCircleSolid, faCircleThin, faCircleDuoTone,
    faClipboard, faClipboardLight, faClipboardSolid, faClipboardThin, faClipboardDuoTone,
    faClock, faClockLight, faClockSolid, faClockThin, faClockDuoTone,
    faCloudDownload, faCloudDownloadLight, faCloudDownloadSolid, faCloudDownloadThin, faCloudDownloadDuoTone,
    faCloudUpload, faCloudUploadLight, faCloudUploadSolid, faCloudUploadThin, faCloudUploadDuoTone,
    faCode, faCodeLight, faCodeSolid, faCodeThin, faCodeDuoTone,
    faCog, faCogLight, faCogSolid, faCogThin, faCogDuoTone,
    faCogs, faCogsLight, faCogsSolid, faCogsThin, faCogsDuoTone,
    faCommentDots, faCommentDotsLight, faCommentDotsSolid, faCommentDotsThin, faCommentDotsDuoTone,
    faCompressAlt, faCompressAltLight, faCompressAltSolid, faCompressAltThin, faCompressAltDuoTone,
    faCopy, faCopyLight, faCopySolid, faCopyThin, faCopyDuoTone,
    faCrosshairs, faCrosshairsLight, faCrosshairsSolid, faCrosshairsThin, faCrosshairsDuoTone,
    faCube, faCubeLight, faCubeSolid, faCubeThin, faCubeDuoTone,
    faDatabase, faDatabaseLight, faDatabaseSolid, faDatabaseThin, faDatabaseDuoTone,
    faDesktop, faDesktopLight, faDesktopSolid, faDesktopThin, faDesktopDuoTone,
    faDollarSign, faDollarSignLight, faDollarSignSolid, faDollarSignThin, faDollarSignDuoTone,
    faDownload, faDownloadLight, faDownloadSolid, faDownloadThin, faDownloadDuoTone,
    faEdit, faEditLight, faEditSolid, faEditThin, faEditDuoTone,
    faEllipsisH, faEllipsisHLight, faEllipsisHSolid, faEllipsisHThin, faEllipsisHDuoTone,
    faEllipsisV, faEllipsisVLight, faEllipsisVSolid, faEllipsisVThin, faEllipsisVDuoTone,
    faEnvelope, faEnvelopeLight, faEnvelopeSolid, faEnvelopeThin, faEnvelopeDuoTone,
    faEquals, faEqualsLight, faEqualsSolid, faEqualsThin, faEqualsDuoTone,
    faEuroSign, faEuroSignLight, faEuroSignSolid, faEuroSignThin, faEuroSignDuoTone,
    faExchange, faExchangeLight, faExchangeSolid, faExchangeThin, faExchangeDuoTone,
    faExclamationCircle, faExclamationCircleLight, faExclamationCircleSolid, faExclamationCircleThin, faExclamationCircleDuoTone,
    faExclamationSquare, faExclamationSquareLight, faExclamationSquareSolid, faExclamationSquareThin, faExclamationSquareDuoTone,
    faExclamationTriangle, faExclamationTriangleLight, faExclamationTriangleSolid, faExclamationTriangleThin, faExclamationTriangleDuoTone,
    faExpandAlt, faExpandAltLight, faExpandAltSolid, faExpandAltThin, faExpandAltDuoTone,
    faExternalLink, faExternalLinkLight, faExternalLinkSolid, faExternalLinkThin, faExternalLinkDuoTone,
    faEye, faEyeLight, faEyeSolid, faEyeThin, faEyeDuoTone,
    faEyeSlash, faEyeSlashLight, faEyeSlashSolid, faEyeSlashThin, faEyeSlashDuoTone,
    faFile, faFileLight, faFileSolid, faFileThin, faFileDuoTone,
    faFileAlt, faFileAltLight, faFileAltSolid, faFileAltThin, faFileAltDuoTone,
    faFileArchive, faFileArchiveLight, faFileArchiveSolid, faFileArchiveThin, faFileArchiveDuoTone,
    faFileCertificate, faFileCertificateLight, faFileCertificateSolid, faFileCertificateThin, faFileCertificateDuoTone,
    faFileCsv, faFileCsvLight, faFileCsvSolid, faFileCsvThin, faFileCsvDuoTone,
    faFileExcel, faFileExcelLight, faFileExcelSolid, faFileExcelThin, faFileExcelDuoTone,
    faFileImage, faFileImageLight, faFileImageSolid, faFileImageThin, faFileImageDuoTone,
    faFilePdf, faFilePdfLight, faFilePdfSolid, faFilePdfThin, faFilePdfDuoTone,
    faFilePowerpoint, faFilePowerpointLight, faFilePowerpointSolid, faFilePowerpointThin, faFilePowerpointDuoTone,
    faFileWord, faFileWordLight, faFileWordSolid, faFileWordThin, faFileWordDuoTone,
    faFilter, faFilterLight, faFilterSolid, faFilterThin, faFilterDuoTone,
    faFlag, faFlagLight, faFlagSolid, faFlagThin, faFlagDuoTone,
    faFlask, faFlaskLight, faFlaskSolid, faFlaskThin, faFlaskDuoTone,
    faFolder, faFolderLight, faFolderSolid, faFolderThin, faFolderDuoTone,
    faFolderOpen, faFolderOpenLight, faFolderOpenSolid, faFolderOpenThin, faFolderOpenDuoTone,
    faFunction, faFunctionLight, faFunctionSolid, faFunctionThin, faFunctionDuoTone,
    faGift, faGiftLight, faGiftSolid, faGiftThin, faGiftDuoTone,
    faGlobe, faGlobeLight, faGlobeSolid, faGlobeThin, faGlobeDuoTone,
    faGlobeAmericas, faGlobeAmericasLight, faGlobeAmericasSolid, faGlobeAmericasThin, faGlobeAmericasDuoTone,
    faGraduationCap, faGraduationCapLight, faGraduationCapSolid, faGraduationCapThin, faGraduationCapDuoTone,
    faGreaterThan, faGreaterThanLight, faGreaterThanSolid, faGreaterThanThin, faGreaterThanDuoTone,
    faGreaterThanEqual, faGreaterThanEqualLight, faGreaterThanEqualSolid, faGreaterThanEqualThin, faGreaterThanEqualDuoTone,
    faGripHorizontal, faGripHorizontalLight, faGripHorizontalSolid, faGripHorizontalThin, faGripHorizontalDuoTone,
    faHandPaper, faHandPaperLight, faHandPaperSolid, faHandPaperThin, faHandPaperDuoTone,
    faHandPointUp, faHandPointUpLight, faHandPointUpSolid, faHandPointUpThin, faHandPointUpDuoTone,
    faHandshake, faHandshakeLight, faHandshakeSolid, faHandshakeThin, faHandshakeDuoTone,
    faHeartRate, faHeartRateLight, faHeartRateSolid, faHeartRateThin, faHeartRateDuoTone,
    faHistory, faHistoryLight, faHistorySolid, faHistoryThin, faHistoryDuoTone,
    faHome, faHomeLight, faHomeSolid, faHomeThin, faHomeDuoTone,
    faInbox, faInboxLight, faInboxSolid, faInboxThin, faInboxDuoTone,
    faIndustryAlt, faIndustryAltLight, faIndustryAltSolid, faIndustryAltThin, faIndustryAltDuoTone,
    faInfoCircle, faInfoCircleLight, faInfoCircleSolid, faInfoCircleThin, faInfoCircleDuoTone,
    faLessThan, faLessThanLight, faLessThanSolid, faLessThanThin, faLessThanDuoTone,
    faLessThanEqual, faLessThanEqualLight, faLessThanEqualSolid, faLessThanEqualThin, faLessThanEqualDuoTone,
    faLink, faLinkLight, faLinkSolid, faLinkThin, faLinkDuoTone,
    faLock, faLockLight, faLockSolid, faLockThin, faLockDuoTone,
    faLockOpen, faLockOpenLight, faLockOpenSolid, faLockOpenThin, faLockOpenDuoTone,
    faWandMagicSparkles, faWandMagicSparklesLight, faWandMagicSparklesSolid, faWandMagicSparklesThin, faWandMagicSparklesDuoTone,
    faMapMarkerAlt, faMapMarkerAltLight, faMapMarkerAltSolid, faMapMarkerAltThin, faMapMarkerAltDuoTone,
    faMapSigns, faMapSignsLight, faMapSignsSolid, faMapSignsThin, faMapSignsDuoTone,
    faMask, faMaskLight, faMaskSolid, faMaskThin, faMaskDuoTone,
    faMinusCircle, faMinusCircleLight, faMinusCircleSolid, faMinusCircleThin, faMinusCircleDuoTone,
    faMobileScreen, faMobileScreenLight, faMobileScreenSolid, faMobileScreenThin, faMobileScreenDuoTone,
    faMoon, faMoonLight, faMoonSolid, faMoonThin, faMoonDuoTone,
    faNewspaper, faNewspaperLight, faNewspaperSolid, faNewspaperThin, faNewspaperDuoTone,
    faNotEqual, faNotEqualLight, faNotEqualSolid, faNotEqualThin, faNotEqualDuoTone,
    faPaperclip, faPaperclipLight, faPaperclipSolid, faPaperclipThin, faPaperclipDuoTone,
    faPaste, faPasteLight, faPasteSolid, faPasteThin, faPasteDuoTone,
    faPause, faPauseLight, faPauseSolid, faPauseThin, faPauseDuoTone,
    faPauseCircle, faPauseCircleLight, faPauseCircleSolid, faPauseCircleThin, faPauseCircleDuoTone,
    faPlay, faPlayLight, faPlaySolid, faPlayThin, faPlayDuoTone,
    faPhoneAlt, faPhoneAltLight, faPhoneAltSolid, faPhoneAltThin, faPhoneAltDuoTone,
    faPlayCircle, faPlayCircleLight, faPlayCircleSolid, faPlayCircleThin, faPlayCircleDuoTone,
    faPlus, faPlusLight, faPlusSolid, faPlusThin, faPlusDuoTone,
    faPlusCircle, faPlusCircleLight, faPlusCircleSolid, faPlusCircleThin, faPlusCircleDuoTone,
    faPoundSign, faPoundSignLight, faPoundSignSolid, faPoundSignThin, faPoundSignDuoTone,
    faPrint, faPrintLight, faPrintSolid, faPrintThin, faPrintDuoTone,
    faQuestion, faQuestionLight, faQuestionSolid, faQuestionThin, faQuestionDuoTone,
    faQuestionCircle, faQuestionCircleLight, faQuestionCircleSolid, faQuestionCircleThin, faQuestionCircleDuoTone,
    faRandom, faRandomLight, faRandomSolid, faRandomThin, faRandomDuoTone,
    faReceipt, faReceiptLight, faReceiptSolid, faReceiptThin, faReceiptDuoTone,
    faRedo, faRedoLight, faRedoSolid, faRedoThin, faRedoDuoTone,
    faRocket, faRocketLight, faRocketSolid, faRocketThin, faRocketDuoTone,
    faSave, faSaveLight, faSaveSolid, faSaveThin, faSaveDuoTone,
    faSearch, faSearchLight, faSearchSolid, faSearchThin, faSearchDuoTone,
    faServer, faServerLight, faServerSolid, faServerThin, faServerDuoTone,
    faShieldAlt, faShieldAltLight, faShieldAltSolid, faShieldAltThin, faShieldAltDuoTone,
    faShieldCheck, faShieldCheckLight, faShieldCheckSolid, faShieldCheckThin, faShieldCheckDuoTone,
    faSigma, faSigmaLight, faSigmaSolid, faSigmaThin, faSigmaDuoTone,
    faSignIn, faSignInLight, faSignInSolid, faSignInThin, faSignInDuoTone,
    faSignOut, faSignOutLight, faSignOutSolid, faSignOutThin, faSignOutDuoTone,
    faSkull, faSkullLight, faSkullSolid, faSkullThin, faSkullDuoTone,
    faSlidersHSquare, faSlidersHSquareLight, faSlidersHSquareSolid, faSlidersHSquareThin, faSlidersHSquareDuoTone,
    faSpinner, faSpinnerLight, faSpinnerSolid, faSpinnerThin, faSpinnerDuoTone,
    faStar, faStarLight, faStarSolid, faStarThin, faStarDuoTone,
    faStethoscope, faStethoscopeLight, faStethoscopeSolid, faStethoscopeThin, faStethoscopeDuoTone,
    faStop, faStopLight, faStopSolid, faStopThin, faStopDuoTone,
    faStopCircle, faStopCircleLight, faStopCircleSolid, faStopCircleThin, faStopCircleDuoTone,
    faStopwatch, faStopwatchLight, faStopwatchSolid, faStopwatchThin, faStopwatchDuoTone,
    faStream, faStreamLight, faStreamSolid, faStreamThin, faStreamDuoTone,
    faSun, faSunLight, faSunSolid, faSunThin, faSunDuoTone,
    faSync, faSyncLight, faSyncSolid, faSyncThin, faSyncDuoTone,
    faTable, faTableLight, faTableSolid, faTableThin, faTableDuoTone,
    faTableLayout, faTableLayoutLight, faTableLayoutSolid, faTableLayoutThin, faTableLayoutDuoTone,
    faGaugeHigh, faGaugeHighLight, faGaugeHighSolid, faGaugeHighThin, faGaugeHighDuoTone,
    faTag, faTagLight, faTagSolid, faTagThin, faTagDuoTone,
    faTags, faTagsLight, faTagsSolid, faTagsThin, faTagsDuoTone,
    faTh, faThLight, faThSolid, faThThin, faThDuoTone,
    faThLarge, faThLargeLight, faThLargeSolid, faThLargeThin, faThLargeDuoTone,
    faThumbsDown, faThumbsDownLight, faThumbsDownSolid, faThumbsDownThin, faThumbsDownDuoTone,
    faThumbsUp, faThumbsUpLight, faThumbsUpSolid, faThumbsUpThin, faThumbsUpDuoTone,
    faThumbtack, faThumbtackLight, faThumbtackSolid, faThumbtackThin, faThumbtackDuoTone,
    faTimes, faTimesLight, faTimesSolid, faTimesThin, faTimesDuoTone,
    faTimesCircle, faTimesCircleLight, faTimesCircleSolid, faTimesCircleThin, faTimesCircleDuoTone,
    faTimesHexagon, faTimesHexagonLight, faTimesHexagonSolid, faTimesHexagonThin, faTimesHexagonDuoTone,
    faToolbox, faToolboxLight, faToolboxSolid, faToolboxThin, faToolboxDuoTone,
    faTools, faToolsLight, faToolsSolid, faToolsThin, faToolsDuoTone,
    faTrashAlt, faTrashAltLight, faTrashAltSolid, faTrashAltThin, faTrashAltDuoTone,
    faUndo, faUndoLight, faUndoSolid, faUndoThin, faUndoDuoTone,
    faUniversity, faUniversityLight, faUniversitySolid, faUniversityThin, faUniversityDuoTone,
    faUnlink, faUnlinkLight, faUnlinkSolid, faUnlinkThin, faUnlinkDuoTone,
    faUpload, faUploadLight, faUploadSolid, faUploadThin, faUploadDuoTone,
    faUsdCircle, faUsdCircleLight, faUsdCircleSolid, faUsdCircleThin, faUsdCircleDuoTone,
    faUser, faUserLight, faUserSolid, faUserThin, faUserDuoTone,
    faUserCheck, faUserCheckLight, faUserCheckSolid, faUserCheckThin, faUserCheckDuoTone,
    faUserCircle, faUserCircleLight, faUserCircleSolid, faUserCircleThin, faUserCircleDuoTone,
    faUserClock, faUserClockLight, faUserClockSolid, faUserClockThin, faUserClockDuoTone,
    faUserFriends, faUserFriendsLight, faUserFriendsSolid, faUserFriendsThin, faUserFriendsDuoTone,
    faUsers, faUsersLight, faUsersSolid, faUsersThin, faUsersDuoTone,
    faWindow, faWindowLight, faWindowSolid, faWindowThin, faWindowDuoTone,
    faWrench, faWrenchLight, faWrenchSolid, faWrenchThin, faWrenchDuoTone
);
