/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2024 Extremely Heavy Industries Inc.
 */
export * from './Icon';
export * from './XHLogo';

import {library} from '@fortawesome/fontawesome-svg-core';
import {
    faAddressCard as faAddressCardLight,
    faAlignJustify as faAlignJustifyLight,
    faAnalytics as faAnalyticsLight,
    faAngleDoubleDown as faAngleDoubleDownLight,
    faAngleDoubleLeft as faAngleDoubleLeftLight,
    faAngleDoubleRight as faAngleDoubleRightLight,
    faAngleDoubleUp as faAngleDoubleUpLight,
    faAngleDown as faAngleDownLight,
    faAngleLeft as faAngleLeftLight,
    faAngleRight as faAngleRightLight,
    faAngleUp as faAngleUpLight,
    faArrowDown as faArrowDownLight,
    faArrowDownToBracket as faArrowDownToBracketLight,
    faArrowLeft as faArrowLeftLight,
    faArrowRight as faArrowRightLight,
    faArrowsH as faArrowsHLight,
    faArrowsV as faArrowsVLight,
    faArrowToBottom as faArrowToBottomLight,
    faArrowToLeft as faArrowToLeftLight,
    faArrowToRight as faArrowToRightLight,
    faArrowToTop as faArrowToTopLight,
    faArrowUp as faArrowUpLight,
    faArrowUpFromBracket as faArrowUpFromBracketLight,
    faBalanceScale as faBalanceScaleLight,
    faBalanceScaleLeft as faBalanceScaleLeftLight,
    faBalanceScaleRight as faBalanceScaleRightLight,
    faBan as faBanLight,
    faBars as faBarsLight,
    faBolt as faBoltLight,
    faBook as faBookLight,
    faBookmark as faBookmarkLight,
    faBooks as faBooksLight,
    faBox as faBoxLight,
    faBoxFull as faBoxFullLight,
    faBracketsCurly as faBracketsCurlyLight,
    faBreadSlice as faBreadSliceLight,
    faBriefcase as faBriefcaseLight,
    faBrowser as faBrowserLight,
    faBuilding as faBuildingLight,
    faBullhorn as faBullhornLight,
    faBullseyeArrow as faBullseyeArrowLight,
    faCalculator as faCalculatorLight,
    faCalendarDay as faCalendarDayLight,
    faCamera as faCameraLight,
    faCaretLeft as faCaretLeftLight,
    faCaretRight as faCaretRightLight,
    faChartArea as faChartAreaLight,
    faChartColumn as faChartColumnLight,
    faChartLine as faChartLineLight,
    faChartPie as faChartPieLight,
    faChartTreeMap as faChartTreeMapLight,
    faCheck as faCheckLight,
    faCheckCircle as faCheckCircleLight,
    faCheckSquare as faCheckSquareLight,
    faChess as faChessLight,
    faChessKnightAlt as faChessKnightAltLight,
    faChevronDown as faChevronDownLight,
    faChevronLeft as faChevronLeftLight,
    faChevronRight as faChevronRightLight,
    faChevronUp as faChevronUpLight,
    faCircle as faCircleLight,
    faClipboard as faClipboardLight,
    faClock as faClockLight,
    faCloudDownload as faCloudDownloadLight,
    faCloudUpload as faCloudUploadLight,
    faCode as faCodeLight,
    faCog as faCogLight,
    faCogs as faCogsLight,
    faCommentDots as faCommentDotsLight,
    faCompressAlt as faCompressAltLight,
    faCopy as faCopyLight,
    faCrosshairs as faCrosshairsLight,
    faCube as faCubeLight,
    faDatabase as faDatabaseLight,
    faDesktop as faDesktopLight,
    faDollarSign as faDollarSignLight,
    faEdit as faEditLight,
    faEllipsisH as faEllipsisHLight,
    faEllipsisV as faEllipsisVLight,
    faEnvelope as faEnvelopeLight,
    faEquals as faEqualsLight,
    faEuroSign as faEuroSignLight,
    faExchange as faExchangeLight,
    faExclamationCircle as faExclamationCircleLight,
    faExclamationSquare as faExclamationSquareLight,
    faExclamationTriangle as faExclamationTriangleLight,
    faExpandAlt as faExpandAltLight,
    faExternalLink as faExternalLinkLight,
    faEye as faEyeLight,
    faEyeSlash as faEyeSlashLight,
    faFile as faFileLight,
    faFileAlt as faFileAltLight,
    faFileArchive as faFileArchiveLight,
    faFileCertificate as faFileCertificateLight,
    faFileChartColumn as faFileChartColumnLight,
    faFileCsv as faFileCsvLight,
    faFileExcel as faFileExcelLight,
    faFileImage as faFileImageLight,
    faFilePdf as faFilePdfLight,
    faFilePowerpoint as faFilePowerpointLight,
    faFileWord as faFileWordLight,
    faFilter as faFilterLight,
    faFilterSlash as faFilterSlashLight,
    faFlag as faFlagLight,
    faFlask as faFlaskLight,
    faFolder as faFolderLight,
    faFolderOpen as faFolderOpenLight,
    faFunction as faFunctionLight,
    faGaugeHigh as faGaugeHighLight,
    faGift as faGiftLight,
    faGlobe as faGlobeLight,
    faGlobeAmericas as faGlobeAmericasLight,
    faGraduationCap as faGraduationCapLight,
    faGreaterThan as faGreaterThanLight,
    faGreaterThanEqual as faGreaterThanEqualLight,
    faGripHorizontal as faGripHorizontalLight,
    faHandPaper as faHandPaperLight,
    faHandPointUp as faHandPointUpLight,
    faHandshake as faHandshakeLight,
    faHeartRate as faHeartRateLight,
    faHistory as faHistoryLight,
    faHome as faHomeLight,
    faIdBadge as faIdBadgeLight,
    faInbox as faInboxLight,
    faIndustryAlt as faIndustryAltLight,
    faInfoCircle as faInfoCircleLight,
    faLessThan as faLessThanLight,
    faLessThanEqual as faLessThanEqualLight,
    faLink as faLinkLight,
    faListTree as faListTreeLight,
    faLock as faLockLight,
    faLockOpen as faLockOpenLight,
    faMapMarkerAlt as faMapMarkerAltLight,
    faMapSigns as faMapSignsLight,
    faMask as faMaskLight,
    faMemory as faMemoryLight,
    faMinusCircle as faMinusCircleLight,
    faMobileScreen as faMobileScreenLight,
    faMoon as faMoonLight,
    faNewspaper as faNewspaperLight,
    faNotEqual as faNotEqualLight,
    faPaperclip as faPaperclipLight,
    faPaste as faPasteLight,
    faPause as faPauseLight,
    faPauseCircle as faPauseCircleLight,
    faPhoneAlt as faPhoneAltLight,
    faPlay as faPlayLight,
    faPlayCircle as faPlayCircleLight,
    faPlus as faPlusLight,
    faPlusCircle as faPlusCircleLight,
    faPoundSign as faPoundSignLight,
    faPrint as faPrintLight,
    faQuestion as faQuestionLight,
    faQuestionCircle as faQuestionCircleLight,
    faRandom as faRandomLight,
    faReceipt as faReceiptLight,
    faRectangleTerminal as faRectangleTerminalLight,
    faRedo as faRedoLight,
    faRocket as faRocketLight,
    faUserShield as faUserShieldLight,
    faSave as faSaveLight,
    faSearch as faSearchLight,
    faServer as faServerLight,
    faShieldAlt as faShieldAltLight,
    faShieldCheck as faShieldCheckLight,
    faSigma as faSigmaLight,
    faSignIn as faSignInLight,
    faSignOut as faSignOutLight,
    faSitemap as faSitemapLight,
    faSkull as faSkullLight,
    faSlidersHSquare as faSlidersHSquareLight,
    faSpinner as faSpinnerLight,
    faSquare as faSquareLight,
    faStar as faStarLight,
    faStethoscope as faStethoscopeLight,
    faStop as faStopLight,
    faStopCircle as faStopCircleLight,
    faStopwatch as faStopwatchLight,
    faSun as faSunLight,
    faSync as faSyncLight,
    faTable as faTableLight,
    faTableLayout as faTableLayoutLight,
    faTag as faTagLight,
    faTags as faTagsLight,
    faTh as faThLight,
    faThLarge as faThLargeLight,
    faThumbsDown as faThumbsDownLight,
    faThumbsUp as faThumbsUpLight,
    faThumbtack as faThumbtackLight,
    faTimes as faTimesLight,
    faTimesCircle as faTimesCircleLight,
    faTimesHexagon as faTimesHexagonLight,
    faToolbox as faToolboxLight,
    faTools as faToolsLight,
    faTrashAlt as faTrashAltLight,
    faUndo as faUndoLight,
    faUniversity as faUniversityLight,
    faUnlink as faUnlinkLight,
    faUsdCircle as faUsdCircleLight,
    faUser as faUserLight,
    faUserCheck as faUserCheckLight,
    faUserCircle as faUserCircleLight,
    faUserClock as faUserClockLight,
    faUserFriends as faUserFriendsLight,
    faUsers as faUsersLight,
    faWandMagicSparkles as faWandMagicSparklesLight,
    faWindow as faWindowLight,
    faWrench as faWrenchLight
} from '@fortawesome/pro-light-svg-icons';
import {
    faAddressCard,
    faAlignJustify,
    faAnalytics,
    faAngleDoubleDown,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faAngleDoubleUp,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faArrowDown,
    faArrowDownToBracket,
    faArrowLeft,
    faArrowRight,
    faArrowsH,
    faArrowsV,
    faArrowToBottom,
    faArrowToLeft,
    faArrowToRight,
    faArrowToTop,
    faArrowUp,
    faArrowUpFromBracket,
    faBalanceScale,
    faBalanceScaleLeft,
    faBalanceScaleRight,
    faBan,
    faBars,
    faBolt,
    faBook,
    faBookmark,
    faBooks,
    faBox,
    faBoxFull,
    faBracketsCurly,
    faBreadSlice,
    faBriefcase,
    faBrowser,
    faBuilding,
    faBullhorn,
    faBullseyeArrow,
    faCalculator,
    faCalendarDay,
    faCamera,
    faCaretLeft,
    faCaretRight,
    faChartArea,
    faChartColumn,
    faChartLine,
    faChartPie,
    faChartTreeMap,
    faCheck,
    faCheckCircle,
    faCheckSquare,
    faChess,
    faChessKnightAlt,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faCircle,
    faClipboard,
    faClock,
    faCloudDownload,
    faCloudUpload,
    faCode,
    faCog,
    faCogs,
    faCommentDots,
    faCompressAlt,
    faCopy,
    faCrosshairs,
    faCube,
    faDatabase,
    faDesktop,
    faDollarSign,
    faEdit,
    faEllipsisH,
    faEllipsisV,
    faEnvelope,
    faEquals,
    faEuroSign,
    faExchange,
    faExclamationCircle,
    faExclamationSquare,
    faExclamationTriangle,
    faExpandAlt,
    faExternalLink,
    faEye,
    faEyeSlash,
    faFile,
    faFileAlt,
    faFileArchive,
    faFileCertificate,
    faFileChartColumn,
    faFileCsv,
    faFileExcel,
    faFileImage,
    faFilePdf,
    faFilePowerpoint,
    faFileWord,
    faFilter,
    faFilterSlash,
    faFlag,
    faFlask,
    faFolder,
    faFolderOpen,
    faFunction,
    faGaugeHigh,
    faGift,
    faGlobe,
    faGlobeAmericas,
    faGraduationCap,
    faGreaterThan,
    faGreaterThanEqual,
    faGripHorizontal,
    faHandPaper,
    faHandPointUp,
    faHandshake,
    faHeartRate,
    faHistory,
    faHome,
    faInbox,
    faIdBadge,
    faIndustryAlt,
    faInfoCircle,
    faLessThan,
    faLessThanEqual,
    faLink,
    faListTree,
    faLock,
    faLockOpen,
    faMapMarkerAlt,
    faMapSigns,
    faMask,
    faMemory,
    faMinusCircle,
    faMobileScreen,
    faMoon,
    faNewspaper,
    faNotEqual,
    faPaperclip,
    faPaste,
    faPause,
    faPauseCircle,
    faPhoneAlt,
    faPlay,
    faPlayCircle,
    faPlus,
    faPlusCircle,
    faPoundSign,
    faPrint,
    faQuestion,
    faQuestionCircle,
    faRandom,
    faReceipt,
    faRectangleTerminal,
    faRedo,
    faRocket,
    faUserShield,
    faSave,
    faSearch,
    faServer,
    faShieldAlt,
    faShieldCheck,
    faSigma,
    faSignIn,
    faSignOut,
    faSkull,
    faSlidersHSquare,
    faSpinner,
    faSquare,
    faStar,
    faStethoscope,
    faStop,
    faStopCircle,
    faStopwatch,
    faSun,
    faSync,
    faTable,
    faTableLayout,
    faTag,
    faTags,
    faTh,
    faThLarge,
    faThumbsDown,
    faThumbsUp,
    faThumbtack,
    faTimes,
    faTimesCircle,
    faTimesHexagon,
    faToolbox,
    faTools,
    faTrashAlt,
    faUndo,
    faUniversity,
    faUnlink,
    faUsdCircle,
    faUser,
    faUserCheck,
    faUserCircle,
    faUserClock,
    faUserFriends,
    faUsers,
    faWandMagicSparkles,
    faWindow,
    faWrench,
    faSitemap
} from '@fortawesome/pro-regular-svg-icons';
import {
    faAddressCard as faAddressCardSolid,
    faAlignJustify as faAlignJustifySolid,
    faAnalytics as faAnalyticsSolid,
    faAngleDoubleDown as faAngleDoubleDownSolid,
    faAngleDoubleLeft as faAngleDoubleLeftSolid,
    faAngleDoubleRight as faAngleDoubleRightSolid,
    faAngleDoubleUp as faAngleDoubleUpSolid,
    faAngleDown as faAngleDownSolid,
    faAngleLeft as faAngleLeftSolid,
    faAngleRight as faAngleRightSolid,
    faAngleUp as faAngleUpSolid,
    faArrowDown as faArrowDownSolid,
    faArrowDownToBracket as faArrowDownToBracketSolid,
    faArrowLeft as faArrowLeftSolid,
    faArrowRight as faArrowRightSolid,
    faArrowsH as faArrowsHSolid,
    faArrowsV as faArrowsVSolid,
    faArrowToBottom as faArrowToBottomSolid,
    faArrowToLeft as faArrowToLeftSolid,
    faArrowToRight as faArrowToRightSolid,
    faArrowToTop as faArrowToTopSolid,
    faArrowUp as faArrowUpSolid,
    faArrowUpFromBracket as faArrowUpFromBracketSolid,
    faBalanceScale as faBalanceScaleSolid,
    faBalanceScaleLeft as faBalanceScaleLeftSolid,
    faBalanceScaleRight as faBalanceScaleRightSolid,
    faBan as faBanSolid,
    faBars as faBarsSolid,
    faBolt as faBoltSolid,
    faBook as faBookSolid,
    faBookmark as faBookmarkSolid,
    faBooks as faBooksSolid,
    faBox as faBoxSolid,
    faBoxFull as faBoxFullSolid,
    faBracketsCurly as faBracketsCurlySolid,
    faBreadSlice as faBreadSliceSolid,
    faBriefcase as faBriefcaseSolid,
    faBrowser as faBrowserSolid,
    faBuilding as faBuildingSolid,
    faBullhorn as faBullhornSolid,
    faBullseyeArrow as faBullseyeArrowSolid,
    faCalculator as faCalculatorSolid,
    faCalendarDay as faCalendarDaySolid,
    faCamera as faCameraSolid,
    faCaretLeft as faCaretLeftSolid,
    faCaretRight as faCaretRightSolid,
    faChartArea as faChartAreaSolid,
    faChartColumn as faChartColumnSolid,
    faChartLine as faChartLineSolid,
    faChartPie as faChartPieSolid,
    faChartTreeMap as faChartTreeMapSolid,
    faCheck as faCheckSolid,
    faCheckCircle as faCheckCircleSolid,
    faCheckSquare as faCheckSquareSolid,
    faChess as faChessSolid,
    faChessKnightAlt as faChessKnightAltSolid,
    faChevronDown as faChevronDownSolid,
    faChevronLeft as faChevronLeftSolid,
    faChevronRight as faChevronRightSolid,
    faChevronUp as faChevronUpSolid,
    faCircle as faCircleSolid,
    faClipboard as faClipboardSolid,
    faClock as faClockSolid,
    faCloudDownload as faCloudDownloadSolid,
    faCloudUpload as faCloudUploadSolid,
    faCode as faCodeSolid,
    faCog as faCogSolid,
    faCogs as faCogsSolid,
    faCommentDots as faCommentDotsSolid,
    faCompressAlt as faCompressAltSolid,
    faCopy as faCopySolid,
    faCrosshairs as faCrosshairsSolid,
    faCube as faCubeSolid,
    faDatabase as faDatabaseSolid,
    faDesktop as faDesktopSolid,
    faDollarSign as faDollarSignSolid,
    faEdit as faEditSolid,
    faEllipsisH as faEllipsisHSolid,
    faEllipsisV as faEllipsisVSolid,
    faEnvelope as faEnvelopeSolid,
    faEquals as faEqualsSolid,
    faEuroSign as faEuroSignSolid,
    faExchange as faExchangeSolid,
    faExclamationCircle as faExclamationCircleSolid,
    faExclamationSquare as faExclamationSquareSolid,
    faExclamationTriangle as faExclamationTriangleSolid,
    faExpandAlt as faExpandAltSolid,
    faExternalLink as faExternalLinkSolid,
    faEye as faEyeSolid,
    faEyeSlash as faEyeSlashSolid,
    faFile as faFileSolid,
    faFileAlt as faFileAltSolid,
    faFileArchive as faFileArchiveSolid,
    faFileCertificate as faFileCertificateSolid,
    faFileChartColumn as faFileChartColumnSolid,
    faFileCsv as faFileCsvSolid,
    faFileExcel as faFileExcelSolid,
    faFileImage as faFileImageSolid,
    faFilePdf as faFilePdfSolid,
    faFilePowerpoint as faFilePowerpointSolid,
    faFileWord as faFileWordSolid,
    faFilter as faFilterSolid,
    faFilterSlash as faFilterSlashSolid,
    faFlag as faFlagSolid,
    faFlask as faFlaskSolid,
    faFolder as faFolderSolid,
    faFolderOpen as faFolderOpenSolid,
    faFunction as faFunctionSolid,
    faGaugeHigh as faGaugeHighSolid,
    faGift as faGiftSolid,
    faGlobe as faGlobeSolid,
    faGlobeAmericas as faGlobeAmericasSolid,
    faGraduationCap as faGraduationCapSolid,
    faGreaterThan as faGreaterThanSolid,
    faGreaterThanEqual as faGreaterThanEqualSolid,
    faGripHorizontal as faGripHorizontalSolid,
    faHandPaper as faHandPaperSolid,
    faHandPointUp as faHandPointUpSolid,
    faHandshake as faHandshakeSolid,
    faHeartRate as faHeartRateSolid,
    faHistory as faHistorySolid,
    faHome as faHomeSolid,
    faInbox as faInboxSolid,
    faIdBadge as faIdBadgeSolid,
    faIndustryAlt as faIndustryAltSolid,
    faInfoCircle as faInfoCircleSolid,
    faLessThan as faLessThanSolid,
    faLessThanEqual as faLessThanEqualSolid,
    faLink as faLinkSolid,
    faListTree as faListTreeSolid,
    faLock as faLockSolid,
    faLockOpen as faLockOpenSolid,
    faMapMarkerAlt as faMapMarkerAltSolid,
    faMapSigns as faMapSignsSolid,
    faMask as faMaskSolid,
    faMemory as faMemorySolid,
    faMinusCircle as faMinusCircleSolid,
    faMobileScreen as faMobileScreenSolid,
    faMoon as faMoonSolid,
    faNewspaper as faNewspaperSolid,
    faNotEqual as faNotEqualSolid,
    faPaperclip as faPaperclipSolid,
    faPaste as faPasteSolid,
    faPause as faPauseSolid,
    faPauseCircle as faPauseCircleSolid,
    faPhoneAlt as faPhoneAltSolid,
    faPlay as faPlaySolid,
    faPlayCircle as faPlayCircleSolid,
    faPlus as faPlusSolid,
    faPlusCircle as faPlusCircleSolid,
    faPoundSign as faPoundSignSolid,
    faPrint as faPrintSolid,
    faQuestion as faQuestionSolid,
    faQuestionCircle as faQuestionCircleSolid,
    faRandom as faRandomSolid,
    faReceipt as faReceiptSolid,
    faRectangleTerminal as faRectangleTerminalSolid,
    faRedo as faRedoSolid,
    faRocket as faRocketSolid,
    faUserShield as faUserShieldSolid,
    faSave as faSaveSolid,
    faSearch as faSearchSolid,
    faServer as faServerSolid,
    faShieldAlt as faShieldAltSolid,
    faShieldCheck as faShieldCheckSolid,
    faSigma as faSigmaSolid,
    faSignIn as faSignInSolid,
    faSignOut as faSignOutSolid,
    faSitemap as faSitemapSolid,
    faSkull as faSkullSolid,
    faSlidersHSquare as faSlidersHSquareSolid,
    faSpinner as faSpinnerSolid,
    faSquare as faSquareSolid,
    faStar as faStarSolid,
    faStethoscope as faStethoscopeSolid,
    faStop as faStopSolid,
    faStopCircle as faStopCircleSolid,
    faStopwatch as faStopwatchSolid,
    faSun as faSunSolid,
    faSync as faSyncSolid,
    faTable as faTableSolid,
    faTableLayout as faTableLayoutSolid,
    faTag as faTagSolid,
    faTags as faTagsSolid,
    faTh as faThSolid,
    faThLarge as faThLargeSolid,
    faThumbsDown as faThumbsDownSolid,
    faThumbsUp as faThumbsUpSolid,
    faThumbtack as faThumbtackSolid,
    faTimes as faTimesSolid,
    faTimesCircle as faTimesCircleSolid,
    faTimesHexagon as faTimesHexagonSolid,
    faToolbox as faToolboxSolid,
    faTools as faToolsSolid,
    faTrashAlt as faTrashAltSolid,
    faUndo as faUndoSolid,
    faUniversity as faUniversitySolid,
    faUnlink as faUnlinkSolid,
    faUsdCircle as faUsdCircleSolid,
    faUser as faUserSolid,
    faUserCheck as faUserCheckSolid,
    faUserCircle as faUserCircleSolid,
    faUserClock as faUserClockSolid,
    faUserFriends as faUserFriendsSolid,
    faUsers as faUsersSolid,
    faWandMagicSparkles as faWandMagicSparklesSolid,
    faWindow as faWindowSolid,
    faWrench as faWrenchSolid
} from '@fortawesome/pro-solid-svg-icons';

import {
    faAddressCard as faAddressCardThin,
    faAlignJustify as faAlignJustifyThin,
    faAnalytics as faAnalyticsThin,
    faAngleDoubleDown as faAngleDoubleDownThin,
    faAngleDoubleLeft as faAngleDoubleLeftThin,
    faAngleDoubleRight as faAngleDoubleRightThin,
    faAngleDoubleUp as faAngleDoubleUpThin,
    faAngleDown as faAngleDownThin,
    faAngleLeft as faAngleLeftThin,
    faAngleRight as faAngleRightThin,
    faAngleUp as faAngleUpThin,
    faArrowDown as faArrowDownThin,
    faArrowDownToBracket as faArrowDownToBracketThin,
    faArrowLeft as faArrowLeftThin,
    faArrowRight as faArrowRightThin,
    faArrowsH as faArrowsHThin,
    faArrowsV as faArrowsVThin,
    faArrowToBottom as faArrowToBottomThin,
    faArrowToLeft as faArrowToLeftThin,
    faArrowToRight as faArrowToRightThin,
    faArrowToTop as faArrowToTopThin,
    faArrowUp as faArrowUpThin,
    faArrowUpFromBracket as faArrowUpFromBracketThin,
    faBalanceScale as faBalanceScaleThin,
    faBalanceScaleLeft as faBalanceScaleLeftThin,
    faBalanceScaleRight as faBalanceScaleRightThin,
    faBan as faBanThin,
    faBars as faBarsThin,
    faBolt as faBoltThin,
    faBook as faBookThin,
    faBookmark as faBookmarkThin,
    faBooks as faBooksThin,
    faBox as faBoxThin,
    faBoxFull as faBoxFullThin,
    faBracketsCurly as faBracketsCurlyThin,
    faBreadSlice as faBreadSliceThin,
    faBriefcase as faBriefcaseThin,
    faBrowser as faBrowserThin,
    faBuilding as faBuildingThin,
    faBullhorn as faBullhornThin,
    faBullseyeArrow as faBullseyeArrowThin,
    faCalculator as faCalculatorThin,
    faCalendarDay as faCalendarDayThin,
    faCamera as faCameraThin,
    faCaretLeft as faCaretLeftThin,
    faCaretRight as faCaretRightThin,
    faChartArea as faChartAreaThin,
    faChartColumn as faChartColumnThin,
    faChartLine as faChartLineThin,
    faChartPie as faChartPieThin,
    faChartTreeMap as faChartTreeMapThin,
    faCheck as faCheckThin,
    faCheckCircle as faCheckCircleThin,
    faCheckSquare as faCheckSquareThin,
    faChess as faChessThin,
    faChessKnightAlt as faChessKnightAltThin,
    faChevronDown as faChevronDownThin,
    faChevronLeft as faChevronLeftThin,
    faChevronRight as faChevronRightThin,
    faChevronUp as faChevronUpThin,
    faCircle as faCircleThin,
    faClipboard as faClipboardThin,
    faClock as faClockThin,
    faCloudDownload as faCloudDownloadThin,
    faCloudUpload as faCloudUploadThin,
    faCode as faCodeThin,
    faCog as faCogThin,
    faCogs as faCogsThin,
    faCommentDots as faCommentDotsThin,
    faCompressAlt as faCompressAltThin,
    faCopy as faCopyThin,
    faCrosshairs as faCrosshairsThin,
    faCube as faCubeThin,
    faDatabase as faDatabaseThin,
    faDesktop as faDesktopThin,
    faDollarSign as faDollarSignThin,
    faEdit as faEditThin,
    faEllipsisH as faEllipsisHThin,
    faEllipsisV as faEllipsisVThin,
    faEnvelope as faEnvelopeThin,
    faEquals as faEqualsThin,
    faEuroSign as faEuroSignThin,
    faExchange as faExchangeThin,
    faExclamationCircle as faExclamationCircleThin,
    faExclamationSquare as faExclamationSquareThin,
    faExclamationTriangle as faExclamationTriangleThin,
    faExpandAlt as faExpandAltThin,
    faExternalLink as faExternalLinkThin,
    faEye as faEyeThin,
    faEyeSlash as faEyeSlashThin,
    faFile as faFileThin,
    faFileAlt as faFileAltThin,
    faFileArchive as faFileArchiveThin,
    faFileCertificate as faFileCertificateThin,
    faFileChartColumn as faFileChartColumnThin,
    faFileCsv as faFileCsvThin,
    faFileExcel as faFileExcelThin,
    faFileImage as faFileImageThin,
    faFilePdf as faFilePdfThin,
    faFilePowerpoint as faFilePowerpointThin,
    faFileWord as faFileWordThin,
    faFilter as faFilterThin,
    faFilterSlash as faFilterSlashThin,
    faFlag as faFlagThin,
    faFlask as faFlaskThin,
    faFolder as faFolderThin,
    faFolderOpen as faFolderOpenThin,
    faFunction as faFunctionThin,
    faGaugeHigh as faGaugeHighThin,
    faGift as faGiftThin,
    faGlobe as faGlobeThin,
    faGlobeAmericas as faGlobeAmericasThin,
    faGraduationCap as faGraduationCapThin,
    faGreaterThan as faGreaterThanThin,
    faGreaterThanEqual as faGreaterThanEqualThin,
    faGripHorizontal as faGripHorizontalThin,
    faHandPaper as faHandPaperThin,
    faHandPointUp as faHandPointUpThin,
    faHandshake as faHandshakeThin,
    faHeartRate as faHeartRateThin,
    faHistory as faHistoryThin,
    faHome as faHomeThin,
    faInbox as faInboxThin,
    faIdBadge as faIdBadgeThin,
    faIndustryAlt as faIndustryAltThin,
    faInfoCircle as faInfoCircleThin,
    faLessThan as faLessThanThin,
    faLessThanEqual as faLessThanEqualThin,
    faLink as faLinkThin,
    faListTree as faListTreeThin,
    faLock as faLockThin,
    faLockOpen as faLockOpenThin,
    faMapMarkerAlt as faMapMarkerAltThin,
    faMapSigns as faMapSignsThin,
    faMask as faMaskThin,
    faMemory as faMemoryThin,
    faMinusCircle as faMinusCircleThin,
    faMobileScreen as faMobileScreenThin,
    faMoon as faMoonThin,
    faNewspaper as faNewspaperThin,
    faNotEqual as faNotEqualThin,
    faPaperclip as faPaperclipThin,
    faPaste as faPasteThin,
    faPause as faPauseThin,
    faPauseCircle as faPauseCircleThin,
    faPhoneAlt as faPhoneAltThin,
    faPlay as faPlayThin,
    faPlayCircle as faPlayCircleThin,
    faPlus as faPlusThin,
    faPlusCircle as faPlusCircleThin,
    faPoundSign as faPoundSignThin,
    faPrint as faPrintThin,
    faQuestion as faQuestionThin,
    faQuestionCircle as faQuestionCircleThin,
    faRandom as faRandomThin,
    faReceipt as faReceiptThin,
    faRectangleTerminal as faRectangleTerminalThin,
    faRedo as faRedoThin,
    faRocket as faRocketThin,
    faUserShield as faUserShieldThin,
    faSave as faSaveThin,
    faSearch as faSearchThin,
    faServer as faServerThin,
    faShieldAlt as faShieldAltThin,
    faShieldCheck as faShieldCheckThin,
    faSigma as faSigmaThin,
    faSignIn as faSignInThin,
    faSignOut as faSignOutThin,
    faSitemap as faSitemapThin,
    faSkull as faSkullThin,
    faSlidersHSquare as faSlidersHSquareThin,
    faSpinner as faSpinnerThin,
    faSquare as faSquareThin,
    faStar as faStarThin,
    faStethoscope as faStethoscopeThin,
    faStop as faStopThin,
    faStopCircle as faStopCircleThin,
    faStopwatch as faStopwatchThin,
    faSun as faSunThin,
    faSync as faSyncThin,
    faTable as faTableThin,
    faTableLayout as faTableLayoutThin,
    faTag as faTagThin,
    faTags as faTagsThin,
    faTh as faThThin,
    faThLarge as faThLargeThin,
    faThumbsDown as faThumbsDownThin,
    faThumbsUp as faThumbsUpThin,
    faThumbtack as faThumbtackThin,
    faTimes as faTimesThin,
    faTimesCircle as faTimesCircleThin,
    faTimesHexagon as faTimesHexagonThin,
    faToolbox as faToolboxThin,
    faTools as faToolsThin,
    faTrashAlt as faTrashAltThin,
    faUndo as faUndoThin,
    faUniversity as faUniversityThin,
    faUnlink as faUnlinkThin,
    faUsdCircle as faUsdCircleThin,
    faUser as faUserThin,
    faUserCheck as faUserCheckThin,
    faUserCircle as faUserCircleThin,
    faUserClock as faUserClockThin,
    faUserFriends as faUserFriendsThin,
    faUsers as faUsersThin,
    faWandMagicSparkles as faWandMagicSparklesThin,
    faWindow as faWindowThin,
    faWrench as faWrenchThin
} from '@fortawesome/pro-thin-svg-icons';

// Register imported icons with the FA library to ensure they are available by name.
library.add(
    faAddressCard,
    faAddressCardLight,
    faAddressCardSolid,
    faAddressCardThin,
    faAddressCard,
    faAddressCardLight,
    faAddressCardSolid,
    faAddressCardThin,
    faAlignJustify,
    faAlignJustifyLight,
    faAlignJustifySolid,
    faAlignJustifyThin,
    faAnalytics,
    faAnalyticsLight,
    faAnalyticsSolid,
    faAnalyticsThin,
    faAngleDoubleDown,
    faAngleDoubleDownLight,
    faAngleDoubleDownSolid,
    faAngleDoubleDownThin,
    faAngleDoubleLeft,
    faAngleDoubleLeftLight,
    faAngleDoubleLeftSolid,
    faAngleDoubleLeftThin,
    faAngleDoubleRight,
    faAngleDoubleRightLight,
    faAngleDoubleRightSolid,
    faAngleDoubleRightThin,
    faAngleDoubleUp,
    faAngleDoubleUpLight,
    faAngleDoubleUpSolid,
    faAngleDoubleUpThin,
    faAngleDown,
    faAngleDownLight,
    faAngleDownSolid,
    faAngleDownThin,
    faAngleLeft,
    faAngleLeftLight,
    faAngleLeftSolid,
    faAngleLeftThin,
    faAngleRight,
    faAngleRightLight,
    faAngleRightSolid,
    faAngleRightThin,
    faAngleUp,
    faAngleUpLight,
    faAngleUpSolid,
    faAngleUpThin,
    faArrowDown,
    faArrowDownLight,
    faArrowDownSolid,
    faArrowDownThin,
    faArrowLeft,
    faArrowLeftLight,
    faArrowLeftSolid,
    faArrowLeftThin,
    faArrowRight,
    faArrowRightLight,
    faArrowRightSolid,
    faArrowRightThin,
    faArrowsH,
    faArrowsHLight,
    faArrowsHSolid,
    faArrowsHThin,
    faArrowsV,
    faArrowsVLight,
    faArrowsVSolid,
    faArrowsVThin,
    faArrowToBottom,
    faArrowToBottomLight,
    faArrowToBottomSolid,
    faArrowToBottomThin,
    faArrowToLeft,
    faArrowToLeftLight,
    faArrowToLeftSolid,
    faArrowToLeftThin,
    faArrowToRight,
    faArrowToRightLight,
    faArrowToRightSolid,
    faArrowToRightThin,
    faArrowToTop,
    faArrowToTopLight,
    faArrowToTopSolid,
    faArrowToTopThin,
    faArrowUp,
    faArrowUpLight,
    faArrowUpSolid,
    faArrowUpThin,
    faBalanceScale,
    faBalanceScaleLight,
    faBalanceScaleSolid,
    faBalanceScaleThin,
    faBalanceScaleLeft,
    faBalanceScaleLeftLight,
    faBalanceScaleLeftSolid,
    faBalanceScaleLeftThin,
    faBalanceScaleRight,
    faBalanceScaleRightLight,
    faBalanceScaleRightSolid,
    faBalanceScaleRightThin,
    faBan,
    faBanLight,
    faBanSolid,
    faBanThin,
    faBars,
    faBarsLight,
    faBarsSolid,
    faBarsThin,
    faBolt,
    faBoltLight,
    faBoltSolid,
    faBoltThin,
    faBook,
    faBookLight,
    faBookSolid,
    faBookThin,
    faBookmark,
    faBookmarkLight,
    faBookmarkSolid,
    faBookmarkThin,
    faBooks,
    faBooksLight,
    faBooksSolid,
    faBooksThin,
    faBox,
    faBoxLight,
    faBoxSolid,
    faBoxThin,
    faBoxFull,
    faBoxFullLight,
    faBoxFullSolid,
    faBoxFullThin,
    faBracketsCurly,
    faBracketsCurlyLight,
    faBracketsCurlySolid,
    faBracketsCurlyThin,
    faBreadSlice,
    faBreadSliceLight,
    faBreadSliceSolid,
    faBreadSliceThin,
    faBriefcase,
    faBriefcaseLight,
    faBriefcaseSolid,
    faBriefcaseThin,
    faBrowser,
    faBrowserLight,
    faBrowserSolid,
    faBrowserThin,
    faBuilding,
    faBuildingLight,
    faBuildingSolid,
    faBuildingThin,
    faBullhorn,
    faBullhornLight,
    faBullhornSolid,
    faBullhornThin,
    faBullseyeArrow,
    faBullseyeArrowLight,
    faBullseyeArrowSolid,
    faBullseyeArrowThin,
    faCalculator,
    faCalculatorLight,
    faCalculatorSolid,
    faCalculatorThin,
    faCalendarDay,
    faCalendarDayLight,
    faCalendarDaySolid,
    faCalendarDayThin,
    faCamera,
    faCameraLight,
    faCameraSolid,
    faCameraThin,
    faCaretLeft,
    faCaretLeftLight,
    faCaretLeftSolid,
    faCaretLeftThin,
    faCaretRight,
    faCaretRightLight,
    faCaretRightSolid,
    faCaretRightThin,
    faChartArea,
    faChartAreaLight,
    faChartAreaSolid,
    faChartAreaThin,
    faChartColumn,
    faChartColumnLight,
    faChartColumnSolid,
    faChartColumnThin,
    faChartLine,
    faChartLineLight,
    faChartLineSolid,
    faChartLineThin,
    faChartPie,
    faChartPieLight,
    faChartPieSolid,
    faChartPieThin,
    faChartTreeMap,
    faChartTreeMapLight,
    faChartTreeMapSolid,
    faChartTreeMapThin,
    faCheck,
    faCheckLight,
    faCheckSolid,
    faCheckThin,
    faCheckCircle,
    faCheckCircleLight,
    faCheckCircleSolid,
    faCheckCircleThin,
    faCheckSquare,
    faCheckSquareLight,
    faCheckSquareSolid,
    faCheckSquareThin,
    faChess,
    faChessLight,
    faChessSolid,
    faChessThin,
    faChessKnightAlt,
    faChessKnightAltLight,
    faChessKnightAltSolid,
    faChessKnightAltThin,
    faChevronDown,
    faChevronDownLight,
    faChevronDownSolid,
    faChevronDownThin,
    faChevronLeft,
    faChevronLeftLight,
    faChevronLeftSolid,
    faChevronLeftThin,
    faChevronRight,
    faChevronRightLight,
    faChevronRightSolid,
    faChevronRightThin,
    faChevronUp,
    faChevronUpLight,
    faChevronUpSolid,
    faChevronUpThin,
    faCircle,
    faCircleLight,
    faCircleSolid,
    faCircleThin,
    faClipboard,
    faClipboardLight,
    faClipboardSolid,
    faClipboardThin,
    faClock,
    faClockLight,
    faClockSolid,
    faClockThin,
    faCloudDownload,
    faCloudDownloadLight,
    faCloudDownloadSolid,
    faCloudDownloadThin,
    faCloudUpload,
    faCloudUploadLight,
    faCloudUploadSolid,
    faCloudUploadThin,
    faCode,
    faCodeLight,
    faCodeSolid,
    faCodeThin,
    faCog,
    faCogLight,
    faCogSolid,
    faCogThin,
    faCogs,
    faCogsLight,
    faCogsSolid,
    faCogsThin,
    faCommentDots,
    faCommentDotsLight,
    faCommentDotsSolid,
    faCommentDotsThin,
    faCompressAlt,
    faCompressAltLight,
    faCompressAltSolid,
    faCompressAltThin,
    faCopy,
    faCopyLight,
    faCopySolid,
    faCopyThin,
    faCrosshairs,
    faCrosshairsLight,
    faCrosshairsSolid,
    faCrosshairsThin,
    faCube,
    faCubeLight,
    faCubeSolid,
    faCubeThin,
    faDatabase,
    faDatabaseLight,
    faDatabaseSolid,
    faDatabaseThin,
    faDesktop,
    faDesktopLight,
    faDesktopSolid,
    faDesktopThin,
    faDollarSign,
    faDollarSignLight,
    faDollarSignSolid,
    faDollarSignThin,
    faArrowDownToBracket,
    faArrowDownToBracketLight,
    faArrowDownToBracketSolid,
    faArrowDownToBracketThin,
    faEdit,
    faEditLight,
    faEditSolid,
    faEditThin,
    faEllipsisH,
    faEllipsisHLight,
    faEllipsisHSolid,
    faEllipsisHThin,
    faEllipsisV,
    faEllipsisVLight,
    faEllipsisVSolid,
    faEllipsisVThin,
    faEnvelope,
    faEnvelopeLight,
    faEnvelopeSolid,
    faEnvelopeThin,
    faEquals,
    faEqualsLight,
    faEqualsSolid,
    faEqualsThin,
    faEuroSign,
    faEuroSignLight,
    faEuroSignSolid,
    faEuroSignThin,
    faExchange,
    faExchangeLight,
    faExchangeSolid,
    faExchangeThin,
    faExclamationCircle,
    faExclamationCircleLight,
    faExclamationCircleSolid,
    faExclamationCircleThin,
    faExclamationSquare,
    faExclamationSquareLight,
    faExclamationSquareSolid,
    faExclamationSquareThin,
    faExclamationTriangle,
    faExclamationTriangleLight,
    faExclamationTriangleSolid,
    faExclamationTriangleThin,
    faExpandAlt,
    faExpandAltLight,
    faExpandAltSolid,
    faExpandAltThin,
    faExternalLink,
    faExternalLinkLight,
    faExternalLinkSolid,
    faExternalLinkThin,
    faEye,
    faEyeLight,
    faEyeSolid,
    faEyeThin,
    faEyeSlash,
    faEyeSlashLight,
    faEyeSlashSolid,
    faEyeSlashThin,
    faFile,
    faFileLight,
    faFileSolid,
    faFileThin,
    faFileAlt,
    faFileAltLight,
    faFileAltSolid,
    faFileAltThin,
    faFileArchive,
    faFileArchiveLight,
    faFileArchiveSolid,
    faFileArchiveThin,
    faFileCertificate,
    faFileCertificateLight,
    faFileCertificateSolid,
    faFileCertificateThin,
    faFileChartColumn,
    faFileChartColumnLight,
    faFileChartColumnSolid,
    faFileChartColumnThin,
    faFileCsv,
    faFileCsvLight,
    faFileCsvSolid,
    faFileCsvThin,
    faFileExcel,
    faFileExcelLight,
    faFileExcelSolid,
    faFileExcelThin,
    faFileImage,
    faFileImageLight,
    faFileImageSolid,
    faFileImageThin,
    faFilePdf,
    faFilePdfLight,
    faFilePdfSolid,
    faFilePdfThin,
    faFilePowerpoint,
    faFilePowerpointLight,
    faFilePowerpointSolid,
    faFilePowerpointThin,
    faFileWord,
    faFileWordLight,
    faFileWordSolid,
    faFileWordThin,
    faFilter,
    faFilterLight,
    faFilterSolid,
    faFilterThin,
    faFilterSlash,
    faFilterSlashLight,
    faFilterSlashSolid,
    faFilterSlashThin,
    faFlag,
    faFlagLight,
    faFlagSolid,
    faFlagThin,
    faFlask,
    faFlaskLight,
    faFlaskSolid,
    faFlaskThin,
    faFolder,
    faFolderLight,
    faFolderSolid,
    faFolderThin,
    faFolderOpen,
    faFolderOpenLight,
    faFolderOpenSolid,
    faFolderOpenThin,
    faFunction,
    faFunctionLight,
    faFunctionSolid,
    faFunctionThin,
    faGift,
    faGiftLight,
    faGiftSolid,
    faGiftThin,
    faGlobe,
    faGlobeLight,
    faGlobeSolid,
    faGlobeThin,
    faGlobeAmericas,
    faGlobeAmericasLight,
    faGlobeAmericasSolid,
    faGlobeAmericasThin,
    faGraduationCap,
    faGraduationCapLight,
    faGraduationCapSolid,
    faGraduationCapThin,
    faGreaterThan,
    faGreaterThanLight,
    faGreaterThanSolid,
    faGreaterThanThin,
    faGreaterThanEqual,
    faGreaterThanEqualLight,
    faGreaterThanEqualSolid,
    faGreaterThanEqualThin,
    faGripHorizontal,
    faGripHorizontalLight,
    faGripHorizontalSolid,
    faGripHorizontalThin,
    faHandPaper,
    faHandPaperLight,
    faHandPaperSolid,
    faHandPaperThin,
    faHandPointUp,
    faHandPointUpLight,
    faHandPointUpSolid,
    faHandPointUpThin,
    faHandshake,
    faHandshakeLight,
    faHandshakeSolid,
    faHandshakeThin,
    faHeartRate,
    faHeartRateLight,
    faHeartRateSolid,
    faHeartRateThin,
    faHistory,
    faHistoryLight,
    faHistorySolid,
    faHistoryThin,
    faHome,
    faHomeLight,
    faHomeSolid,
    faHomeThin,
    faInbox,
    faInboxLight,
    faInboxSolid,
    faInboxThin,
    faIdBadge,
    faIdBadgeLight,
    faIdBadgeSolid,
    faIdBadgeThin,
    faIndustryAlt,
    faIndustryAltLight,
    faIndustryAltSolid,
    faIndustryAltThin,
    faInfoCircle,
    faInfoCircleLight,
    faInfoCircleSolid,
    faInfoCircleThin,
    faLessThan,
    faLessThanLight,
    faLessThanSolid,
    faLessThanThin,
    faLessThanEqual,
    faLessThanEqualLight,
    faLessThanEqualSolid,
    faLessThanEqualThin,
    faLink,
    faLinkLight,
    faLinkSolid,
    faLinkThin,
    faLock,
    faLockLight,
    faLockSolid,
    faLockThin,
    faLockOpen,
    faLockOpenLight,
    faLockOpenSolid,
    faLockOpenThin,
    faWandMagicSparkles,
    faWandMagicSparklesLight,
    faWandMagicSparklesSolid,
    faWandMagicSparklesThin,
    faMapMarkerAlt,
    faMapMarkerAltLight,
    faMapMarkerAltSolid,
    faMapMarkerAltThin,
    faMapSigns,
    faMapSignsLight,
    faMapSignsSolid,
    faMapSignsThin,
    faMask,
    faMaskLight,
    faMaskSolid,
    faMaskThin,
    faMemory,
    faMemoryLight,
    faMemorySolid,
    faMemoryThin,
    faMinusCircle,
    faMinusCircleLight,
    faMinusCircleSolid,
    faMinusCircleThin,
    faMobileScreen,
    faMobileScreenLight,
    faMobileScreenSolid,
    faMobileScreenThin,
    faMoon,
    faMoonLight,
    faMoonSolid,
    faMoonThin,
    faNewspaper,
    faNewspaperLight,
    faNewspaperSolid,
    faNewspaperThin,
    faNotEqual,
    faNotEqualLight,
    faNotEqualSolid,
    faNotEqualThin,
    faPaperclip,
    faPaperclipLight,
    faPaperclipSolid,
    faPaperclipThin,
    faPaste,
    faPasteLight,
    faPasteSolid,
    faPasteThin,
    faPause,
    faPauseLight,
    faPauseSolid,
    faPauseThin,
    faPauseCircle,
    faPauseCircleLight,
    faPauseCircleSolid,
    faPauseCircleThin,
    faPlay,
    faPlayLight,
    faPlaySolid,
    faPlayThin,
    faPhoneAlt,
    faPhoneAltLight,
    faPhoneAltSolid,
    faPhoneAltThin,
    faPlayCircle,
    faPlayCircleLight,
    faPlayCircleSolid,
    faPlayCircleThin,
    faPlus,
    faPlusLight,
    faPlusSolid,
    faPlusThin,
    faPlusCircle,
    faPlusCircleLight,
    faPlusCircleSolid,
    faPlusCircleThin,
    faPoundSign,
    faPoundSignLight,
    faPoundSignSolid,
    faPoundSignThin,
    faPrint,
    faPrintLight,
    faPrintSolid,
    faPrintThin,
    faQuestion,
    faQuestionLight,
    faQuestionSolid,
    faQuestionThin,
    faQuestionCircle,
    faQuestionCircleLight,
    faQuestionCircleSolid,
    faQuestionCircleThin,
    faRandom,
    faRandomLight,
    faRandomSolid,
    faRandomThin,
    faReceipt,
    faReceiptLight,
    faReceiptSolid,
    faReceiptThin,
    faRectangleTerminal,
    faRectangleTerminalLight,
    faRectangleTerminalSolid,
    faRectangleTerminalThin,
    faRedo,
    faRedoLight,
    faRedoSolid,
    faRedoThin,
    faRocket,
    faRocketLight,
    faRocketSolid,
    faRocketThin,
    faUserShield,
    faUserShieldLight,
    faUserShieldSolid,
    faUserShieldThin,
    faSave,
    faSaveLight,
    faSaveSolid,
    faSaveThin,
    faSearch,
    faSearchLight,
    faSearchSolid,
    faSearchThin,
    faServer,
    faServerLight,
    faServerSolid,
    faServerThin,
    faShieldAlt,
    faShieldAltLight,
    faShieldAltSolid,
    faShieldAltThin,
    faShieldCheck,
    faShieldCheckLight,
    faShieldCheckSolid,
    faShieldCheckThin,
    faSigma,
    faSigmaLight,
    faSigmaSolid,
    faSigmaThin,
    faSignIn,
    faSignInLight,
    faSignInSolid,
    faSignInThin,
    faSignOut,
    faSignOutLight,
    faSignOutSolid,
    faSignOutThin,
    faSitemap,
    faSitemapLight,
    faSitemapSolid,
    faSitemapThin,
    faSkull,
    faSkullLight,
    faSkullSolid,
    faSkullThin,
    faSlidersHSquare,
    faSlidersHSquareLight,
    faSlidersHSquareSolid,
    faSlidersHSquareThin,
    faSpinner,
    faSpinnerLight,
    faSpinnerSolid,
    faSpinnerThin,
    faSquare,
    faSquareLight,
    faSquareSolid,
    faSquareThin,
    faStar,
    faStarLight,
    faStarSolid,
    faStarThin,
    faStethoscope,
    faStethoscopeLight,
    faStethoscopeSolid,
    faStethoscopeThin,
    faStop,
    faStopLight,
    faStopSolid,
    faStopThin,
    faStopCircle,
    faStopCircleLight,
    faStopCircleSolid,
    faStopCircleThin,
    faStopwatch,
    faStopwatchLight,
    faStopwatchSolid,
    faStopwatchThin,
    faListTree,
    faListTreeLight,
    faListTreeSolid,
    faListTreeThin,
    faSun,
    faSunLight,
    faSunSolid,
    faSunThin,
    faSync,
    faSyncLight,
    faSyncSolid,
    faSyncThin,
    faTable,
    faTableLight,
    faTableSolid,
    faTableThin,
    faTableLayout,
    faTableLayoutLight,
    faTableLayoutSolid,
    faTableLayoutThin,
    faGaugeHigh,
    faGaugeHighLight,
    faGaugeHighSolid,
    faGaugeHighThin,
    faTag,
    faTagLight,
    faTagSolid,
    faTagThin,
    faTags,
    faTagsLight,
    faTagsSolid,
    faTagsThin,
    faTh,
    faThLight,
    faThSolid,
    faThThin,
    faThLarge,
    faThLargeLight,
    faThLargeSolid,
    faThLargeThin,
    faThumbsDown,
    faThumbsDownLight,
    faThumbsDownSolid,
    faThumbsDownThin,
    faThumbsUp,
    faThumbsUpLight,
    faThumbsUpSolid,
    faThumbsUpThin,
    faThumbtack,
    faThumbtackLight,
    faThumbtackSolid,
    faThumbtackThin,
    faTimes,
    faTimesLight,
    faTimesSolid,
    faTimesThin,
    faTimesCircle,
    faTimesCircleLight,
    faTimesCircleSolid,
    faTimesCircleThin,
    faTimesHexagon,
    faTimesHexagonLight,
    faTimesHexagonSolid,
    faTimesHexagonThin,
    faToolbox,
    faToolboxLight,
    faToolboxSolid,
    faToolboxThin,
    faTools,
    faToolsLight,
    faToolsSolid,
    faToolsThin,
    faTrashAlt,
    faTrashAltLight,
    faTrashAltSolid,
    faTrashAltThin,
    faUndo,
    faUndoLight,
    faUndoSolid,
    faUndoThin,
    faUniversity,
    faUniversityLight,
    faUniversitySolid,
    faUniversityThin,
    faUnlink,
    faUnlinkLight,
    faUnlinkSolid,
    faUnlinkThin,
    faArrowUpFromBracket,
    faArrowUpFromBracketLight,
    faArrowUpFromBracketSolid,
    faArrowUpFromBracketThin,
    faUsdCircle,
    faUsdCircleLight,
    faUsdCircleSolid,
    faUsdCircleThin,
    faUser,
    faUserLight,
    faUserSolid,
    faUserThin,
    faUserCheck,
    faUserCheckLight,
    faUserCheckSolid,
    faUserCheckThin,
    faUserCircle,
    faUserCircleLight,
    faUserCircleSolid,
    faUserCircleThin,
    faUserClock,
    faUserClockLight,
    faUserClockSolid,
    faUserClockThin,
    faUserFriends,
    faUserFriendsLight,
    faUserFriendsSolid,
    faUserFriendsThin,
    faUsers,
    faUsersLight,
    faUsersSolid,
    faUsersThin,
    faWindow,
    faWindowLight,
    faWindowSolid,
    faWindowThin,
    faWrench,
    faWrenchLight,
    faWrenchSolid,
    faWrenchThin
);
