/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2026 Extremely Heavy Industries Inc.
 */
import {escape, groupBy} from 'lodash';
import {fmtDuration} from './MarkdownReport';
import {fullName, type ReportFile, type ReportTest, type TestReport} from './TestReporter';

/**
 * Render a test report as a single, self-contained HTML page - no external assets, so it works
 * when opened from a downloaded CI artifact as well as from GitHub Pages.
 */
export function renderHtml(report: TestReport): string {
    const {totals, files, git} = report,
        passing = !totals.failed && !report.loadFailures && !report.unhandledErrors.length,
        pkgs = groupBy(files, it => it.pkg),
        status = passing
            ? `All ${fmtNum(totals.passed)} tests passing`
            : `${fmtNum(totals.failed + report.loadFailures)} failing`;

    const meta = [
        git.branch ? `<span>${escape(git.branch)}</span>` : null,
        git.sha ? link(commitUrl(report), `<code>${git.sha.slice(0, 8)}</code>`) : null,
        `<span>${new Date(report.timestamp).toUTCString()}</span>`,
        git.runUrl ? link(git.runUrl, 'View CI run') : null
    ];

    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hoist React Unit Tests</title>
<style>${CSS}</style>
</head>
<body class="${passing ? 'passing' : 'failing'}">
<header>
  <div class="wrap">
    <div class="brand">Hoist React <span>Unit Tests</span></div>
    <h1><span class="mark">${passing ? '✓' : '✗'}</span>${status}</h1>
    <div class="meta">${meta.filter(Boolean).join('<i>·</i>')}</div>
    <p class="intro">Unit tests for the <code>@xh/hoist</code> library, run on Vitest. Tests compile
    Hoist with the same SWC decorator settings apps use, and run its real services against an
    in-memory fake of the hoist-core server.</p>
  </div>
</header>
<main class="wrap">
  <section class="tiles">
    ${tile(fmtNum(totals.total), 'Tests')}
    ${tile(fmtNum(files.length), 'Spec files')}
    ${tile(fmtNum(Object.keys(pkgs).length), 'Packages')}
    ${tile(fmtDuration(report.duration), 'Duration')}
    ${totals.knownBugs ? tile(fmtNum(totals.knownBugs), 'Known bugs', 'bug') : ''}
    ${totals.failed ? tile(fmtNum(totals.failed), 'Failed', 'fail') : ''}
  </section>
  ${failuresSection(report)}
  <section class="tests">
    <div class="toolbar">
      <h2>Tests by package</h2>
      <input id="filter" type="search" placeholder="Filter tests..." autocomplete="off">
      <span id="matches"></span>
      <button id="toggle" type="button">Expand all</button>
    </div>
    ${Object.entries(pkgs)
        .map(([pkg, pkgFiles]) => packageSection(report, pkg, pkgFiles))
        .join('\n')}
  </section>
</main>
<footer class="wrap">Generated by hoist-react's test reporter (test/report) · ${link(
        'https://github.com/xh/hoist-react/blob/develop/docs/unit-testing.md',
        'About these tests'
    )}</footer>
<script>${SCRIPT}</script>
</body>
</html>
`;
}

//------------------------
// Sections
//------------------------
function failuresSection(report: TestReport): string {
    const items = [];
    report.files.forEach(file => {
        file.loadErrors.forEach(msg =>
            items.push(
                `<div class="failure"><h3>💥 Could not run ${escape(file.path)}</h3>${pre(msg)}</div>`
            )
        );
        file.tests
            .filter(it => it.state === 'failed')
            .forEach(test => {
                const [err] = test.errors;
                items.push(`<div class="failure">
                    <h3>✗ ${escape(fullName(test))}</h3>
                    <div class="where">${fileLink(report, file, err?.line ?? test.line)}</div>
                    ${err ? pre(err.message) : ''}
                    ${err?.diff ? diffPre(err.diff) : ''}
                </div>`);
            });
    });
    report.unhandledErrors.forEach(msg =>
        items.push(`<div class="failure"><h3>💥 Unhandled error</h3>${pre(msg)}</div>`)
    );
    return items.length
        ? `<section class="failures"><h2>Failures</h2>${items.join('')}</section>`
        : '';
}

function packageSection(report: TestReport, pkg: string, files: ReportFile[]): string {
    const tests = files.flatMap(it => it.tests),
        failed =
            tests.filter(it => it.state === 'failed').length +
            files.filter(it => it.loadErrors.length).length,
        passPct = tests.length ? ((tests.length - failed) / tests.length) * 100 : 100;

    return `<details class="pkg"${failed ? ' open' : ''}>
  <summary>
    <span class="pkg-name">${escape(pkg)}</span>
    <span class="bar"><span style="width:${passPct.toFixed(1)}%"></span></span>
    <span class="count">${plural(files.length, 'file')} · ${plural(tests.length, 'test')}${failed ? ` · <b class="fail">${failed} failed</b>` : ''}</span>
  </summary>
  ${files.map(file => fileSection(report, file)).join('\n')}
</details>`;
}

function fileSection(report: TestReport, file: ReportFile): string {
    const failed = file.tests.some(it => it.state === 'failed') || file.loadErrors.length;
    return `<details class="file"${failed ? ' open' : ''}>
  <summary>${escape(file.path.split('/').pop())}<span class="count">${file.tests.length}</span>${fileLink(report, file, null, '↗')}</summary>
  ${renderTree(report, file, buildTree(file.tests))}
</details>`;
}

//------------------------
// Describe-block tree
//------------------------
interface TreeNode {
    suites: Map<string, TreeNode>;
    tests: ReportTest[];
}

function buildTree(tests: ReportTest[]): TreeNode {
    const root: TreeNode = {suites: new Map(), tests: []};
    tests.forEach(test => {
        let node = root;
        test.suites.forEach(name => {
            if (!node.suites.has(name)) node.suites.set(name, {suites: new Map(), tests: []});
            node = node.suites.get(name);
        });
        node.tests.push(test);
    });
    return root;
}

function renderTree(report: TestReport, file: ReportFile, node: TreeNode): string {
    const suites = [...node.suites.entries()].map(
            ([name, child]) =>
                `<li class="suite"><span class="suite-name">${escape(name)}</span>${renderTree(report, file, child)}</li>`
        ),
        tests = node.tests.map(test => {
            const cls = test.state === 'passed' && test.knownBug ? 'bug' : test.state,
                icon = {passed: '✓', failed: '✗', skipped: '–', bug: '🐞'}[cls],
                title = test.knownBug ? ' title="Known bug - expected to fail until fixed"' : '';
            return `<li class="test ${cls}"${title}><span class="icon">${icon}</span>${escape(test.name)}<span class="dur">${fmtDuration(test.duration)}</span></li>`;
        });
    return `<ul>${[...tests, ...suites].join('')}</ul>`;
}

//------------------------
// Helpers
//------------------------
function tile(value: string, label: string, cls = ''): string {
    return `<div class="tile ${cls}"><div class="value">${value}</div><div class="label">${label}</div></div>`;
}

function link(href: string, html: string): string {
    return `<a href="${escape(href)}" target="_blank" rel="noopener">${html}</a>`;
}

function fileLink(report: TestReport, file: ReportFile, line: number, label?: string): string {
    const text = label ?? escape(line ? `${file.path}:${line}` : file.path),
        {blobUrl} = report.git;
    if (!blobUrl) return label ? '' : `<code>${text}</code>`;
    return link(
        `${blobUrl}/${file.path}${line ? `#L${line}` : ''}`,
        label ? text : `<code>${text}</code>`
    );
}

function commitUrl(report: TestReport): string {
    const {blobUrl, sha} = report.git;
    return blobUrl ? blobUrl.replace(/\/blob\/.*$/, `/commit/${sha}`) : null;
}

function pre(text: string): string {
    return `<pre>${escape(text.trim())}</pre>`;
}

function diffPre(diff: string): string {
    const lines = diff
        .trim()
        .split('\n')
        .map(line => {
            const cls = line.startsWith('+') ? 'add' : line.startsWith('-') ? 'del' : '';
            return `<span class="${cls}">${escape(line)}</span>`;
        });
    return `<pre class="diff">${lines.join('\n')}</pre>`;
}

function fmtNum(n: number): string {
    return n.toLocaleString('en-US');
}

function plural(n: number, noun: string): string {
    return `${fmtNum(n)} ${noun}${n === 1 ? '' : 's'}`;
}

//------------------------
// Assets
//------------------------
const CSS = `
:root {
  --bg: #f6f7f9; --panel: #fff; --text: #1d232b; --muted: #687384; --border: #e2e6eb;
  --pass: #1f8f4e; --fail: #c93a3a; --bug: #b7791f; --accent: #2f6fb3;
  --header-pass: linear-gradient(120deg, #156b3b, #1f8f4e); --header-fail: linear-gradient(120deg, #8f1f1f, #c93a3a);
  --code-bg: #f1f3f6;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #12161b; --panel: #1a2027; --text: #e3e8ee; --muted: #8b96a5; --border: #2a323c;
    --pass: #3fb871; --fail: #ef6b6b; --bug: #e0a84a; --accent: #6aa6e8; --code-bg: #10151a;
  }
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--text);
  font: 14px/1.5 -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, Roboto, sans-serif; }
.wrap { max-width: 1080px; margin: 0 auto; padding: 0 16px; }
a { color: var(--accent); text-decoration: none; } a:hover { text-decoration: underline; }
code, pre { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12.5px; }
header { color: #fff; padding: 28px 0 32px; background: var(--header-pass); }
body.failing header { background: var(--header-fail); }
header a { color: #fff; text-decoration: underline; text-decoration-color: rgba(255,255,255,.5); }
.brand { font-size: 13px; letter-spacing: .08em; text-transform: uppercase; opacity: .85; font-weight: 600; }
.brand span { font-weight: 400; }
h1 { margin: 6px 0 8px; font-size: 30px; font-weight: 650; display: flex; align-items: center; gap: 12px; }
.mark { display: inline-grid; place-items: center; width: 40px; height: 40px; border-radius: 50%;
  background: rgba(255,255,255,.2); font-size: 22px; }
.meta { opacity: .9; font-size: 13px; display: flex; flex-wrap: wrap; gap: 6px; }
.meta i { font-style: normal; opacity: .6; }
.intro { margin: 14px 0 0; max-width: 720px; font-size: 13px; opacity: .85; }
.intro code { background: rgba(255,255,255,.15); padding: 0 4px; border-radius: 3px; }
.toolbar button { margin-left: auto; padding: 6px 12px; border-radius: 8px; cursor: pointer; font: inherit;
  font-size: 12px; border: 1px solid var(--border); background: var(--panel); color: var(--text); }
.meta code { background: rgba(255,255,255,.15); padding: 1px 6px; border-radius: 4px; }
.tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin: -18px 0 24px; }
.tile { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 14px 16px;
  box-shadow: 0 1px 2px rgba(0,0,0,.05); }
.tile .value { font-size: 26px; font-weight: 650; font-variant-numeric: tabular-nums; }
.tile .label { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .05em; }
.tile.fail .value { color: var(--fail); } .tile.bug .value { color: var(--bug); }
h2 { font-size: 16px; margin: 0; }
section { margin-bottom: 28px; }
.failures h2 { color: var(--fail); margin-bottom: 10px; }
.failure { background: var(--panel); border: 1px solid var(--border); border-left: 4px solid var(--fail);
  border-radius: 8px; padding: 12px 16px; margin-bottom: 10px; overflow: hidden; }
.failure h3 { margin: 0 0 4px; font-size: 14px; }
.where { font-size: 12px; margin-bottom: 8px; }
pre { background: var(--code-bg); border-radius: 6px; padding: 10px 12px; overflow-x: auto; margin: 6px 0 0;
  white-space: pre-wrap; word-break: break-word; }
.diff .add { color: var(--pass); } .diff .del { color: var(--fail); }
.toolbar { display: flex; align-items: center; gap: 12px; margin-bottom: 10px; flex-wrap: wrap; }
.toolbar input { flex: 1; min-width: 200px; max-width: 360px; padding: 7px 12px; border-radius: 8px;
  border: 1px solid var(--border); background: var(--panel); color: var(--text); font: inherit; }
#matches { color: var(--muted); font-size: 12px; }
details.pkg { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; margin-bottom: 8px; }
details > summary { cursor: pointer; list-style: none; }
details > summary::-webkit-details-marker { display: none; }
.pkg > summary { display: flex; align-items: center; gap: 14px; padding: 12px 16px; }
.pkg > summary::before, .file > summary::before { content: '▸'; color: var(--muted); transition: transform .15s; }
.pkg[open] > summary::before, .file[open] > summary::before { transform: rotate(90deg); }
.pkg-name { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-weight: 600; min-width: 160px; }
.bar { flex: 1; height: 6px; border-radius: 3px; background: var(--fail); overflow: hidden; max-width: 320px; }
.bar span { display: block; height: 100%; background: var(--pass); }
.count { color: var(--muted); font-size: 12px; margin-left: auto; }
.count b.fail { color: var(--fail); }
details.file { border-top: 1px solid var(--border); }
.file > summary { display: flex; align-items: center; gap: 10px; padding: 8px 16px 8px 36px; font-weight: 500; }
.file > summary .count { margin-left: 0; background: var(--code-bg); padding: 0 7px; border-radius: 10px; }
.file > summary a { margin-left: auto; font-size: 12px; }
.file ul { list-style: none; margin: 0; padding: 0 0 0 18px; }
.file > ul { padding: 0 16px 10px 52px; }
.suite-name { display: block; font-weight: 600; margin-top: 6px; }
.test { display: flex; gap: 8px; align-items: baseline; padding: 1px 0; }
.test .icon { width: 16px; flex: none; text-align: center; font-weight: 700; }
.test.passed .icon { color: var(--pass); } .test.failed { color: var(--fail); } .test.skipped { color: var(--muted); }
.test .dur { margin-left: auto; color: var(--muted); font-size: 11px; padding-left: 12px; font-variant-numeric: tabular-nums; }
.hidden { display: none !important; }
footer { color: var(--muted); font-size: 12px; padding: 8px 16px 32px; }
`;

// Filter tests by name - hide non-matching tests, then any suite, file, or package left empty.
const SCRIPT = `
const input = document.getElementById('filter'), matches = document.getElementById('matches');
input.addEventListener('input', () => {
  const q = input.value.trim().toLowerCase();
  let n = 0;
  document.querySelectorAll('li.test').forEach(li => {
    const path = [li.textContent];
    for (let p = li.parentElement.closest('li.suite'); p; p = p.parentElement.closest('li.suite'))
      path.push(p.querySelector('.suite-name').textContent);
    const hit = !q || path.join(' ').toLowerCase().includes(q);
    li.classList.toggle('hidden', !hit);
    if (hit) n++;
  });
  const prune = sel => document.querySelectorAll(sel).forEach(el =>
    el.classList.toggle('hidden', !!q && !el.querySelector('li.test:not(.hidden)')));
  prune('li.suite'); prune('details.file'); prune('details.pkg');
  if (q) document.querySelectorAll('details.pkg:not(.hidden), details.file:not(.hidden)').forEach(d => d.open = true);
  matches.textContent = q ? n + ' matching tests' : '';
});
const toggle = document.getElementById('toggle');
toggle.addEventListener('click', () => {
  const open = toggle.textContent === 'Expand all';
  document.querySelectorAll('details.pkg, details.file').forEach(d => d.open = open);
  toggle.textContent = open ? 'Collapse all' : 'Expand all';
});
`;
