/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2026 Extremely Heavy Industries Inc.
 */

import type {StoreRecord} from '@xh/hoist/data';
import type {BaseRow} from '../row/BaseRow';
import {ExposedLeafRow, type LeafRow} from '../row/LeafRow';
import type {ParentRow} from '../row/ParentRow';
import type {View} from '../View';

/**
 * Cache of the BaseRows generated by a View, allowing rows - along with their published data
 * objects and `cubeRowDigest` stamps - to be reused across regenerations of the View's results.
 *
 * A cached row is reused only when its published data can be made identical to that of a
 * from-scratch rebuild: leaves must be backed by the same (immutable) cube StoreRecord and match
 * the view's current exposed/hidden leaf class, while parents recompute in place as needed - see
 * {@link ParentRow.reuse}, which owns that contract. Digests bump only for values that actually
 * changed, letting connected stores - which read that stamp via a View-installed reuse digest -
 * skip record rebuilds for unchanged rows. Bucket stamps, `lockFn` and `omitFn` are re-derived
 * for all rows on every generation and need no constraint.
 *
 * Entries not requested by a generation are retained for later reuse - e.g. leaves for records
 * currently excluded by filter, ready should the filter widen again. Two bounds apply: parents
 * orphaned by a grouping change are evicted at the end of the generation that orphaned them
 * (their live-record children would otherwise keep them cached for the life of the view), and a
 * sweep drops rows whose cube records have been removed or replaced whenever the cache outgrows
 * the rows in current use by 50%+.
 *
 * @internal
 */
export class RowCache {
    private view: View;
    private rows = new Map<string, BaseRow>();
    private exposedLeaves = false;
    private sweptAsOf: number = null;
    private genStartDigest = 0;
    private evictUnusedParents = false;
    private usedParents: Set<BaseRow> = null;

    // Stats for the current generation - logged by endGeneration()
    private reused = 0;
    private rebuilt = 0;
    private created = 0;
    private evicted = 0;
    private removed = 0;
    private sweepTime = 0;

    constructor(view: View) {
        this.view = view;
    }

    get size(): number {
        return this.rows.size;
    }

    get(id: string): BaseRow {
        return this.rows.get(id);
    }

    /**
     * Return the cached row for id if it satisfies the reuse invariant, otherwise build via
     * `fn` and cache the result. Leaves validate against `record`; parents delegate to
     * {@link ParentRow.reuse}, which recomputes in place as needed.
     */
    getOrCreate<T extends BaseRow>(
        id: string,
        children: BaseRow[],
        fn: () => T,
        record?: StoreRecord
    ): T {
        let ret = this.rows.get(id);
        if (ret) {
            if (ret.isLeaf) {
                if (
                    (ret as LeafRow).cubeRecord === record &&
                    ret instanceof ExposedLeafRow === this.exposedLeaves
                ) {
                    this.reused++;
                    return ret as T;
                }
            } else if ((ret as ParentRow).reuse(children, this.genStartDigest)) {
                this.usedParents?.add(ret);
                this.reused++;
                return ret as T;
            }
            this.rebuilt++;
        } else {
            this.created++;
        }
        ret = fn();
        if (!ret.isLeaf) this.usedParents?.add(ret);
        this.rows.set(id, ret);
        return ret as T;
    }

    beginGeneration() {
        const {view} = this;
        this.genStartDigest = view._rowDigest;
        this.usedParents = this.evictUnusedParents ? new Set() : null;
        this.exposedLeaves = view.exposesLeaves;
        this.reused = this.rebuilt = this.created = 0;
        this.evicted = this.removed = this.sweepTime = 0;
    }

    endGeneration() {
        if (this.evictUnusedParents) {
            this.evictUnusedParents = false;
            this.doEvictUnusedParents();
            this.usedParents = null;
        }
        this.sweep();
        this.view.logDebug(
            `Generated rows: reused=${this.reused} rebuilt=${this.rebuilt} ` +
                `created=${this.created} cached=${this.size} ` +
                `evicted=${this.evicted} removed=${this.removed} ` +
                `sweepTime=${this.sweepTime.toFixed(1)}ms`
        );
    }

    /**
     * Request eviction of any parent rows not used by the coming generation, at its end. Called
     * ahead of a query change that alters the grouping - see View.pruneCacheForQueryChange.
     */
    evictUnusedParentsAtGenerationEnd() {
        this.evictUnusedParents = true;
    }

    clear() {
        this.rows.clear();
        this.evictUnusedParents = false;
    }

    /**
     * Remove all parent (aggregate/bucket) rows, and null the parent pointers of the retained
     * leaves - every pointer is dead once all parents are dropped, and would otherwise pin the
     * dead chains in memory.
     */
    removeParentRows() {
        const {rows} = this;
        rows.forEach((row, id) => {
            if (row.isLeaf) {
                row.parent = null;
            } else {
                rows.delete(id);
            }
        });
    }

    // Drop parents orphaned by a grouping change - each distinct grouping would otherwise
    // accumulate a cached parent set for the life of the view, as live-record children keep such
    // parents from ever sweeping. Then null dangling parent pointers on retained rows, so
    // evicted chains are not pinned in memory. Filter-dormant parents are retained across
    // filter-only changes (which never trigger this pass) and are bounded at one full-data
    // tree's worth; any evicted here alongside the orphans (their subtree filtered out during a
    // regroup) simply rebuild if the filter widens again.
    private doEvictUnusedParents() {
        const {rows, usedParents} = this;
        rows.forEach((row, id) => {
            if (!row.isLeaf && !usedParents.has(row)) {
                rows.delete(id);
                this.evicted++;
            }
        });
        if (!this.evicted) return;
        rows.forEach(row => {
            const {parent} = row;
            if (parent && rows.get(parent.id) !== parent) row.parent = null;
        });
    }

    // Drop rows whose underlying cube records have been removed or replaced. Skipped unless the
    // cache has outgrown the generation's live rows by 50%+ and cube data has changed since the
    // last sweep - rows can only die with their records.
    private sweep() {
        const live = this.reused + this.rebuilt + this.created,
            asOf = this.view.cube.lastUpdated;
        if (asOf === this.sweptAsOf || this.size <= 1.5 * live) return;

        const start = performance.now(),
            {rows} = this,
            {store} = this.view.cube,
            memo = new Map<BaseRow, boolean>(),
            startSize = rows.size;

        const isRetained = (row: BaseRow): boolean => {
            let ret = memo.get(row);
            if (ret === undefined) {
                ret = row.isLeaf
                    ? store.getById((row as LeafRow).cubeRecordId) === (row as LeafRow).cubeRecord
                    : !!row.children?.every(it => rows.get(it.id) === it && isRetained(it));
                memo.set(row, ret);
            }
            return ret;
        };

        rows.forEach((row, id) => {
            if (!isRetained(row)) rows.delete(id);
        });

        this.sweptAsOf = asOf;
        this.removed = startSize - rows.size;
        this.sweepTime = performance.now() - start;
    }
}
