/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2026 Extremely Heavy Industries Inc.
 */

import type {StoreRecord} from '@xh/hoist/data';
import {shallowEqualArrays} from '@xh/hoist/utils/impl';
import type {BaseRow} from '../row/BaseRow';
import type {LeafRow} from '../row/LeafRow';
import type {View} from '../View';

/**
 * Cache of the BaseRows generated by a View, allowing rows - along with their published data
 * objects and `cubeRowVersion` stamps - to be reused across regenerations of the View's results.
 *
 * Reuse invariant: a cached row is returned only when it would be recreated identically - a leaf
 * must be backed by the same (immutable) cube StoreRecord, an aggregate/bucket by an identical
 * array of child rows. Any data change therefore rebuilds the changed row and its ancestor chain
 * while all other rows carry over, and a stale entry can never serve stale data - at worst it
 * misses and is rebuilt. Reused rows keep their `cubeRowVersion`, letting connected stores with
 * `reuseRecords: 'cubeRowVersion'` skip record rebuilds for them.
 *
 * Reuse is gated on every input to a row's published data being intrinsic or re-derived:
 * aggregates declare that their inputs are their children
 * ({@link Aggregator.dependsOnChildrenOnly}), while bucket stamps, `lockFn` and `omitFn` are
 * re-evaluated for all rows on every generation (see `BaseRow.getVisibleDatas`) and so need no
 * constraint. `canAggregateFn` runs only at row construction and must be pure in its inputs.
 *
 * Retention: entries not requested by a generation are retained for potential later reuse - e.g.
 * leaves for records currently excluded by filter, ready should the filter widen again. To bound
 * memory, the cache sweeps when it grows well past its post-sweep baseline, dropping exactly the
 * entries that can no longer satisfy the reuse invariant. Since a live cache entry only ever
 * references records also retained by its View and Cube, this delays record collection by at
 * most one sweep cycle.
 *
 * @internal
 */
export class RowCache {
    private view: View;
    private rows = new Map<string, BaseRow>();
    // Size after the last sweep/reset - growth beyond this signals unreusable entries piling up.
    private sweepBaseline = 0;

    // Stats for the current generation, reset by noteGeneration.
    reused = 0;
    rebuilt = 0;
    created = 0;
    // Entries dropped by the most recent sweep.
    swept = 0;

    constructor(view: View) {
        this.view = view;
    }

    get size(): number {
        return this.rows.size;
    }

    get(id: string): BaseRow {
        return this.rows.get(id);
    }

    /**
     * Return the cached row for id if it satisfies the reuse invariant, otherwise build via
     * `fn` and cache the result. Leaves validate against `record`, other rows against `children`.
     */
    getOrCreate<T extends BaseRow>(
        id: string,
        children: BaseRow[],
        fn: () => T,
        record?: StoreRecord
    ): T {
        let ret = this.rows.get(id);
        if (ret) {
            if (
                ret.isLeaf
                    ? (ret as LeafRow).cubeRecord === record
                    : shallowEqualArrays(ret.children, children)
            ) {
                this.reused++;
                return ret as T;
            }
            this.rebuilt++;
        } else {
            this.created++;
        }
        ret = fn();
        this.rows.set(id, ret);
        return ret as T;
    }

    /** Mark the start of a generation - resets stats and sweeps if the cache has grown stale. */
    noteGeneration() {
        this.reused = this.rebuilt = this.created = 0;

        // Growth-triggered amortization: replaced records/rows overwrite their entries in place,
        // so size grows only as ids/paths disappear from results. Steady-state views never sweep.
        const {size, sweepBaseline} = this;
        if (!sweepBaseline) {
            this.sweepBaseline = size;
        } else if (size > 1.5 * sweepBaseline + 1000) {
            this.sweep();
        }
    }

    clear() {
        this.rows.clear();
        this.sweepBaseline = 0;
    }

    // Drop entries that can no longer satisfy the reuse invariant, evaluated transitively: a
    // leaf whose source record is gone from the cube can never validate again, nor can any row
    // with a dropped/replaced descendant. Rows over intact subtrees are retained - e.g. groups
    // currently filtered out in full, reusable verbatim (aggregation skipped) on filter widen.
    private sweep() {
        const {rows} = this,
            {store} = this.view.cube,
            memo = new Map<BaseRow, boolean>(),
            startSize = rows.size;

        const isRetained = (row: BaseRow): boolean => {
            let ret = memo.get(row);
            if (ret === undefined) {
                ret = row.isLeaf
                    ? store.getById((row as LeafRow).cubeRecordId) === (row as LeafRow).cubeRecord
                    : !!row.children?.every(it => rows.get(it.id) === it && isRetained(it));
                memo.set(row, ret);
            }
            return ret;
        };

        rows.forEach((row, id) => {
            if (!isRetained(row)) rows.delete(id);
        });

        this.swept = startSize - rows.size;
        this.sweepBaseline = rows.size;
    }
}
