/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2026 Extremely Heavy Industries Inc.
 */

import {PlainObject} from '@xh/hoist/core';
import {Field, Store, StoreConfig, StoreRecord} from '@xh/hoist/data';
import {throwIf} from '@xh/hoist/utils/js';
import {isEmpty} from 'lodash';
import {VIEW_ROW_DATA_FIELDS, ViewRowData} from './ViewRowData';
import {
    buildPivotLattice,
    CHILD_KIND_LEAF,
    discoverPivotPaths,
    PATH_DELIMITER,
    pivotCellFieldName,
    type PivotLatticeResult,
    type PivotPathDiscoveryResult,
    type PivotPathSpec
} from './impl/PivotLattice';
import {PivotRowDataGenerator} from './impl/PivotRowDataGenerator';
import {CubeField} from './CubeField';
import {PivotCellField, PivotPath} from './PivotPath';
import {PivotQuery, PivotQueryConfig} from './PivotQuery';
import {BaseRow} from './row/BaseRow';
import {LeafRow} from './row/LeafRow';
import {PivotCellRow} from './row/PivotCellRow';
import {View, ViewConfig, ViewResult} from './View';

export interface PivotViewResult extends ViewResult {
    /**
     * Pivot path tree, top-level paths first with nested `children`. Identity-stable while the pivot
     * structure is unchanged - track it to decide whether to rebuild columns.
     */
    paths: PivotPath[];

    /**
     * One entry per (path, value field), including the root-path row totals. Identity-stable with
     * `paths` - track it to decide whether to re-declare Store fields. Note both move on a
     * `valueFields`-only change, even though the path tree itself is structurally unchanged.
     */
    cellFields: PivotCellField[];
}

/**
 * Configuration for {@link PivotView.createStore}. Accepts the full {@link StoreConfig} surface,
 * defaulting `loadTreeData` and `projectionOnly` to true.
 */
export interface PivotViewStoreConfig extends StoreConfig {
    /**
     * True to register the new Store for live updates from this view. The *caller* owns the store
     * and must call {@link PivotView.disconnectStore} when done with it. False (default) to declare
     * fields and load once from the current result, then never again.
     */
    connect?: boolean;
}

/**
 * A {@link View} that additionally slices its measures across a pivot axis, producing a compact
 * table of `(group row, pivot path)` cells alongside the usual row hierarchy.
 *
 * Create via {@link Cube.createPivotView}. Cell values arrive as flat synthetic fields on the
 * published row data, named per {@link PivotViewResult.cellFields} - so they are ordinary Store
 * fields, and work with grid column filters, Excel export, and inline editing.
 *
 * The row hierarchy and the pivot hierarchy are orthogonal: every node of the row hierarchy carries
 * its own pivot subtree of {@link PivotCellRow}s. Those are real rows in the aggregation network, so
 * every aggregator works unmodified and ticks propagate incrementally, but they never enter the
 * visible tree or reach a connected Store.
 *
 * @see PivotQuery
 * @mcpHint live or snapshot pivoted view of aggregated Cube data
 */
export class PivotView extends View {
    /** Separator between pivot path segments, and between a path key and its value field. */
    static PATH_DELIMITER = PATH_DELIMITER;

    declare query: PivotQuery;
    declare result: PivotViewResult;

    // Implementation - declared, never initialized. Field initializers on a View subclass would run
    // *after* super()'s constructor-time fullUpdate() and wipe everything generated by it.
    declare protected _allPaths: PivotPath[];
    declare protected _pathKeys: string[];
    declare protected _pathLabels: string[];
    declare protected _valueFieldNames: string[];
    declare protected _paths: PivotPath[];
    /** Published cell fields - also read by `PivotRowDataGenerator` to shape exposed leaves. */
    declare _cellFields: PivotCellField[];
    /** Keyed on path *identity*, so a cell can never resolve names for a path it no longer holds. */
    declare protected _cellFieldNames: Map<PivotPath, string[]>;
    /** Index of each path within `_allPaths` - what an exposed leaf's `_pivotPathIdx` names. */
    declare _pathIdx: Map<PivotPath, number>;
    /** This generation's path discovery, run ahead of row generation - see `discoverPaths`. */
    declare protected _discovery: PivotPathDiscoveryResult;
    declare protected _cellRows: PivotCellRow[];
    /** Cell fields last declared on each store, by identity - the structural-change signal. */
    declare protected _syncedCellFields: WeakMap<Store, PivotCellField[]>;

    // Aggregation field lists for cell rows, in the shape View maintains per depth for group rows -
    // see PivotCellRow. Derived on each build, as `updateQuery` can change `valueFields`.
    declare _cellAggFields: CubeField[];
    declare _cellAggFieldNames: Set<string>;
    declare _cellCanAggregateFnFields: CubeField[];
    declare _cellComplexAggFields: CubeField[];

    /** @internal - applications should use {@link Cube.createPivotView} */
    constructor(config: ViewConfig) {
        super(config);
    }

    /**
     * As per {@link View.updateQuery}, widened to the pivot members - without this override
     * `pivotDimensions` and `valueFields` are unreachable from an object literal, including the
     * documented case of emptying `pivotDimensions` to degenerate to plain View behavior.
     */
    override updateQuery(overrides: Partial<PivotQueryConfig>) {
        super.updateQuery(overrides);
    }

    /**
     * Create a Store shaped for this view's results - a Field per {@link ViewRowData} member, per
     * query field, and per {@link PivotViewResult.cellFields} entry, kept in sync as the pivot
     * structure changes.
     *
     * A convenience factory, not a claim of ownership: the *caller* owns the returned Store, and a
     * caller passing `connect: true` must call {@link disconnectStore} from its own `destroy()`.
     * (`View.destroy` unregisters itself from its Cube only because there the registered object is
     * the owned one.)
     */
    createStore(config?: PivotViewStoreConfig): Store {
        const {connect = false, fields = [], ...rest} = config ?? {};

        const store = new Store({
            loadTreeData: true,
            projectionOnly: true,
            xhName: this.childXhName('store'),
            ...rest,
            fields: [...VIEW_ROW_DATA_FIELDS, ...this.fields, ...fields]
        });

        // Run `parseStores` either way - it installs the row digest and rejects a conflicting one,
        // and an unconnected store still loads from this view. Adopt the result only when
        // connecting; without the digest it would fall back to per-field value comparison, which a
        // pivot store pays for across every cell field.
        const stores = this.parseStores([...this.stores, store]);
        if (connect) this.stores = stores;

        this.syncStore(store);
        this.loadStore(store);

        return store;
    }

    /** Stop loading the given Store from this view. Callers of {@link createStore} own this call. */
    disconnectStore(store: Store) {
        this.stores = this.stores.filter(it => it !== store);
    }

    //------------------------
    // Implementation
    //------------------------
    protected override createRowDataGenerator(): PivotRowDataGenerator {
        return new PivotRowDataGenerator(this);
    }

    private get pivotRowDataGenerator(): PivotRowDataGenerator {
        return this._rowDataGenerator as PivotRowDataGenerator;
    }

    /**
     * Create the data object for a cell row.
     * @internal
     */
    newCellRowData(): PlainObject {
        const ret = this.pivotRowDataGenerator.newCellRowData();
        this.assignDigest(ret as ViewRowData);
        return ret;
    }

    protected override generateRows() {
        this.discoverPaths();
        super.generateRows();
        this.generateCells(this._records.list);
    }

    /**
     * Discover the pivot path tree and publish the cell fields it implies, ahead of row generation.
     *
     * Runs *before* `super.generateRows()` because the exposed-leaf class is built from the cell
     * fields and leaves are minted during that call. Discovery needs only the filtered records and
     * the pivot dimension names - never the row tree - so nothing forces it to wait. Only the
     * lattice needs groups, and that stays in `generateCells`.
     */
    private discoverPaths() {
        const {query} = this;
        if (query.isPivoted) {
            this._discovery = discoverPivotPaths(this._records.list, query.pivotDimensionNames, {
                emptyPathLabel: query.emptyPathLabel,
                maxPivotPaths: query.maxPivotPaths
            });
            this.syncPaths(this._discovery.paths);
        } else {
            this._discovery = null;
            this.clearCells();
        }

        this.pivotRowDataGenerator.onCellFieldsChange();
    }

    protected override createResult(): PivotViewResult {
        return {
            ...super.createResult(),
            paths: this._paths ?? [],
            cellFields: this._cellFields ?? []
        };
    }

    protected override loadStores() {
        this.stores.forEach(store => this.syncStore(store));
        super.loadStores();
    }

    /**
     * Declare a Field on `store` for every current cell field, and mirror `includeRoot` onto its
     * `loadRootAsSummary` - `loadStores` publishes exactly the one root node carrying `children`
     * that flag expects.
     *
     * Done here rather than from a consumer's reaction on `result` because `fullUpdate` assigns
     * `result` *last*: a reaction cannot declare fields until after the load has already run against
     * the outgoing set, which under `projectionOnly` builds records against the wrong declared
     * fields rather than merely rendering late. Plain Views need none of this - their field set is
     * static and known at construction, while cell fields are discovered from data.
     */
    private syncStore(store: Store) {
        store.setLoadRootAsSummary(this.query.includeRoot);

        const cellFields = this._cellFields ?? [],
            synced = (this._syncedCellFields ??= new WeakMap()),
            prior = synced.get(store);

        // `clearCells` mints a fresh empty array per build, so identity alone is not enough to keep
        // a degenerate (unpivoted) view from re-declaring fields on every one.
        if (prior === cellFields || (isEmpty(prior) && isEmpty(cellFields))) return;

        // Touch only the fields this view declared last time round, leaving the app's own alone.
        // Root-path entries are the value fields themselves, so they fall out as already present.
        const stale = new Set(prior?.map(it => it.name) ?? []),
            retained = store.fields.filter(f => !stale.has(f.name)),
            retainedNames = new Set(retained.map(f => f.name)),
            added = cellFields
                .filter(it => !retainedNames.has(it.name))
                .map(
                    ({name, valueField}) =>
                        new Field({
                            name,
                            type: valueField.type,
                            displayName: valueField.displayName,
                            defaultValue: valueField.defaultValue
                        })
                );

        store.setFields([...retained, ...added]);
        synced.set(store, cellFields);
    }

    /** A change to a *pivot* dimension value restructures the columns - force a full rebuild. */
    protected override hasDimOrBucketUpdates(
        update: StoreRecord[],
        changedFields?: Set<string>
    ): boolean {
        if (super.hasDimOrBucketUpdates(update, changedFields)) return true;

        const names = this.query.pivotDimensionNames;
        if (isEmpty(names)) return false;
        if (changedFields && !names.some(name => changedFields.has(name))) return false;

        for (const rec of update) {
            const cur = this._records.getById(rec.id).data;
            if (names.some(name => rec.data[name] !== cur[name])) return true;
        }
        return false;
    }

    protected override hasStructuralChange(changedFields: Set<string>): boolean {
        return (
            super.hasStructuralChange(changedFields) ||
            this.query.pivotDimensionNames.some(name => changedFields.has(name))
        );
    }

    /**
     * Rewrite the cells touched by a tick onto their owning group rows, then push only group rows to
     * connected stores - cell rows are never published.
     */
    protected override loadUpdatedRows(updatedRows: Set<BaseRow>, changedFields: Set<string>) {
        const groupRows = new Set<BaseRow>(),
            {exposesLeaves} = this;

        updatedRows.forEach(row => {
            if (row instanceof PivotCellRow) {
                this.projectCell(row, changedFields);
                groupRows.add(row.ownerRow);
            } else {
                if (exposesLeaves && row.isLeaf) {
                    this.noteLeafCellFields(row as LeafRow, changedFields);
                }
                groupRows.add(row);
            }
        });

        super.loadUpdatedRows(groupRows, changedFields);
    }

    private clearCells() {
        this.clearVacatedCells(this._cellRows, EMPTY_CELLS);
        this._allPaths = [];
        this._pathKeys = [];
        this._pathLabels = [];
        this._valueFieldNames = [];
        this._paths = [];
        this._cellFields = [];
        this._cellFieldNames = new Map();
        this._pathIdx = new Map();
        this._cellRows = [];
    }

    private generateCells(records: StoreRecord[]) {
        const {_discovery, _rootRows, exposesLeaves} = this,
            prevCells = this._cellRows;
        if (!_discovery || isEmpty(_rootRows)) return this.clearCells();

        const {groups, parentOfGroup, innermost, groupIdxOf} = this.enumerateGroups();
        if (isEmpty(groups)) return this.clearCells();

        // Leaves, aligned to the record order discovery used so path indices carry across.
        const leafRows: LeafRow[] = [],
            leafOwnerGroup: number[] = [],
            leafPathIdx: number[] = [];
        for (let i = 0; i < records.length; i++) {
            const leaf = this._leafMap.get(records[i].id);
            if (!leaf) continue;

            const pathIdx = _discovery.pathIdxOfRecord[i];

            // Stamped on every leaf, owned or not - this is what its cell-field getters read, so a
            // leaf the lattice skips must not keep publishing a previous generation's column.
            if (exposesLeaves) leaf.data._pivotPathIdx = pathIdx;

            const owner = groupIdxOf.get(leaf.parent);
            if (owner == null) continue;
            leafRows.push(leaf);
            leafOwnerGroup.push(owner);
            leafPathIdx.push(pathIdx);
        }
        if (isEmpty(leafRows)) return this.clearCells();

        const lattice = buildPivotLattice({
            groupCount: groups.length,
            parentOfGroup: Int32Array.from(parentOfGroup),
            innermost: Uint8Array.from(innermost),
            leafOwnerGroup: Int32Array.from(leafOwnerGroup),
            leafPathIdx: Int32Array.from(leafPathIdx),
            pathCount: _discovery.paths.length,
            pathParentIdx: _discovery.pathParentIdx,
            pathDepth: _discovery.pathDepth,
            maxDepth: _discovery.maxDepth
        });

        this.buildCellRows(lattice, groups, leafRows);
        this.clearVacatedCells(prevCells, new Set(this._cellRows));
        this._cellRows.forEach(cell => this.projectCell(cell));
    }

    /**
     * Null the slots of cells present in `prev` but not in `live`, and cut any update route still
     * pointing at one.
     *
     * Cells are sparse - a `(group, path)` pair holding no leaves is simply not built - so a cell
     * vacated by a re-partitioning would otherwise leave its last value on a reused owner row forever,
     * where it reads as a real cell and breaks `total == sum of cells`.
     *
     * Retained children must also give up their `pivotParent`. `buildCellRows` reassigns it for every
     * row in the new lattice, but a generation that produces no cells at all reassigns nothing - a
     * live leaf would keep routing ticks into a discarded cell, where `cellFieldNames` throws.
     * `RowCache` covers only the query-change cases; this bail can follow from data alone.
     *
     * Cutting that route is what then makes the cell's own aggregates stale, so it is also marked -
     * `RowCache` may revive it generations later, and unchanged children would otherwise pass for
     * proof that its values are current. Marking rather than evicting keeps the cell and its data
     * object reusable: cells are the most numerous rows in a pivot, and rebuilding every vacated one
     * outright costs far more than re-aggregating the few that come back.
     */
    private clearVacatedCells(prev: PivotCellRow[], live: Set<PivotCellRow>) {
        prev?.forEach(cell => {
            if (live.has(cell)) return;

            cell.children?.forEach(child => {
                if (child.pivotParent === cell) child.pivotParent = null;
            });
            cell.staleAggs = true;

            const {data} = cell.ownerRow;
            if (clearCellSlots(cell, data, EMPTY_NAMES)) this.assignDigest(data as ViewRowData);
        });
    }

    /**
     * Rebuild the published path tree and cell fields, but only when the structure actually changed -
     * their object identity is the structural-change signal consumers key off.
     */
    private syncPaths(specs: PivotPathSpec[]) {
        // Path keys alone are not enough. `updateQuery` can change `valueFields` without moving a
        // single key, and can change `emptyPathLabel` - which reshapes labels while an empty
        // segment's key stays a fixed sentinel. Compared as separate arrays rather than one
        // concatenation, so no value can forge a boundary between them.
        const keys = specs.map(s => s.key),
            labels = specs.map(s => s.label),
            valueFieldNames = this.query.valueFields.map(f => f.name);
        if (
            this._pathKeys &&
            arraysEqual(this._pathKeys, keys) &&
            arraysEqual(this._pathLabels, labels) &&
            arraysEqual(this._valueFieldNames, valueFieldNames)
        ) {
            return;
        }

        const {pivotDimensions, valueFields} = this.query,
            all: PivotPath[] = specs.map(
                s =>
                    new PivotPath({
                        dimension: s.dimIdx >= 0 ? pivotDimensions[s.dimIdx] : null,
                        value: s.value,
                        label: s.label,
                        key: s.key,
                        depth: s.depth,
                        isEmpty: s.isEmpty
                    })
            );

        specs.forEach(s => {
            if (s.parentIdx >= 0) all[s.parentIdx].children.push(all[s.idx]);
        });

        const cellFields: PivotCellField[] = [],
            cellFieldNames = new Map<PivotPath, string[]>(),
            pathIdx = new Map<PivotPath, number>();
        all.forEach((path, idx) => {
            const names = valueFields.map(vf => pivotCellFieldName(path.key, vf.name));
            cellFieldNames.set(path, names);
            pathIdx.set(path, idx);
            valueFields.forEach((valueField, i) => {
                cellFields.push({name: names[i], path, valueField});
            });
        });

        this.validateCellFieldNames(cellFields);

        this._pathKeys = keys;
        this._pathLabels = labels;
        this._valueFieldNames = valueFieldNames;
        this._allPaths = all;
        this._paths = all[0].children;
        this._cellFields = cellFields;
        this._cellFieldNames = cellFieldNames;
        this._pathIdx = pathIdx;
    }

    /**
     * A synthetic cell field colliding with a Cube field would silently overwrite it on row data.
     * Root-path entries are exempt - those *are* the value field, by design.
     */
    private validateCellFieldNames(cellFields: PivotCellField[]) {
        const cubeNames = new Set(this.cube.fields.map(f => f.name));
        cellFields.forEach(({name, path}) => {
            if (!path.isRoot && cubeNames.has(name)) {
                throw new Error(
                    `Generated pivot cell field '${name}' collides with a Cube field of the same ` +
                        `name. Rename the Cube field, or change PivotView.PATH_DELIMITER.`
                );
            }
        });
    }

    /**
     * Instantiate cell rows bottom-up, then wire the two aggregation routes.
     *
     * Cells come out of the lattice ordered by (group, path), and both parents of a cell sit at a
     * *lower* index than it does - so reverse order is a valid bottom-up build for both axes.
     */
    private buildCellRows(lattice: PivotLatticeResult, groups: BaseRow[], leafRows: LeafRow[]) {
        this.buildCellAggFields();

        const {cellCount, cellGroup, cellPath, childStart, childIdx, cellChildKind} = lattice,
            {_allPaths} = this,
            cellRows: PivotCellRow[] = new Array(cellCount);

        for (let c = cellCount - 1; c >= 0; c--) {
            const ownerRow = groups[cellGroup[c]],
                pathIdx = cellPath[c],
                path = _allPaths[pathIdx],
                isLeafKind = cellChildKind[c] === CHILD_KIND_LEAF,
                children: BaseRow[] = [];

            for (let i = childStart[c]; i < childStart[c + 1]; i++) {
                children.push(isLeafKind ? leafRows[childIdx[i]] : cellRows[childIdx[i]]);
            }

            const id = `${ownerRow.id}#${path.key}`,
                row = (cellRows[c] = this._rowCache.getOrCreate(
                    id,
                    children,
                    () => new PivotCellRow(this, id, children, ownerRow, path)
                ));

            // A cache hit means the id and the children match - not that the objects they name are
            // the same instances. Rebind, or a reused cell projects onto a discarded owner row.
            row.ownerRow = ownerRow;
            row.path = path;
        }

        for (let c = 0; c < cellCount; c++) {
            const row = cellRows[c],
                parent = lattice.cellParent[c],
                pivotParent = lattice.cellPivotParent[c];
            row.parent = parent >= 0 ? cellRows[parent] : null;
            row.pivotParent = pivotParent >= 0 ? cellRows[pivotParent] : null;
        }

        for (let l = 0; l < leafRows.length; l++) {
            const cell = lattice.leafPivotParentCell[l];
            leafRows[l].pivotParent = cell >= 0 ? cellRows[cell] : null;
        }

        this._cellRows = cellRows;
    }

    // Cells aggregate the query's value fields, plus any fields those declare a dependence on.
    private buildCellAggFields() {
        const names = new Set<string>();
        this.query.valueFields.forEach(f => {
            names.add(f.name);
            f.dependsOn?.forEach(n => names.add(n));
        });

        const fields: CubeField[] = [];
        names.forEach(name => {
            const field = this.getField(name);
            if (field?.aggregator) fields.push(field);
        });
        this._cellAggFields = fields;
        this._cellAggFieldNames = new Set(fields.map(f => f.name));
        this._cellCanAggregateFnFields = fields.filter(f => f.canAggregateFn);
        this._cellComplexAggFields = fields.filter(f => !f.aggregator.dependsOnChildrenOnly);

        this.pivotRowDataGenerator.onCellAggFieldsChange();
    }

    /**
     * Name an updated leaf's own cell fields into `changedFields`.
     *
     * A leaf's cell values are prototype getters over the same measures it already reports, so they
     * move without being written - but `GridTransactionManager` reads `changedFields` as a complete
     * assertion, and a grid sorted on a pivot value column would otherwise keep a stale row order.
     */
    private noteLeafCellFields(leaf: LeafRow, changedFields: Set<string>) {
        const cell = leaf.pivotParent as PivotCellRow;
        if (cell) this.cellFieldNames(cell).forEach(name => changedFields.add(name));
    }

    /**
     * Write a cell's values onto its owning group row.
     *
     * Cells are published on the owner's data, so a moved cell must move the owner's digest - the
     * owner's own aggregates can be entirely unchanged while its cells move (leaves shifting between
     * pivot paths), and a `canAggregateFn` can keep it out of an incremental update's row set.
     */
    private projectCell(cell: PivotCellRow, changedFields?: Set<string>) {
        const names = this.cellFieldNames(cell),
            {data, ownerRow} = cell,
            ownerData = ownerRow.data,
            {valueFields} = this.query;

        let changed = clearCellSlots(cell, ownerData, names, changedFields);
        for (let i = 0; i < valueFields.length; i++) {
            const name = names[i],
                val = data[valueFields[i].name];
            if (ownerData[name] !== val) {
                ownerData[name] = val;
                changedFields?.add(name);
                changed = true;
            }
        }

        if (changed) this.assignDigest(ownerData as ViewRowData);
    }

    /** A miss means a cached cell outlived its path - `buildCellRows` should have rebound it. */
    private cellFieldNames(cell: PivotCellRow): string[] {
        const ret = this._cellFieldNames.get(cell.path);
        throwIf(!ret, 'No pivot cell fields for this cell path - stale cached cell row.');
        return ret;
    }

    /**
     * Flatten the group nodes of the final (post-bucketing) network. DFS preorder, so a parent always
     * gets a lower index than its children - which is what makes the reverse cell build bottom-up.
     */
    private enumerateGroups() {
        const groups: BaseRow[] = [],
            parentOfGroup: number[] = [],
            innermost: number[] = [],
            groupIdxOf = new Map<BaseRow, number>();

        const visit = (row: BaseRow, parentIdx: number) => {
            if (row.isLeaf) return;

            const idx = groups.length;
            groups.push(row);
            parentOfGroup.push(parentIdx);
            innermost.push(row.children?.some(it => it.isLeaf) ? 1 : 0);
            groupIdxOf.set(row, idx);

            row.children?.forEach(child => visit(child, idx));
        };
        this._rootRows.forEach(row => visit(row, -1));

        return {groups, parentOfGroup, innermost, groupIdxOf};
    }
}

function arraysEqual(a: string[], b: string[]): boolean {
    return a.length === b.length && a.every((v, i) => v === b[i]);
}

/**
 * Point `cell` at the cell fields it is about to write onto its owner, nulling any it wrote last
 * generation and no longer covers. Returns true if a value moved.
 *
 * Name arrays hold their identity while the pivot structure does, so this is an identity check on the
 * common path.
 */
function clearCellSlots(
    row: BaseRow,
    data: PlainObject,
    names: string[],
    changedFields?: Set<string>
): boolean {
    const prior = row.projectedCellNames;
    row.projectedCellNames = names;
    if (!prior || prior === names) return false;

    let changed = false;
    prior.forEach(name => {
        if (!names.includes(name) && data[name] != null) {
            data[name] = null;
            changedFields?.add(name);
            changed = true;
        }
    });
    return changed;
}

const EMPTY_NAMES: string[] = [],
    EMPTY_CELLS = new Set<PivotCellRow>();
