/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2026 Extremely Heavy Industries Inc.
 */

import {PlainObject} from '@xh/hoist/core';
import {StoreRecord} from '@xh/hoist/data';
import {isEmpty} from 'lodash';
import {
    buildPivotLattice,
    CHILD_KIND_LEAF,
    discoverPivotPaths,
    PATH_DELIMITER,
    pivotCellFieldName,
    type PivotLatticeResult,
    type PivotPathSpec
} from './impl/PivotLattice';
import {CubeField} from './CubeField';
import {PivotCellField, PivotPath} from './PivotPath';
import {PivotQuery} from './PivotQuery';
import {BaseRow} from './row/BaseRow';
import {LeafRow} from './row/LeafRow';
import {PivotCellRow} from './row/PivotCellRow';
import {View, ViewConfig, ViewResult} from './View';

export interface PivotViewResult extends ViewResult {
    /**
     * Pivot path tree, top-level paths first with nested `children`. Identity-stable while the pivot
     * structure is unchanged - track it to decide whether to rebuild columns.
     */
    paths: PivotPath[];

    /**
     * One entry per (path, value field), including the root-path row totals. Identity-stable with
     * `paths` - track it to decide whether to re-declare Store fields.
     */
    cellFields: PivotCellField[];
}

/**
 * A {@link View} that additionally slices its measures across a pivot axis, producing a compact
 * table of `(group row, pivot path)` cells alongside the usual row hierarchy.
 *
 * Create via {@link Cube.createPivotView}. Cell values arrive as flat synthetic fields on the
 * published row data, named per {@link PivotViewResult.cellFields} - so they are ordinary Store
 * fields, and work with grid column filters, Excel export, and inline editing.
 *
 * The row hierarchy and the pivot hierarchy are orthogonal: every node of the row hierarchy carries
 * its own pivot subtree of {@link PivotCellRow}s. Those are real rows in the aggregation network, so
 * every aggregator works unmodified and ticks propagate incrementally, but they never enter the
 * visible tree or reach a connected Store.
 *
 * See the Cube package README (`data/cube/README.md`) for pivot patterns.
 *
 * @see PivotQuery
 * @mcpHint live or snapshot pivoted view of aggregated Cube data
 */
export class PivotView extends View {
    /** Separator between pivot path segments, and between a path key and its value field. */
    static PATH_DELIMITER = PATH_DELIMITER;

    declare query: PivotQuery;
    declare result: PivotViewResult;

    // Implementation - declared, never initialized. Field initializers on a View subclass would run
    // *after* super()'s constructor-time fullUpdate() and wipe everything generated by it.
    declare protected _allPaths: PivotPath[];
    declare protected _pathKeys: string[];
    declare protected _paths: PivotPath[];
    declare protected _cellFields: PivotCellField[];
    /** Keyed on path *identity*, so a cell can never resolve names for a path it no longer holds. */
    declare protected _cellFieldNames: Map<PivotPath, string[]>;
    declare protected _cellRows: PivotCellRow[];
    declare protected _cellAggFields: CubeField[];

    /** @internal - applications should use {@link Cube.createPivotView} */
    constructor(config: ViewConfig) {
        super(config);
    }

    /** Fields aggregated on cell rows - the value fields plus their declared dependencies. */
    get cellAggFields(): CubeField[] {
        if (!this._cellAggFields) {
            const names = new Set<string>();
            this.query.valueFields.forEach(f => {
                names.add(f.name);
                f.dependsOn?.forEach(n => names.add(n));
            });
            this._cellAggFields = this.fields.filter(f => names.has(f.name));
        }
        return this._cellAggFields;
    }

    //------------------------
    // Implementation
    //------------------------
    protected override generateRows() {
        super.generateRows();
        this.generateCells();
    }

    protected override createResult(): PivotViewResult {
        return {
            ...super.createResult(),
            paths: this._paths ?? [],
            cellFields: this._cellFields ?? []
        };
    }

    /** A change to a *pivot* dimension value restructures the columns - force a full rebuild. */
    protected override hasDimOrBucketUpdates(update: StoreRecord[]): boolean {
        if (super.hasDimOrBucketUpdates(update)) return true;

        const names = this.query.pivotDimensionNames;
        if (isEmpty(names)) return false;

        for (const rec of update) {
            const cur = this._leafMap.get(rec.id);
            if (names.some(name => rec.data[name] !== cur.data[name])) return true;
        }
        return false;
    }

    /**
     * Rewrite the cells touched by a tick onto their owning group rows, then push only group rows to
     * connected stores - cell rows are never published.
     */
    protected override loadUpdatedRows(updatedRows: Set<BaseRow>) {
        const groupRows = new Set<BaseRow>(),
            {exposesLeaves} = this;

        updatedRows.forEach(row => {
            if (row instanceof PivotCellRow) {
                this.projectCell(row);
                groupRows.add(row.ownerRow);
            } else {
                if (exposesLeaves && row.isLeaf) this.projectLeaf(row as LeafRow);
                groupRows.add(row);
            }
        });

        // Projection mutates owner data after the base class has stamped digests, and an owner whose
        // own aggregates held is never in `updatedRows` - restamp, or connected stores read an
        // unchanged digest and skip the record rebuild, leaving stale cells in the grid.
        groupRows.forEach(row => this.noteRowDataMutated(row.data));

        super.loadUpdatedRows(groupRows);
    }

    private clearCells() {
        this._allPaths = [];
        this._pathKeys = [];
        this._paths = [];
        this._cellFields = [];
        this._cellFieldNames = new Map();
        this._cellRows = [];
    }

    private generateCells() {
        const {query, _rootRows} = this;
        if (!query.isPivoted || isEmpty(_rootRows)) return this.clearCells();

        const {groups, parentOfGroup, innermost, groupIdxOf} = this.enumerateGroups();
        if (isEmpty(groups)) return this.clearCells();

        const records = this._aggContext.filteredRecords,
            discovery = discoverPivotPaths(records, query.pivotDimensionNames, {
                emptyPathLabel: query.emptyPathLabel,
                maxPivotPaths: query.maxPivotPaths
            });

        // Leaves, aligned to the record order discovery used so path indices carry across.
        const leafRows: LeafRow[] = [],
            leafOwnerGroup: number[] = [],
            leafPathIdx: number[] = [];
        for (let i = 0; i < records.length; i++) {
            const leaf = this._leafMap.get(records[i].id),
                owner = leaf ? groupIdxOf.get(leaf.parent) : null;
            if (owner == null) continue;
            leafRows.push(leaf);
            leafOwnerGroup.push(owner);
            leafPathIdx.push(discovery.pathIdxOfRecord[i]);
        }
        if (isEmpty(leafRows)) return this.clearCells();

        const lattice = buildPivotLattice({
            groupCount: groups.length,
            parentOfGroup: Int32Array.from(parentOfGroup),
            innermost: Uint8Array.from(innermost),
            leafOwnerGroup: Int32Array.from(leafOwnerGroup),
            leafPathIdx: Int32Array.from(leafPathIdx),
            pathCount: discovery.paths.length,
            pathParentIdx: discovery.pathParentIdx,
            pathDepth: discovery.pathDepth,
            maxDepth: discovery.maxDepth
        });

        this.syncPaths(discovery.paths);
        this.buildCellRows(lattice, groups, leafRows);
        this.projectCells(leafRows);
    }

    /**
     * Rebuild the published path tree and cell fields, but only when the structure actually changed -
     * their object identity is the structural-change signal consumers key off.
     */
    private syncPaths(specs: PivotPathSpec[]) {
        const keys = specs.map(s => s.key);
        if (this._pathKeys && arraysEqual(this._pathKeys, keys)) return;

        const {pivotDimensions, valueFields} = this.query,
            all: PivotPath[] = specs.map(
                s =>
                    new PivotPath({
                        dimension: s.dimIdx >= 0 ? pivotDimensions[s.dimIdx] : null,
                        value: s.value,
                        label: s.label,
                        key: s.key,
                        depth: s.depth,
                        isEmpty: s.isEmpty
                    })
            );

        specs.forEach(s => {
            if (s.parentIdx >= 0) all[s.parentIdx].children.push(all[s.idx]);
        });

        const cellFields: PivotCellField[] = [],
            cellFieldNames = new Map<PivotPath, string[]>();
        all.forEach(path => {
            const names = valueFields.map(vf => pivotCellFieldName(path.key, vf.name));
            cellFieldNames.set(path, names);
            valueFields.forEach((valueField, i) => {
                cellFields.push({name: names[i], path, valueField});
            });
        });

        this.validateCellFieldNames(cellFields);

        this._pathKeys = keys;
        this._allPaths = all;
        this._paths = all[0].children;
        this._cellFields = cellFields;
        this._cellFieldNames = cellFieldNames;
    }

    /**
     * A synthetic cell field colliding with a Cube field would silently overwrite it on row data.
     * Root-path entries are exempt - those *are* the value field, by design.
     */
    private validateCellFieldNames(cellFields: PivotCellField[]) {
        const cubeNames = new Set(this.cube.fields.map(f => f.name));
        cellFields.forEach(({name, path}) => {
            if (!path.isRoot && cubeNames.has(name)) {
                throw new Error(
                    `Generated pivot cell field '${name}' collides with a Cube field of the same ` +
                        `name. Rename the Cube field, or change PivotView.PATH_DELIMITER.`
                );
            }
        });
    }

    /**
     * Instantiate cell rows bottom-up, then wire the two aggregation routes.
     *
     * Cells come out of the lattice ordered by (group, path), and both parents of a cell sit at a
     * *lower* index than it does - so reverse order is a valid bottom-up build for both axes.
     */
    private buildCellRows(lattice: PivotLatticeResult, groups: BaseRow[], leafRows: LeafRow[]) {
        const {cellCount, cellGroup, cellPath, childStart, childIdx, cellChildKind} = lattice,
            {_allPaths} = this,
            valueFields = this.cellAggFields,
            cellRows: PivotCellRow[] = new Array(cellCount),
            canAggregateOfPath: PlainObject[] = new Array(_allPaths.length);

        for (let c = cellCount - 1; c >= 0; c--) {
            const ownerRow = groups[cellGroup[c]],
                pathIdx = cellPath[c],
                path = _allPaths[pathIdx],
                isLeafKind = cellChildKind[c] === CHILD_KIND_LEAF,
                children: BaseRow[] = [];

            for (let i = childStart[c]; i < childStart[c + 1]; i++) {
                children.push(isLeafKind ? leafRows[childIdx[i]] : cellRows[childIdx[i]]);
            }

            // One canAggregate map per path, shared by every cell on it.
            const canAggregate = (canAggregateOfPath[pathIdx] ??= this.cellCanAggregate(
                path,
                valueFields
            ));

            const id = `${ownerRow.id}#${path.key}`,
                row = (cellRows[c] = this._rowCache.getOrCreate(
                    id,
                    children,
                    () =>
                        new PivotCellRow(
                            this,
                            id,
                            children,
                            ownerRow,
                            path,
                            valueFields,
                            canAggregate
                        )
                ));

            // A cache hit means the id and the children match - not that the objects they name are
            // the same instances. Rebind, or a reused cell projects onto a discarded owner row.
            row.ownerRow = ownerRow;
            row.path = path;
        }

        for (let c = 0; c < cellCount; c++) {
            const row = cellRows[c],
                parent = lattice.cellParent[c],
                pivotParent = lattice.cellPivotParent[c];
            row.parent = parent >= 0 ? cellRows[parent] : null;
            row.pivotParent = pivotParent >= 0 ? cellRows[pivotParent] : null;
        }

        for (let l = 0; l < leafRows.length; l++) {
            const cell = lattice.leafPivotParentCell[l];
            leafRows[l].pivotParent = cell >= 0 ? cellRows[cell] : null;
        }

        this._cellRows = cellRows;
    }

    private cellCanAggregate(path: PivotPath, valueFields: CubeField[]): PlainObject {
        const ctx = this._aggContext;
        return valueFields.reduce((ret, field) => {
            const {aggregator, canAggregateFn} = field;
            ret[field.name] =
                aggregator &&
                (!canAggregateFn || canAggregateFn(path.dimension?.name, path.value, {}, ctx));
            return ret;
        }, {} as PlainObject);
    }

    private projectCells(leafRows: LeafRow[]) {
        this._cellRows.forEach(cell => this.projectCell(cell));

        // An exposed leaf carries a value for its own path only, so a drilled-down row reads as a
        // single populated pivot column rather than a blank one. Hidden leaves are skipped - their
        // data is a shared reference to Cube record data and must never be mutated.
        if (this.exposesLeaves) leafRows.forEach(leaf => this.projectLeaf(leaf));
    }

    /** A leaf's own full-path cell is exactly its `pivotParent`, so no extra bookkeeping is needed. */
    private projectLeaf(leaf: LeafRow) {
        const cell = leaf.pivotParent as PivotCellRow;
        if (!cell) return;

        const names = this._cellFieldNames.get(cell.path),
            {valueFields} = this.query,
            {data} = leaf;

        for (let i = 0; i < valueFields.length; i++) {
            data[names[i]] = data[valueFields[i].name];
        }
    }

    private projectCell(cell: PivotCellRow) {
        const names = this._cellFieldNames.get(cell.path),
            {data, ownerRow} = cell,
            ownerData = ownerRow.data,
            {valueFields} = this.query;

        for (let i = 0; i < valueFields.length; i++) {
            ownerData[names[i]] = data[valueFields[i].name];
        }
    }

    /**
     * Flatten the group nodes of the final (post-bucketing) network. DFS preorder, so a parent always
     * gets a lower index than its children - which is what makes the reverse cell build bottom-up.
     */
    private enumerateGroups() {
        const groups: BaseRow[] = [],
            parentOfGroup: number[] = [],
            innermost: number[] = [],
            groupIdxOf = new Map<BaseRow, number>();

        const visit = (row: BaseRow, parentIdx: number) => {
            if (row.isLeaf) return;

            const idx = groups.length;
            groups.push(row);
            parentOfGroup.push(parentIdx);
            innermost.push(row.children?.some(it => it.isLeaf) ? 1 : 0);
            groupIdxOf.set(row, idx);

            row.children?.forEach(child => visit(child, idx));
        };
        this._rootRows.forEach(row => visit(row, -1));

        return {groups, parentOfGroup, innermost, groupIdxOf};
    }
}

function arraysEqual(a: string[], b: string[]): boolean {
    return a.length === b.length && a.every((v, i) => v === b[i]);
}
